
// unit id, pc_alive, pc_recruited, npc_alive, misc, chapter_min, line string
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "Ah. Uh... Uhhhh. Sniff. Ah.... Oh...")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "...")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "Ah! *wolf companion name*! Haha, stop.")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "Stop! ...Sniff...")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "I won't see Teharon ever again...")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "Me? ")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "Kill a Bison?")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "He will trample me...")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "I want as the Goddess, but...")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "ihaaa .. ih?")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "You want to hunt, *kakwi wolf companion name*?")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "Bisons travel in a herd.")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "They are easy to track...")
