
// Setting: Kakwi is looking at the rolling hills, preparing to face the bison with her animal companions, just as the warriors of her tribe do. Teharon comes up to her from behind.

// unit id, pc_alive, pc_recruited, npc_alive, misc, chapter_min, line string
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "...") 
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "You know this place, Kakwi?") 
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "I heard my fathers and brothers stories...") 
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "But my eyes only see the hills for the first.") 
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "They are just as beautiful as I remember.") 
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "How long ago was it?") 
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "More than a thousand suns.") 
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "I killed my Bison just as the Rift ripped open...")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "My younger brothers went to war when I was drying the meat.")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "When I was returning, everything was settled, we had lost.")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "I was hunted.")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "I abandoned the meat...")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "Yes, I remember.")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "My fathers and my brothers ran for revenge after the Night of Blood and Tears.")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "They did not return.")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "But you did.")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "Godspouses! / Gods and Goddesses!")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "The goddess wants as I...")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "Shame me being not there.")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "Shame my empty hands.")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "Shame my life.")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "No shame!")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "None!")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "The Rift is not your fault! ")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "No one could know.")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "You are alone, *horse name* is alone!")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "Still alone, you ride to war!")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "No one should run to war alone!")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "There are no more warriors.")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "They ran into the setting Sun, Kakwi.")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "Now there is only babes and elders.")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "I run until die.")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "* Horse name * never fled, not even when I pushed him. ")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "Alone warrior and his companion.")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "No, not alone.")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "Yes, that is true!")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "You are here.")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "So are the Voldans!")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "They have taken me to the gates of "Kewacate city names".")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "Aaion was forced to discuss with us!")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "You won't be alone anymore.")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "Eh? I was not alone already...")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "If I am to be a warrior, I must do as the warriors.")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "Ah!")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "But Kakwi, you can fight now.")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "It shames me, it shames the Kesiru and the Kewac, it shames the Gods.")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "I should have bagged you and brought you home... ")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "What would...")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "Do not!! ")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "Do not speak of home!")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "The Kiseru needs warriors, here and now.")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "The Voldans are not warriors, yet they fight.")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "You fought until now!")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "My Teharon.")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "Clear like summer river water...")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "You worry...")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "But it must be done.")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "The Goddess has taken my womanhood.")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "Months before.")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "Taken wh...? ")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "No... ")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "Do not speak of this! ")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "This is terrible...")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "Listen, Teharon.")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "It has yet to return to me.")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "The tribe has no need of women, She speaks it so.")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "The Goddess wants as I, and the I want as the Goddess.")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "Hunting a Bison is hard, and slaying it is hopeless.")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "Curing meat takes time.")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "Carrying what remains slows down even the mightiest.")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "We do not have time for this!")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "The Gods know of our circumstances, and they already forgiven, even if I not do all the rituals.")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "My Eldest, Wenna did not return!")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "Your younger, Nawake too!")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "Stop this madness.")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "We need you! ")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "Here, now!")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "I, need...")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "Do not!")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "Ah, my Teharon, close your face... ")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "or my will open also...")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "I will return.")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "I will help you mend the Tribal Rift.")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "The Goddess wants as I, and the I want as the Goddess.")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "I... I want as the Goddess.")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "My sister.")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "You are to become Woman, or stay Girl forever.")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "From now you ride alone.")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "Victorious, come back arms full and heart strong.")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "Go, conquer the Bison.")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "Return to us...")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "I have to go, now...")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "Uh...")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "Uhn...")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "Sniff...")