
// unit id, pc_alive, pc_recruited, npc_alive, misc, chapter_min, line string
REGISTER_ENUM(UNIT_NAME_RANDOM_GUARD, 0,0,0,0,0, "Teharon! ")
REGISTER_ENUM(UNIT_NAME_RANDOM_GUARD, 0,0,0,0,0, "Teharon, Come with me. ")
REGISTER_ENUM(UNIT_NAME_RANDOM_GUARD, 0,0,0,0,0, "Quickly.")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "What is going on?")
REGISTER_ENUM(UNIT_NAME_RANDOM_GUARD, 0,0,0,0,0, "I was on guard duty, and we captured an intruder! ")
REGISTER_ENUM(UNIT_NAME_RANDOM_GUARD, 0,0,0,0,0, "X had a sense that someone was watching us... I think she is looking for you.")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "For me? She? ")
REGISTER_ENUM(UNIT_NAME_RANDOM_GUARD, 0,0,0,0,0, "I think she is kewac, she has a pet wolf cub.")
REGISTER_ENUM(UNIT_NAME_RANDOM_GUARD, 0,0,0,0,0, "It ran away as soon as it saw X! ")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "Ah.")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "Oh, no!")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "It's her! ")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "Mercy!")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "Mercy, please!")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "Kakwi!")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "You foolish, small head mule in girl skin!")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "Why do you come here??")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "Teharon!")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "Help me!")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "X, please.")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "She is armed, has a wolf pup, and attacked us before you arrive.")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "She can talk as she is.")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "Kakwi what do you think they do to their enemies!")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "Worthless!")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "Traitor! ")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "I am your blood! ")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "Help me, it hurts!")
REGISTER_ENUM(UNIT_NAME_ERWIN, 0,0,0,0,0, "Now that, that is quite a mess! ")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "I will not run!")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "You should!")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "Run back to the village.")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "Go where you belong!")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "No!")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "Girl, I should bag you and carry back myself...")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "There are still the sick at home, and the companions...")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "Do not!! ")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "Do not speak of home like this!")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "You left, again!")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "This war is not over, Kakwi.")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "The kingdom of ... ride the eternal plains.")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "They are the true enemy of the riders and the runners.")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "I cannot go back.")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "I join you!")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "No!")
REGISTER_ENUM(UNIT_NAME_ERWIN, 0,0,0,0,0, "A new recruit?")
REGISTER_ENUM(UNIT_NAME_ERWIN, 0,0,0,0,0, "X, let her go.")
REGISTER_ENUM(UNIT_NAME_RANDOM_GUARD, 0,0,0,0,0, "...")
REGISTER_ENUM(UNIT_NAME_RANDOM_GUARD, 0,0,0,0,0, "Yes, commander! ")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "Oof!")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "Thank you ChiefWarrior.")
REGISTER_ENUM(UNIT_NAME_ERWIN, 0,0,0,0,0, "What do you have to give this army?")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "Erwin of Eifailwen, do not...")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "My bow, my arrows, my wolf companion.")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "I will fight. ")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "As long as Teharon is here.")
REGISTER_ENUM(UNIT_NAME_ERWIN, 0,0,0,0,0, "She likes you a lot. ")
REGISTER_ENUM(UNIT_NAME_ERWIN, 0,0,0,0,0, "Now Teharon,  what do you think about her? ")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "Weak girl. ")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "Shouts a lot. ")
REGISTER_ENUM(UNIT_NAME_TEHARON, 0,0,0,0,0, "Cannot follow orders. ")
REGISTER_ENUM(UNIT_NAME_ERWIN, 0,0,0,0,0, "And stubborn. ")
REGISTER_ENUM(UNIT_NAME_ERWIN, 0,0,0,0,0, "Welcome to the Gaolinian Militia! ")
REGISTER_ENUM(UNIT_NAME_KAKWI, 0,0,0,0,0, "Erwin! This brat injured me.")
REGISTER_ENUM(UNIT_NAME_ERWIN, 0,0,0,0,0, "I did not forget.")
REGISTER_ENUM(UNIT_NAME_ERWIN, 0,0,0,0,0, "Drawing your weapons at your brothers is 5 lashes. ")
REGISTER_ENUM(UNIT_NAME_ERWIN, 0,0,0,0,0, "Causing injury is 10 lashes.")