#include "minctest.h"
#include "convoy.hpp"

void test_convoy() {
    testConvoyfull();
    testConvoysortStats();
    // testConvoyWriteXML();
    testConvoysortused();
}

void testConvoyfull() {
    Convoy test_convoy;
    Inventory_item temp;
    temp.id = ITEM::NAME::WOODEN_SWORD;
    test_convoy.deposit(temp);

    for (int i = 0; i < (DEFAULT::CONVOY_SIZE + 2); i++) {
        test_convoy.deposit(temp);
    }

    test_convoy.withdraw(0, ITEM::TYPE::SWORD);
    test_convoy.withdraw(1, ITEM::TYPE::SWORD);
    temp.id = ITEM::NAME::DAMAS_LANCE;
    test_convoy.deposit(temp);
    test_convoy.deposit(temp);
}

void testConvoysortused() {
    SDL_Log("Testing Convoy sorting for stats and uses abilities");
    Convoy test_convoy;
    Inventory_item temp;
    temp.id = ITEM::NAME::WOODEN_SWORD;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::KITCHEN_KNIFE;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::WRATH_SWORD;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::FLEURET;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::DAMAS_SWORD;
    temp.used = 0;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::DAMAS_SWORD;
    temp.used = 1;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::WOODEN_SWORD;
    temp.used = 1;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::WOODEN_SWORD;
    temp.used = 2;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::WOODEN_SWORD;
    temp.used = 20;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::WOODEN_SWORD;
    temp.used = 21;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::WOODEN_SWORD;
    temp.used = 10;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::WOODEN_SWORD;
    temp.used = 11;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::WOODEN_SWORD;
    temp.used = 12;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::WOODEN_SWORD;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::IRON_SWORD;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::STEEL_SWORD;
    test_convoy.deposit(temp);
    SDL_Log("SWORD: Base Convoy Order.");
    test_convoy.printContents(ITEM::TYPE::SWORD);
    test_convoy.printStats(ITEM::TYPE::SWORD, ITEM::STAT::USES_LEFT);
    SDL_Log("Sorting swords according to Pmight");
    test_convoy.sortStats(ITEM::TYPE::SWORD, ITEM::STAT::PMIGHT);
    test_convoy.sort(ITEM::TYPE::SWORD, ITEM::STAT::PMIGHT);
    test_convoy.printStats(ITEM::TYPE::SWORD, ITEM::STAT::USES_LEFT);
}

void testConvoyWriteXML() {
    SDL_Log("Testing Convoy for writeXML abilities.");
    Convoy test_convoy;
    Inventory_item temp;
    temp.id = ITEM::NAME::WOODEN_SWORD;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::KITCHEN_KNIFE;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::WRATH_SWORD;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::FLEURET;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::DAMAS_SWORD;
    temp.used = 0;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::DAMAS_SWORD;
    temp.used = 1;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::WOODEN_SWORD;
    temp.used = 1;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::WOODEN_SWORD;
    temp.used = 2;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::WOODEN_SWORD;
    temp.used = 20;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::WOODEN_SWORD;
    temp.used = 21;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::WOODEN_SWORD;
    temp.used = 10;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::WOODEN_SWORD;
    temp.used = 11;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::WOODEN_SWORD;
    temp.used = 12;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::WOODEN_SWORD;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::IRON_SWORD;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::STEEL_SWORD;

    temp.id = ITEM::NAME::DAMAS_LANCE;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::ACHILLES;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::VEL;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::IRON_LANCE;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::TONBOKIRI;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::DAMAS_LANCE;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::WRATH_LANCE;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::WRATH_LANCE;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::TRIDENT;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::SPEAR;
    test_convoy.deposit(temp);
    test_convoy.writeXML("convoy_test.xml");

    Convoy test_convoy2;
    test_convoy2.readXML("convoy_test.xml");
    test_convoy2.writeXML("convoy_rewrite.xml");
}

void testConvoysortStats() {
    SDL_Log("Testing Convoy for stat sorting abilities");
    Convoy test_convoy;
    Inventory_item temp;
    temp.id = ITEM::NAME::WOODEN_SWORD;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::KITCHEN_KNIFE;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::WRATH_SWORD;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::FLEURET;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::DAMAS_SWORD;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::DAMAS_SWORD;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::WOODEN_SWORD;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::WOODEN_SWORD;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::IRON_SWORD;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::STEEL_SWORD;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::DAMAS_SWORD;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::ESPADON;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::EXSANGUE;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::SECUNDUS;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::FAUCHON;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::SABER;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::GALATINE;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::HAUTECLAIRE;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::BROADSWORD;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::MERCIFUL_BLADE;
    test_convoy.deposit(temp);

    temp.id = ITEM::NAME::DAMAS_LANCE;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::ACHILLES;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::VEL;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::IRON_LANCE;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::TONBOKIRI;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::DAMAS_LANCE;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::WRATH_LANCE;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::WRATH_LANCE;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::TRIDENT;
    test_convoy.deposit(temp);
    temp.id = ITEM::NAME::SPEAR;
    test_convoy.deposit(temp);

    SDL_Log("SWORD: Base Convoy Order.");
    test_convoy.printContents(ITEM::TYPE::SWORD);
    SDL_Log("Sorting swords according to Pmight");
    test_convoy.sortStats(ITEM::TYPE::SWORD, ITEM::STAT::PMIGHT);
    test_convoy.printStats(ITEM::TYPE::SWORD, ITEM::STAT::PMIGHT);
    SDL_Log("Sorting swords according to Mmight");
    test_convoy.sortStats(ITEM::TYPE::SWORD, ITEM::STAT::MMIGHT);
    test_convoy.printStats(ITEM::TYPE::SWORD, ITEM::STAT::MMIGHT);
    SDL_Log("Sorting swords according to hit");
    test_convoy.sortStats(ITEM::TYPE::SWORD, ITEM::STAT::HIT);
    test_convoy.printStats(ITEM::TYPE::SWORD, ITEM::STAT::HIT);
    SDL_Log("Sorting swords according to dodge");
    test_convoy.sortStats(ITEM::TYPE::SWORD, ITEM::STAT::DODGE);
    test_convoy.printStats(ITEM::TYPE::SWORD, ITEM::STAT::DODGE);
    SDL_Log("Sorting swords according to crit");
    test_convoy.sortStats(ITEM::TYPE::SWORD, ITEM::STAT::CRIT);
    test_convoy.printStats(ITEM::TYPE::SWORD, ITEM::STAT::CRIT);
    SDL_Log("Sorting swords according to favor");
    test_convoy.sortStats(ITEM::TYPE::SWORD, ITEM::STAT::FAVOR);
    test_convoy.printStats(ITEM::TYPE::SWORD, ITEM::STAT::FAVOR);
    SDL_Log("Sorting swords according to weight");
    test_convoy.sortStats(ITEM::TYPE::SWORD, ITEM::STAT::WGT);
    test_convoy.printStats(ITEM::TYPE::SWORD, ITEM::STAT::WGT);
    SDL_Log("Sorting swords according to uses");
    test_convoy.sortStats(ITEM::TYPE::SWORD, ITEM::STAT::USES);
    test_convoy.printStats(ITEM::TYPE::SWORD, ITEM::STAT::USES);
    SDL_Log("Sorting swords according to proficiency");
    test_convoy.sortStats(ITEM::TYPE::SWORD, ITEM::STAT::PROF);
    test_convoy.printStats(ITEM::TYPE::SWORD, ITEM::STAT::PROF);
    SDL_Log("Sorting swords according to price");
    test_convoy.sortStats(ITEM::TYPE::SWORD, ITEM::STAT::PRICE);
    test_convoy.printStats(ITEM::TYPE::SWORD, ITEM::STAT::PRICE);

    SDL_Log("LANCE: Base Convoy Order.");
    test_convoy.printContents(ITEM::TYPE::LANCE);
    SDL_Log("Sorting lances according to Pmight");
    test_convoy.sortStats(ITEM::TYPE::LANCE, ITEM::STAT::PMIGHT);
    test_convoy.printStats(ITEM::TYPE::LANCE, ITEM::STAT::PMIGHT);
    SDL_Log("Sorting lances according to Mmight");
    test_convoy.sortStats(ITEM::TYPE::LANCE, ITEM::STAT::MMIGHT);
    test_convoy.printStats(ITEM::TYPE::LANCE, ITEM::STAT::MMIGHT);
    SDL_Log("Sorting lances according to hit");
    test_convoy.sortStats(ITEM::TYPE::LANCE, ITEM::STAT::HIT);
    test_convoy.printStats(ITEM::TYPE::LANCE, ITEM::STAT::HIT);
    SDL_Log("Sorting lances according to dodge");
    test_convoy.sortStats(ITEM::TYPE::LANCE, ITEM::STAT::DODGE);
    test_convoy.printStats(ITEM::TYPE::LANCE, ITEM::STAT::DODGE);
    SDL_Log("Sorting lances according to crit");
    test_convoy.sortStats(ITEM::TYPE::LANCE, ITEM::STAT::CRIT);
    test_convoy.printStats(ITEM::TYPE::LANCE, ITEM::STAT::CRIT);
    SDL_Log("Sorting lances according to favor");
    test_convoy.sortStats(ITEM::TYPE::LANCE, ITEM::STAT::FAVOR);
    test_convoy.printStats(ITEM::TYPE::LANCE, ITEM::STAT::FAVOR);
    SDL_Log("Sorting lances according to weight");
    test_convoy.sortStats(ITEM::TYPE::LANCE, ITEM::STAT::WGT);
    test_convoy.printStats(ITEM::TYPE::LANCE, ITEM::STAT::WGT);
    SDL_Log("Sorting lances according to uses");
    test_convoy.sortStats(ITEM::TYPE::LANCE, ITEM::STAT::USES);
    test_convoy.printStats(ITEM::TYPE::LANCE, ITEM::STAT::USES);
    SDL_Log("Sorting lances according to proficiency");
    test_convoy.sortStats(ITEM::TYPE::LANCE, ITEM::STAT::PROF);
    test_convoy.printStats(ITEM::TYPE::LANCE, ITEM::STAT::PROF);
    SDL_Log("Sorting lances according to minimum range");
    test_convoy.sortStats(ITEM::TYPE::LANCE, ITEM::STAT::RANGEMIN);
    test_convoy.printStats(ITEM::TYPE::LANCE, ITEM::STAT::RANGEMIN);
    SDL_Log("Sorting lances according to maximum range");
    test_convoy.sortStats(ITEM::TYPE::LANCE, ITEM::STAT::RANGEMAX);
    test_convoy.printStats(ITEM::TYPE::LANCE, ITEM::STAT::RANGEMAX);
    SDL_Log("Sorting lances according to price");
    test_convoy.sortStats(ITEM::TYPE::LANCE, ITEM::STAT::PRICE);
    test_convoy.printStats(ITEM::TYPE::LANCE, ITEM::STAT::PRICE);
}