#include "minctest.h"
#include "convoy.hpp"

void testConvoyfull() {
    Convoy convoy;
    Inventory_item temp;
    std::unordered_map<short int, Weapon> weapons;
    convoy.setWeapons(&weapons);
    temp.id = ITEM::NAME::WOODEN_SWORD;
    convoy.deposit(temp);

    for (int i = 0; i < (DEFAULT::CONVOY_SIZE + 2); i++) {
        convoy.deposit(temp);
    }

    convoy.withdraw(0, ITEM::TYPE::SWORD);
    convoy.withdraw(1, ITEM::TYPE::SWORD);
    temp.id = ITEM::NAME::DAMAS_LANCE;
    convoy.deposit(temp);
    convoy.deposit(temp);
    lok(convoy.isFull());
}

void testConvoysortused() {
    Convoy convoy;
    std::unordered_map<short int, Weapon> weapons;
    convoy.setWeapons(&weapons);
    Inventory_item temp;
    temp.id = ITEM::NAME::WOODEN_SWORD;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::KITCHEN_KNIFE;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::WRATH_SWORD;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::FLEURET;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::DAMAS_SWORD;
    temp.used = 0;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::DAMAS_SWORD;
    temp.used = 1;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::WOODEN_SWORD;
    temp.used = 1;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::WOODEN_SWORD;
    temp.used = 2;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::WOODEN_SWORD;
    temp.used = 20;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::WOODEN_SWORD;
    temp.used = 21;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::WOODEN_SWORD;
    temp.used = 10;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::WOODEN_SWORD;
    temp.used = 11;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::WOODEN_SWORD;
    temp.used = 12;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::WOODEN_SWORD;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::IRON_SWORD;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::STEEL_SWORD;
    convoy.deposit(temp);
    convoy.printContents(ITEM::TYPE::SWORD);
    convoy.printStats(ITEM::TYPE::SWORD, ITEM::STAT::USES_LEFT);
    convoy.sortStats(ITEM::TYPE::SWORD, ITEM::STAT::PMIGHT);
    convoy.sort(ITEM::TYPE::SWORD, ITEM::STAT::PMIGHT);
    convoy.printStats(ITEM::TYPE::SWORD, ITEM::STAT::USES_LEFT);
}

void testConvoyWriteRead() {
    Convoy convoy;
    std::unordered_map<short int, Weapon> weapons;
    convoy.setWeapons(&weapons);
    Inventory_item temp;
    temp.id = ITEM::NAME::WOODEN_SWORD;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::KITCHEN_KNIFE;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::WRATH_SWORD;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::FLEURET;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::DAMAS_SWORD;
    temp.used = 0;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::DAMAS_SWORD;
    temp.used = 1;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::WOODEN_SWORD;
    temp.used = 1;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::WOODEN_SWORD;
    temp.used = 2;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::WOODEN_SWORD;
    temp.used = 20;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::WOODEN_SWORD;
    temp.used = 21;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::WOODEN_SWORD;
    temp.used = 10;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::WOODEN_SWORD;
    temp.used = 11;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::WOODEN_SWORD;
    temp.used = 12;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::WOODEN_SWORD;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::IRON_SWORD;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::STEEL_SWORD;

    temp.id = ITEM::NAME::DAMAS_LANCE;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::ACHILLES;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::VEL;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::IRON_LANCE;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::TONBOKIRI;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::DAMAS_LANCE;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::WRATH_LANCE;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::WRATH_LANCE;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::TRIDENT;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::SPEAR;
    convoy.deposit(temp);

    if (PHYSFS_stat("saves", nullptr) == 0) {
        PHYSFS_mkdir("saves");
    }

    convoy.writeXML("saves//convoy_test.xml", false);
    convoy.writeJSON("saves//convoy_test.json", false);
    std::unordered_map<short int, Weapon> weapons2;
    std::unordered_map<short int, Weapon> weapons3;
    Convoy convoy2, convoy3;
    convoy2.setWeapons(&weapons2);
    convoy3.setWeapons(&weapons3);
    convoy2.readXML("saves//convoy_test.xml");
    convoy2.writeXML("saves//convoy_rewrite.xml");
    // lok(fequal("saves//convoy_rewrite.xml", "saves//convoy_test.xml"));
    convoy3.readJSON("saves//convoy_test.json");
    convoy3.writeJSON("saves//convoy_rewrite.json");
    lok(fequal("saves//convoy_rewrite.json", "saves//convoy_test.json"));
    lok(PHYSFS_exists("saves//convoy_rewrite.json"));
    lok(PHYSFS_exists("saves//convoy_test.json"));
}

void testConvoysortStats() {
    Convoy convoy;
    std::unordered_map<short int, Weapon> weapons;
    convoy.setWeapons(&weapons);
    Inventory_item temp;
    temp.id = ITEM::NAME::WOODEN_SWORD;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::KITCHEN_KNIFE;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::WRATH_SWORD;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::FLEURET;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::DAMAS_SWORD;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::DAMAS_SWORD;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::WOODEN_SWORD;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::WOODEN_SWORD;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::IRON_SWORD;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::STEEL_SWORD;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::DAMAS_SWORD;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::ESPADON;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::EXSANGUE;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::SECUNDUS;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::FAUCHON;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::SABER;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::GALATINE;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::HAUTECLAIRE;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::BROADSWORD;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::MERCIFUL_BLADE;
    convoy.deposit(temp);

    temp.id = ITEM::NAME::DAMAS_LANCE;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::ACHILLES;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::VEL;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::IRON_LANCE;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::TONBOKIRI;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::DAMAS_LANCE;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::WRATH_LANCE;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::WRATH_LANCE;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::TRIDENT;
    convoy.deposit(temp);
    temp.id = ITEM::NAME::SPEAR;
    convoy.deposit(temp);

    SDL_Log("SWORD: Base Convoy Order.");
    convoy.printContents(ITEM::TYPE::SWORD);
    SDL_Log("Sorting swords according to Pmight");
    convoy.sortStats(ITEM::TYPE::SWORD, ITEM::STAT::PMIGHT);
    convoy.printStats(ITEM::TYPE::SWORD, ITEM::STAT::PMIGHT);
    SDL_Log("Sorting swords according to Mmight");
    convoy.sortStats(ITEM::TYPE::SWORD, ITEM::STAT::MMIGHT);
    convoy.printStats(ITEM::TYPE::SWORD, ITEM::STAT::MMIGHT);
    SDL_Log("Sorting swords according to hit");
    convoy.sortStats(ITEM::TYPE::SWORD, ITEM::STAT::HIT);
    convoy.printStats(ITEM::TYPE::SWORD, ITEM::STAT::HIT);
    SDL_Log("Sorting swords according to dodge");
    convoy.sortStats(ITEM::TYPE::SWORD, ITEM::STAT::DODGE);
    convoy.printStats(ITEM::TYPE::SWORD, ITEM::STAT::DODGE);
    SDL_Log("Sorting swords according to crit");
    convoy.sortStats(ITEM::TYPE::SWORD, ITEM::STAT::CRIT);
    convoy.printStats(ITEM::TYPE::SWORD, ITEM::STAT::CRIT);
    SDL_Log("Sorting swords according to favor");
    convoy.sortStats(ITEM::TYPE::SWORD, ITEM::STAT::FAVOR);
    convoy.printStats(ITEM::TYPE::SWORD, ITEM::STAT::FAVOR);
    SDL_Log("Sorting swords according to weight");
    convoy.sortStats(ITEM::TYPE::SWORD, ITEM::STAT::WGT);
    convoy.printStats(ITEM::TYPE::SWORD, ITEM::STAT::WGT);
    SDL_Log("Sorting swords according to uses");
    convoy.sortStats(ITEM::TYPE::SWORD, ITEM::STAT::USES);
    convoy.printStats(ITEM::TYPE::SWORD, ITEM::STAT::USES);
    SDL_Log("Sorting swords according to proficiency");
    convoy.sortStats(ITEM::TYPE::SWORD, ITEM::STAT::PROF);
    convoy.printStats(ITEM::TYPE::SWORD, ITEM::STAT::PROF);
    SDL_Log("Sorting swords according to price");
    convoy.sortStats(ITEM::TYPE::SWORD, ITEM::STAT::PRICE);
    convoy.printStats(ITEM::TYPE::SWORD, ITEM::STAT::PRICE);

    SDL_Log("LANCE: Base Convoy Order.");
    convoy.printContents(ITEM::TYPE::LANCE);
    SDL_Log("Sorting lances according to Pmight");
    convoy.sortStats(ITEM::TYPE::LANCE, ITEM::STAT::PMIGHT);
    convoy.printStats(ITEM::TYPE::LANCE, ITEM::STAT::PMIGHT);
    SDL_Log("Sorting lances according to Mmight");
    convoy.sortStats(ITEM::TYPE::LANCE, ITEM::STAT::MMIGHT);
    convoy.printStats(ITEM::TYPE::LANCE, ITEM::STAT::MMIGHT);
    SDL_Log("Sorting lances according to hit");
    convoy.sortStats(ITEM::TYPE::LANCE, ITEM::STAT::HIT);
    convoy.printStats(ITEM::TYPE::LANCE, ITEM::STAT::HIT);
    SDL_Log("Sorting lances according to dodge");
    convoy.sortStats(ITEM::TYPE::LANCE, ITEM::STAT::DODGE);
    convoy.printStats(ITEM::TYPE::LANCE, ITEM::STAT::DODGE);
    SDL_Log("Sorting lances according to crit");
    convoy.sortStats(ITEM::TYPE::LANCE, ITEM::STAT::CRIT);
    convoy.printStats(ITEM::TYPE::LANCE, ITEM::STAT::CRIT);
    SDL_Log("Sorting lances according to favor");
    convoy.sortStats(ITEM::TYPE::LANCE, ITEM::STAT::FAVOR);
    convoy.printStats(ITEM::TYPE::LANCE, ITEM::STAT::FAVOR);
    SDL_Log("Sorting lances according to weight");
    convoy.sortStats(ITEM::TYPE::LANCE, ITEM::STAT::WGT);
    convoy.printStats(ITEM::TYPE::LANCE, ITEM::STAT::WGT);
    SDL_Log("Sorting lances according to uses");
    convoy.sortStats(ITEM::TYPE::LANCE, ITEM::STAT::USES);
    convoy.printStats(ITEM::TYPE::LANCE, ITEM::STAT::USES);
    SDL_Log("Sorting lances according to proficiency");
    convoy.sortStats(ITEM::TYPE::LANCE, ITEM::STAT::PROF);
    convoy.printStats(ITEM::TYPE::LANCE, ITEM::STAT::PROF);
    SDL_Log("Sorting lances according to minimum range");
    convoy.sortStats(ITEM::TYPE::LANCE, ITEM::STAT::RANGEMIN);
    convoy.printStats(ITEM::TYPE::LANCE, ITEM::STAT::RANGEMIN);
    SDL_Log("Sorting lances according to maximum range");
    convoy.sortStats(ITEM::TYPE::LANCE, ITEM::STAT::RANGEMAX);
    convoy.printStats(ITEM::TYPE::LANCE, ITEM::STAT::RANGEMAX);
    SDL_Log("Sorting lances according to price");
    convoy.sortStats(ITEM::TYPE::LANCE, ITEM::STAT::PRICE);
    convoy.printStats(ITEM::TYPE::LANCE, ITEM::STAT::PRICE);
}

void test_convoy() {
    SDL_Log("test_convoy");
    testConvoyfull();
    testConvoysortStats();
    testConvoyWriteRead();
    testConvoysortused();
}