#include "minctest.h"
#include "convoy.h"

void testConvoyfull() {
    struct Convoy convoy = Convoy_default;
    struct Inventory_item temp = Inventory_item_default;
    struct Weapon temp_weapon = Weapon_default;
    struct Weapons_hash * weapons = NULL;
    hmdefault(weapons, temp_weapon);
    Convoy_Weapons_Set(&convoy, weapons);
    temp.id = ITEM_NAME_KITCHEN_KNIFE;
    Convoy_deposit(&convoy, temp);
    lok(!Convoy_isFull(&convoy));
    for (int i = 0; i < (DEFAULT_CONVOY_SIZE + 2); i++) {
        Convoy_deposit(&convoy, temp);
    }
    lok(Convoy_isFull(&convoy));
    Convoy_withdraw(&convoy, 0, ITEM_TYPE_SWORD);
    lok(!Convoy_isFull(&convoy));
    Convoy_withdraw(&convoy, 1, ITEM_TYPE_SWORD);
    lok(!Convoy_isFull(&convoy));
    temp.id = ITEM_NAME_DAMAS_LANCE;
    Convoy_deposit(&convoy, temp);
    lok(!Convoy_isFull(&convoy));
    Convoy_deposit(&convoy, temp);
    lok(Convoy_isFull(&convoy));
}

void testConvoysortused() {
    struct Convoy convoy = Convoy_default;
    struct Weapon temp_weapon = Weapon_default;
    struct Weapons_hash * weapons = NULL;
    hmdefault(weapons, temp_weapon);
    Convoy_Weapons_Set(&convoy, weapons);
    struct Inventory_item temp;
    temp.id = ITEM_NAME_KITCHEN_KNIFE;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_KITCHEN_KNIFE;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_WRATH_SWORD;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_FLEURET;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_DAMAS_SWORD;
    temp.used = 0;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_DAMAS_SWORD;
    temp.used = 1;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_KITCHEN_KNIFE;
    temp.used = 1;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_KITCHEN_KNIFE;
    temp.used = 2;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_KITCHEN_KNIFE;
    temp.used = 20;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_KITCHEN_KNIFE;
    temp.used = 21;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_KITCHEN_KNIFE;
    temp.used = 10;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_KITCHEN_KNIFE;
    temp.used = 11;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_KITCHEN_KNIFE;
    temp.used = 12;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_KITCHEN_KNIFE;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_IRON_SWORD;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_STEEL_SWORD;
    Convoy_deposit(&convoy, temp);
    Convoy_Contents_Print(&convoy, ITEM_TYPE_SWORD);
    Convoy_Stats_Print(&convoy, ITEM_TYPE_SWORD, ITEM_STAT_USES_LEFT);
    Convoy_Stats_Sort(&convoy, ITEM_TYPE_SWORD, ITEM_STAT_PMIGHT);
    Convoy_Used_Sort(&convoy, ITEM_TYPE_SWORD);
    Convoy_Stats_Print(&convoy, ITEM_TYPE_SWORD, ITEM_STAT_USES_LEFT);
}

void testConvoyWriteRead() {
    struct Convoy convoy = Convoy_default;
    struct Weapon temp_weapon = Weapon_default;
    struct Weapons_hash * weapons = NULL;
    hmdefault(weapons, Weapon_default);
    Convoy_Weapons_Set(&convoy, weapons);
    struct Inventory_item temp = Inventory_item_default;
    temp.id = ITEM_NAME_KITCHEN_KNIFE;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_KITCHEN_KNIFE;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_WRATH_SWORD;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_FLEURET;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_DAMAS_SWORD;
    temp.used = 0;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_DAMAS_SWORD;
    temp.used = 1;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_KITCHEN_KNIFE;
    temp.used = 1;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_KITCHEN_KNIFE;
    temp.used = 2;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_KITCHEN_KNIFE;
    temp.used = 20;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_KITCHEN_KNIFE;
    temp.used = 21;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_KITCHEN_KNIFE;
    temp.used = 10;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_KITCHEN_KNIFE;
    temp.used = 11;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_KITCHEN_KNIFE;
    temp.used = 12;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_KITCHEN_KNIFE;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_IRON_SWORD;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_STEEL_SWORD;
    temp.id = ITEM_NAME_DAMAS_LANCE;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_ACHILLES;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_VEL;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_IRON_LANCE;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_TONBOKIRI;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_DAMAS_LANCE;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_WRATH_LANCE;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_WRATH_LANCE;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_TRIDENT;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_SPEAR;
    Convoy_deposit(&convoy, temp);
    if (PHYSFS_stat("saves", NULL) == 0) {
        PHYSFS_mkdir("saves");
    }
    temp_weapon = Weapon_default;
    writeJSON("saves"PHYSFS_SEPARATOR"convoy_test.json", &convoy, false);
    struct Convoy convoy2 = Convoy_default;
    struct Weapons_hash * weapons2 = NULL;
    hmdefault(weapons2, Weapon_default);
    Convoy_Weapons_Set(&convoy2, weapons2);
    struct Convoy convoy3 = Convoy_default;
    struct Weapons_hash * weapons3 = NULL;
    hmdefault(weapons3, Weapon_default);
    Convoy_Weapons_Set(&convoy3, weapons3);
    readJSON("saves"PHYSFS_SEPARATOR"convoy_test.json", &convoy3);
    writeJSON("saves"PHYSFS_SEPARATOR"convoy_rewrite.json", &convoy3, false);
    lok(fequal("saves"PHYSFS_SEPARATOR"convoy_rewrite.json", "saves"PHYSFS_SEPARATOR"convoy_test.json"));
    lok(PHYSFS_exists("saves"PHYSFS_SEPARATOR"convoy_rewrite.json"));
    lok(PHYSFS_exists("saves"PHYSFS_SEPARATOR"convoy_test.json"));
}

void testConvoysortStats() {
    struct Convoy convoy = Convoy_default;
    struct Weapon temp_weapon = Weapon_default;
    struct Weapons_hash * weapons = NULL;
    hmdefault(weapons, Weapon_default);
    Convoy_Weapons_Set(&convoy, weapons);
    struct Inventory_item temp;
    temp.id = ITEM_NAME_KITCHEN_KNIFE;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_KITCHEN_KNIFE;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_WRATH_SWORD;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_FLEURET;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_DAMAS_SWORD;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_DAMAS_SWORD;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_KITCHEN_KNIFE;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_KITCHEN_KNIFE;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_IRON_SWORD;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_STEEL_SWORD;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_DAMAS_SWORD;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_ESPADON;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_EXSANGUE;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_SECUNDUS;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_FAUCHON;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_SABER;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_GALATINE;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_HAUTECLAIRE;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_BROADSWORD;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_MERCIFUL_BLADE;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_DAMAS_LANCE;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_ACHILLES;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_VEL;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_IRON_LANCE;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_TONBOKIRI;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_DAMAS_LANCE;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_WRATH_LANCE;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_WRATH_LANCE;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_TRIDENT;
    Convoy_deposit(&convoy, temp);
    temp.id = ITEM_NAME_SPEAR;
    Convoy_deposit(&convoy, temp);
    SDL_Log("SWORD: Base Convoy Order.");
    Convoy_Contents_Print(&convoy, ITEM_TYPE_SWORD);
    SDL_Log("Sorting swords according to Pmight");
    Convoy_Stats_Sort(&convoy, ITEM_TYPE_SWORD, ITEM_STAT_PMIGHT);
    Convoy_Stats_Print(&convoy, ITEM_TYPE_SWORD, ITEM_STAT_PMIGHT);
    SDL_Log("Sorting swords according to Mmight");
    Convoy_Stats_Sort(&convoy, ITEM_TYPE_SWORD, ITEM_STAT_MMIGHT);
    Convoy_Stats_Print(&convoy, ITEM_TYPE_SWORD, ITEM_STAT_MMIGHT);
    SDL_Log("Sorting swords according to hit");
    Convoy_Stats_Sort(&convoy, ITEM_TYPE_SWORD, ITEM_STAT_HIT);
    Convoy_Stats_Print(&convoy, ITEM_TYPE_SWORD, ITEM_STAT_HIT);
    SDL_Log("Sorting swords according to dodge");
    Convoy_Stats_Sort(&convoy, ITEM_TYPE_SWORD, ITEM_STAT_DODGE);
    Convoy_Stats_Print(&convoy, ITEM_TYPE_SWORD, ITEM_STAT_DODGE);
    SDL_Log("Sorting swords according to crit");
    Convoy_Stats_Sort(&convoy, ITEM_TYPE_SWORD, ITEM_STAT_CRIT);
    Convoy_Stats_Print(&convoy, ITEM_TYPE_SWORD, ITEM_STAT_CRIT);
    SDL_Log("Sorting swords according to favor");
    Convoy_Stats_Sort(&convoy, ITEM_TYPE_SWORD, ITEM_STAT_FAVOR);
    Convoy_Stats_Print(&convoy, ITEM_TYPE_SWORD, ITEM_STAT_FAVOR);
    SDL_Log("Sorting swords according to weight");
    Convoy_Stats_Sort(&convoy, ITEM_TYPE_SWORD, ITEM_STAT_WGT);
    Convoy_Stats_Print(&convoy, ITEM_TYPE_SWORD, ITEM_STAT_WGT);
    SDL_Log("Sorting swords according to uses");
    Convoy_Stats_Sort(&convoy, ITEM_TYPE_SWORD, ITEM_STAT_USES);
    Convoy_Stats_Print(&convoy, ITEM_TYPE_SWORD, ITEM_STAT_USES);
    SDL_Log("Sorting swords according to proficiency");
    Convoy_Stats_Sort(&convoy, ITEM_TYPE_SWORD, ITEM_STAT_PROF);
    Convoy_Stats_Print(&convoy, ITEM_TYPE_SWORD, ITEM_STAT_PROF);
    SDL_Log("Sorting swords according to price");
    Convoy_Stats_Sort(&convoy, ITEM_TYPE_SWORD, ITEM_STAT_PRICE);
    Convoy_Stats_Print(&convoy, ITEM_TYPE_SWORD, ITEM_STAT_PRICE);
    SDL_Log("LANCE: Base Convoy Order.");
    Convoy_Contents_Print(&convoy, ITEM_TYPE_LANCE);
    SDL_Log("Sorting lances according to Pmight");
    Convoy_Stats_Sort(&convoy, ITEM_TYPE_LANCE, ITEM_STAT_PMIGHT);
    Convoy_Stats_Print(&convoy, ITEM_TYPE_LANCE, ITEM_STAT_PMIGHT);
    SDL_Log("Sorting lances according to Mmight");
    Convoy_Stats_Sort(&convoy, ITEM_TYPE_LANCE, ITEM_STAT_MMIGHT);
    Convoy_Stats_Print(&convoy, ITEM_TYPE_LANCE, ITEM_STAT_MMIGHT);
    SDL_Log("Sorting lances according to hit");
    Convoy_Stats_Sort(&convoy, ITEM_TYPE_LANCE, ITEM_STAT_HIT);
    Convoy_Stats_Print(&convoy, ITEM_TYPE_LANCE, ITEM_STAT_HIT);
    SDL_Log("Sorting lances according to dodge");
    Convoy_Stats_Sort(&convoy, ITEM_TYPE_LANCE, ITEM_STAT_DODGE);
    Convoy_Stats_Print(&convoy, ITEM_TYPE_LANCE, ITEM_STAT_DODGE);
    SDL_Log("Sorting lances according to crit");
    Convoy_Stats_Sort(&convoy, ITEM_TYPE_LANCE, ITEM_STAT_CRIT);
    Convoy_Stats_Print(&convoy, ITEM_TYPE_LANCE, ITEM_STAT_CRIT);
    SDL_Log("Sorting lances according to favor");
    Convoy_Stats_Sort(&convoy, ITEM_TYPE_LANCE, ITEM_STAT_FAVOR);
    Convoy_Stats_Print(&convoy, ITEM_TYPE_LANCE, ITEM_STAT_FAVOR);
    SDL_Log("Sorting lances according to weight");
    Convoy_Stats_Sort(&convoy, ITEM_TYPE_LANCE, ITEM_STAT_WGT);
    Convoy_Stats_Print(&convoy, ITEM_TYPE_LANCE, ITEM_STAT_WGT);
    SDL_Log("Sorting lances according to uses");
    Convoy_Stats_Sort(&convoy, ITEM_TYPE_LANCE, ITEM_STAT_USES);
    Convoy_Stats_Print(&convoy, ITEM_TYPE_LANCE, ITEM_STAT_USES);
    SDL_Log("Sorting lances according to proficiency");
    Convoy_Stats_Sort(&convoy, ITEM_TYPE_LANCE, ITEM_STAT_PROF);
    Convoy_Stats_Print(&convoy, ITEM_TYPE_LANCE, ITEM_STAT_PROF);
    SDL_Log("Sorting lances according to minimum range");
    Convoy_Stats_Sort(&convoy, ITEM_TYPE_LANCE, ITEM_STAT_RANGEMIN);
    Convoy_Stats_Print(&convoy, ITEM_TYPE_LANCE, ITEM_STAT_RANGEMIN);
    SDL_Log("Sorting lances according to maximum range");
    Convoy_Stats_Sort(&convoy, ITEM_TYPE_LANCE, ITEM_STAT_RANGEMAX);
    Convoy_Stats_Print(&convoy, ITEM_TYPE_LANCE, ITEM_STAT_RANGEMAX);
    SDL_Log("Sorting lances according to price");
    Convoy_Stats_Sort(&convoy, ITEM_TYPE_LANCE, ITEM_STAT_PRICE);
    Convoy_Stats_Print(&convoy, ITEM_TYPE_LANCE, ITEM_STAT_PRICE);
}

void test_convoy() {
    SDL_Log("test_convoy");
    testConvoyfull();
    testConvoysortStats();
    testConvoyWriteRead();
    testConvoysortused();
}