REGISTER_ENUM(RIGHT)
REGISTER_ENUM(UP)
REGISTER_ENUM(LEFT)
REGISTER_ENUM(DOWN)
REGISTER_ENUM(ACCEPT)           /* GC A */
REGISTER_ENUM(CANCEL)           /* GC B */
REGISTER_ENUM(MINIMAP)
REGISTER_ENUM(MENURIGHT)        /* GC R */
REGISTER_ENUM(MENULEFT)         /* GC L */
REGISTER_ENUM(PAUSE)            /* GC START */
REGISTER_ENUM(STATS)
REGISTER_ENUM(OPTIONS)
REGISTER_ENUM(FASTER)
REGISTER_ENUM(GLOBALRANGE)