REGISTER_ENUM(1,        map_test.json,             NULL)
REGISTER_ENUM(2,        map_test.json,             NULL)
REGISTER_ENUM(3,        map_test.json,             NULL)
REGISTER_ENUM(4,        map_test.json,             NULL)
REGISTER_ENUM(5,        map_test.json,             NULL)
REGISTER_ENUM(6,        map_test.json,             NULL)
REGISTER_ENUM(7,        map_test.json,             NULL)
REGISTER_ENUM(PROLOGUE, map_test.json,             NULL)
REGISTER_ENUM(EPILOGUE, map_test.json,             NULL)
REGISTER_ENUM(TEST,     map_test.json,             NULL)
REGISTER_ENUM(TEST_V6,  Map_Test_V6_stacked.json,  NULL)
REGISTER_ENUM(TEST_V7,  Map_Test_V7_stacked.json,  NULL)
REGISTER_ENUM(TEST_V8,  Map_Test_V8_stacked.json,  NULL)
//                  ID,      map name,      gaiden name