REGISTER_ENUM(Combat,           Cmbt)
REGISTER_ENUM(Scene_Talk,       ScnTlk)
REGISTER_ENUM(Scene_FMV,        ScnFMV)
REGISTER_ENUM(Gameplay_Map,     GmpMap)
REGISTER_ENUM(Gameplay_Camp,    GmpCamp)
REGISTER_ENUM(Preparation,      Prep)
REGISTER_ENUM(Title_Screen,     TtScrn)
REGISTER_ENUM(Animation,        Anim)