//uint6_t -> 65,535 MAX
REGISTER_ENUM(SWORD_START,                     0)
REGISTER_ENUM(WOODEN_SWORD,                    1)
REGISTER_ENUM(KITCHEN_KNIFE,                   2) // maybe should be sword and offhand?
REGISTER_ENUM(WRATH_SWORD,                     3)
REGISTER_ENUM(FLEURET,                         4)
REGISTER_ENUM(RAPIERE,                         5)
REGISTER_ENUM(GLAIVE,                          6)
REGISTER_ENUM(SABER,                           7)
REGISTER_ENUM(FAUCHON,                         8)
REGISTER_ENUM(IRON_SWORD,                      9)
REGISTER_ENUM(STEEL_SWORD,                    10)
REGISTER_ENUM(DAMAS_SWORD,                    11)
REGISTER_ENUM(MERCIFUL_BLADE,                 12)
REGISTER_ENUM(BROADSWORD,                     13)
REGISTER_ENUM(ESPADON,                        14)
REGISTER_ENUM(OODACHI,                        15)
REGISTER_ENUM(UCHIGATANA,                     16)
REGISTER_ENUM(EXSANGUE,                       17)
REGISTER_ENUM(HAUTECLAIRE,                    18)
REGISTER_ENUM(SECUNDUS,                       19)
REGISTER_ENUM(EXCALIBUR,                      20)
REGISTER_ENUM(GALATINE,                       21)
REGISTER_ENUM(RAIJINTOU,                      22)
REGISTER_ENUM(FUUJINTOU,                      23)
REGISTER_ENUM(HONJOU_MASAMUNE,                24)
REGISTER_ENUM(RAW_IRON_SLAB,                  25)
REGISTER_ENUM(KIRITO,                         26)
REGISTER_ENUM(KILLY,                          27)
REGISTER_ENUM(KAJINTOU,                       28)
REGISTER_ENUM(CLAYMORE,                       29)
REGISTER_ENUM(GLADIUS,                        30)
REGISTER_ENUM(FALX,                           31) /* 2H */
REGISTER_ENUM(SWORD_END,                      32)

REGISTER_ENUM(LANCE_START,                   100)
REGISTER_ENUM(FIGHTING_STICK,                101)
REGISTER_ENUM(IRON_LANCE,                    102)
REGISTER_ENUM(WRATH_LANCE,                   103)
REGISTER_ENUM(STEEL_LANCE,                   104)
REGISTER_ENUM(DAMAS_LANCE,                   105)
REGISTER_ENUM(HEAVY_SPEAR,                   106) /* square spike Lance? bodkin Lance? */
REGISTER_ENUM(TRIDENT,                       107)
REGISTER_ENUM(MERCIFUL_LANCE,                108)
REGISTER_ENUM(JAVELIN,                       109)
REGISTER_ENUM(PILUM,                         110)
REGISTER_ENUM(SPEAR,                         111)
REGISTER_ENUM(VEL,                           112)
REGISTER_ENUM(GUNGNIR,                       113)
REGISTER_ENUM(ACHILLES,                      114)
REGISTER_ENUM(TONBOKIRI,                     115)
REGISTER_ENUM(PITCHFORK,                     116)
REGISTER_ENUM(LANCE_END,                     117)

REGISTER_ENUM(AXE_START,                     200)
REGISTER_ENUM(IRON_AXE,                      201)
REGISTER_ENUM(STEEL_AXE,                     202)
REGISTER_ENUM(DAMAS_AXE,                     203)
REGISTER_ENUM(THROWING_AXE,                  204)
REGISTER_ENUM(TOMAHAWK,                      205)
REGISTER_ENUM(PICK_AXE,                      206)
REGISTER_ENUM(HOE,                           207)
REGISTER_ENUM(CLUB,                          208)
REGISTER_ENUM(HAMMER,                        209)
REGISTER_ENUM(WAR_PICK,                      210)
REGISTER_ENUM(BATTLEAXE,                     211)
REGISTER_ENUM(VIDYU,                         212)
REGISTER_ENUM(HEPHAESTUS,                    213)
REGISTER_ENUM(WRATH_AXE,                     214)
REGISTER_ENUM(WOOD_AXE,                      215)
REGISTER_ENUM(SHOVEL,                        216)
REGISTER_ENUM(AXE_END,                       217)

REGISTER_ENUM(BOW_START,                     300)
REGISTER_ENUM(REPEATABLE_CROSSBOW,           301)
REGISTER_ENUM(CROSSBOW,                      302)
REGISTER_ENUM(SHORT_BOW,                     303)
REGISTER_ENUM(LONG_BOW,                      304)
REGISTER_ENUM(COMPOSITE_BOW,                 305)
REGISTER_ENUM(RECURVE_CROSSBOW,              306)
REGISTER_ENUM(RECURVE_BOW,                   307)
REGISTER_ENUM(APOLLO,                        308)
REGISTER_ENUM(ARTEMIS,                       309)
REGISTER_ENUM(PINAKA,                        310)
REGISTER_ENUM(ADAPTED_CROSSBOW,              311)
REGISTER_ENUM(TRAINING_LONG_BOW,             312)
REGISTER_ENUM(BOW_END,                       313)

REGISTER_ENUM(SHIELD_START,                  400)
REGISTER_ENUM(ADAPTED_SHIELD,                401)
REGISTER_ENUM(WOODEN_SHIELD,                 402)
REGISTER_ENUM(CLOAK,                         403)
REGISTER_ENUM(LEATHER_SHIELD,                404)
REGISTER_ENUM(KITE_SHIELD,                   405)
REGISTER_ENUM(IRON_BUCKLER,                  406)
REGISTER_ENUM(STEEL_BUCKLER,                 407)
REGISTER_ENUM(SPIKED_BUCKLER,                408)
REGISTER_ENUM(SCUTUM,                        409)
REGISTER_ENUM(MASTER_SHIELD,                 410)
REGISTER_ENUM(GODDESS_HAND,                  411)
REGISTER_ENUM(ANCILE,                        412)
REGISTER_ENUM(BOULDER,                       413)
REGISTER_ENUM(OBSIDIAN_SLAB,                 414)
REGISTER_ENUM(MARBLE_PLATE_SHIELD,           415)
REGISTER_ENUM(DIVINE_PROTECTOR,              416)
REGISTER_ENUM(POT_LID,                       417)
REGISTER_ENUM(SHIELD_END,                    418)

REGISTER_ENUM(OFFHAND_START,                 500)
REGISTER_ENUM(SHIELD_HOOK,                   501)
REGISTER_ENUM(RETRACTABLE_WRISTBLADE,        502)
REGISTER_ENUM(MAIN_GAUCHE,                   503)
REGISTER_ENUM(SWORDBREAKER,                  504)
REGISTER_ENUM(TRIDENT_DAGGER,                505)
REGISTER_ENUM(TANTOU,                        506)
REGISTER_ENUM(KODACHI,                       507) /* too similar to tantou and wakizashi */
REGISTER_ENUM(DAGUE,                         508) /* too similar to main gauche */
REGISTER_ENUM(WAKIZASHI,                     509)
REGISTER_ENUM(BRAQUEMARD,                    510)
REGISTER_ENUM(MISERICORDE,                   511)
REGISTER_ENUM(CARNWENNAN,                    512)
REGISTER_ENUM(FLINTLOCK,                     513)
REGISTER_ENUM(CIBO,                          514)
REGISTER_ENUM(WRISTBLADE,                    515)
REGISTER_ENUM(SAI,                           516)
REGISTER_ENUM(PUGIO,                         517)
REGISTER_ENUM(OFFHAND_END,                   518)

REGISTER_ENUM(MAGIC_START,                   600)
REGISTER_ENUM(ELEMENTAL_START,               600)
REGISTER_ENUM(ICICLE,                        601)
REGISTER_ENUM(VOLCANO,                       602)
REGISTER_ENUM(WIND_SPEAR,                    603)
REGISTER_ENUM(EMBER,                         604)
REGISTER_ENUM(TSUNAMI,                       605)
REGISTER_ENUM(GODS_FORGE_FIRE,               606)
REGISTER_ENUM(FEANOR,                        607)
REGISTER_ENUM(BALL_LIGHTNING,                608)
REGISTER_ENUM(ELEMENTAL_END,                 609)
REGISTER_ENUM(MAGIC_END,                     609)

REGISTER_ENUM(DEMONIC_START,                 700)
REGISTER_ENUM(VOIDD,                         700)
REGISTER_ENUM(NETHER,                        701)
REGISTER_ENUM(DOWNFALL,                      702)
REGISTER_ENUM(CONSUME,                       703)
REGISTER_ENUM(PUTRIFY,                       704)
REGISTER_ENUM(FATALIS,                       705)
REGISTER_ENUM(GLAURUNG,                      706)
REGISTER_ENUM(MORGOTH,                       707)
REGISTER_ENUM(GOTHMOG,                       708)
REGISTER_ENUM(DEMONIC_END,                   709)

REGISTER_ENUM(ANGELIC_START,                 800)
REGISTER_ENUM(BLINDING_CLARITY,              801)
REGISTER_ENUM(DAYBREAK,                      802)
REGISTER_ENUM(DUSK,                          803)
REGISTER_ENUM(TWIN_HELIX,                    804)
REGISTER_ENUM(SILVERLIGHT_SPEAR,             805)
REGISTER_ENUM(FINGOLFIN,                     806)
REGISTER_ENUM(MITHRANDIR,                    807)
REGISTER_ENUM(MOONLIGHT,                     808)
REGISTER_ENUM(ANGELIC_END,                   809)

REGISTER_ENUM(STAFF_START,                   900)
REGISTER_ENUM(HEAL,                          901) // Heal a little
REGISTER_ENUM(RENEW,                         902) // Heal more
REGISTER_ENUM(WISH,                          903) // Heal all hp
REGISTER_ENUM(PRAY,                          904) // Heal AOE
REGISTER_ENUM(CADUCEUS,                      905)
REGISTER_ENUM(MAGIC_SHIELD,                  906)
REGISTER_ENUM(CURE,                          907)
REGISTER_ENUM(PULL,                          908)
REGISTER_ENUM(PUSH,                          909)
REGISTER_ENUM(REMEDY,                        910) // Cures status
REGISTER_ENUM(STAFF_END,                     911)

REGISTER_ENUM(CLAW_START,                   1000)
REGISTER_ENUM(CLAW,                         1001)
REGISTER_ENUM(METAL_CLAW,                   1002)
REGISTER_ENUM(POISON_CLAW,                  1003)
REGISTER_ENUM(RADIANT_CLAW,                 1004)
REGISTER_ENUM(BLOODY_CLAW,                  1005)
REGISTER_ENUM(CLAW_END,                     1006)

REGISTER_ENUM(ITEM_START,                   1100)
REGISTER_ENUM(PANACEA,                      1101) // cures status ailments.
REGISTER_ENUM(HEALING_POTION,               1102) // heals for 100%.
REGISTER_ENUM(TELPERION_EXTRACT,            1103) // heals for 50% + cures ailments
REGISTER_ENUM(LAURELIN_EXTRACT,             1104) // heals for 50% + divine Shield
REGISTER_ENUM(CROSS,
              1105) // 10% healing everyturn if in hand + everyone in range?
REGISTER_ENUM(IMPERIAL_EDICT,               1106) // Promote
REGISTER_ENUM(PURE_MAGIC,                   1107) // Same as pure_magic
REGISTER_ENUM(ELEMENTAL_DUST,               1108) // Same as pure_magic
REGISTER_ENUM(SALVE,                        1109) // heals for 50%.
REGISTER_ENUM(COARSE_WHETSTONE,             1110) // Repairs weapons
REGISTER_ENUM(FINE_WHETSTONE,               1111) // Repairs weapons
REGISTER_ENUM(DOUBLE_SIDED_WHETSTONE,       1112) // Repairs weapons
REGISTER_ENUM(REPAIR_KIT,                   1113) // Repairs bows and shields
REGISTER_ENUM(MAGICAL_REPAIR_KIT,           1114) // Repairs bows and shields
REGISTER_ENUM(LUMBER,                       1115) // Build siege weapons
REGISTER_ENUM(FIRST_S_RECOGNITION,          1116) // Teharon unique amulet
REGISTER_ENUM(ITEM_END,                     1117)

REGISTER_ENUM(TRINKET_START,                1200)
REGISTER_ENUM(SHRUNKEN_HEAD,                1201)   /* -> human skull */
REGISTER_ENUM(CRYSTAL,                      1202)
REGISTER_ENUM(GLASS_ORB,                    1203)
REGISTER_ENUM(HUMAN_FEMUR,                  1204)
REGISTER_ENUM(VOID_FRAGMENT,                1205)
REGISTER_ENUM(DEMON_FANG,                   1206)
REGISTER_ENUM(ANGEL_FEATHER,                1207)
REGISTER_ENUM(ANGEL_HAIR,                   1208)
REGISTER_ENUM(VIAL_OF_LIGHT,                1209)
REGISTER_ENUM(MAIDENS_HANDKERCHIEF,         1210)
REGISTER_ENUM(WAR_HORN,                     1211)
REGISTER_ENUM(TRINKET_END,                  1212)

REGISTER_ENUM(STANDARD_START,               1300)
REGISTER_ENUM(IMPERIAL_STANDARD,            1301)
REGISTER_ENUM(EAGLE_STANDARD,               1302)
REGISTER_ENUM(EMPEROR_STANDARD,             1303)
REGISTER_ENUM(LABARUM,                      1304)
REGISTER_ENUM(STANDARD_END,                 1305)

REGISTER_ENUM(SLING_START,                  1400)
REGISTER_ENUM(GERMANIC_SLING,               1401)
REGISTER_ENUM(SLING_END,                    1402)

REGISTER_ENUM(DOUBLE_SWORDAXE_START,        1500)
REGISTER_ENUM(DOUBLE_SWORDAXE_END,          1501)

REGISTER_ENUM(DOUBLE_LANCEAXE_START,        1600)
REGISTER_ENUM(HALBERD,                      1601)
REGISTER_ENUM(DOUBLE_LANCEAXE_END,          1602)

REGISTER_ENUM(DOUBLE_SWORDOFFHAND_START,    1700)
REGISTER_ENUM(DOUBLE_SWORDOFFHAND_END,      1701)

REGISTER_ENUM(DOUBLE_SWORDLANCE_START,      1800)
REGISTER_ENUM(DOUBLE_SWORDLANCE_END,        1801)

REGISTER_ENUM(BROKEN,                       2001)

REGISTER_ENUM(GBE,                         32767)

REGISTER_ENUM(BOOK_START,                   5000)
REGISTER_ENUM(BOOKBASICS,                   5001)
REGISTER_ENUM(BOOKELEMENTAL,                5002)
REGISTER_ENUM(BOOKMATHEMAGICS,              5003)
REGISTER_ENUM(BOOKLOVE,                     5004)
REGISTER_ENUM(BOOKGROWTHS,                  5005)
REGISTER_ENUM(BOOKPOSSESSION,               5006)
REGISTER_ENUM(BOOKWEAPONS,                  5007)
REGISTER_ENUM(BOOKHOROLOGION,               5008)
REGISTER_ENUM(BOOK_END,                     5009)
