REGISTER_ENUM(SWORD)
REGISTER_ENUM(LANCE)
REGISTER_ENUM(AXE)
REGISTER_ENUM(BOW)
REGISTER_ENUM(SHIELD)
REGISTER_ENUM(OFFHAND)
REGISTER_ENUM(ELEMENTAL)
REGISTER_ENUM(DEMONIC)
REGISTER_ENUM(ANGELIC)
REGISTER_ENUM(STAFF)
REGISTER_ENUM(CLAW)
REGISTER_ENUM(ITEM)
REGISTER_ENUM(TRINKET)
REGISTER_ENUM(BOOK)
REGISTER_ENUM(DOUBLE_SWORDAXE)     /* MACE          */
REGISTER_ENUM(DOUBLE_LANCEAXE)     /* HALBERD       */
REGISTER_ENUM(DOUBLE_SWORDOFFHAND) /* kitchen knife */
REGISTER_ENUM(DOUBLE_SWORDLANCE)   /* ranseur, naginata */
REGISTER_ENUM(BROKEN)
