REGISTER_ENUM(HORSE)
REGISTER_ENUM(SALAMANDER)
REGISTER_ENUM(PEGASUS)
REGISTER_ENUM(EAGLE)
REGISTER_ENUM(GOOSE)
REGISTER_ENUM(BEAVER)
REGISTER_ENUM(TYPE_END)
REGISTER_ENUM(HORSIE)   /* First horse */
REGISTER_ENUM(GOITEIA)  /* Lucrece's pegasus, Charm in greek */
REGISTER_ENUM(NIBAL)    /* Hamilcar's poison salamander */
REGISTER_ENUM(RAIA)     /* ? */
REGISTER_ENUM(MANWE)    /* The only eagle */
REGISTER_ENUM(DIVINE)   /* ? */
