// Mount Types
REGISTER_ENUM(HORSE)
REGISTER_ENUM(SALAMANDER)
REGISTER_ENUM(PEGASUS)
REGISTER_ENUM(EAGLE)
REGISTER_ENUM(GOOSE)
REGISTER_ENUM(BEAVER)
// Unique mounts
REGISTER_ENUM(HORSIE)
REGISTER_ENUM(GOITEIA)  /* Lucrece's pegasus, Charm in greek */
REGISTER_ENUM(NIBAL)
REGISTER_ENUM(RAIA)
REGISTER_ENUM(MANWE)
REGISTER_ENUM(DIVINE)
