REGISTER_ENUM(TYPE_HORSE)
REGISTER_ENUM(TYPE_SALAMANDER)
REGISTER_ENUM(TYPE_PEGASUS)
REGISTER_ENUM(TYPE_EAGLE)
REGISTER_ENUM(TYPE_GOOSE)
REGISTER_ENUM(TYPE_BEAVER)
REGISTER_ENUM(TYPE_END)
REGISTER_ENUM(HORSIE)   /* First horse */
REGISTER_ENUM(GOITEIA)  /* Lucrece's pegasus, Charm in greek */
REGISTER_ENUM(NIBAL)    /* Hamilcar's poison salamander */
REGISTER_ENUM(RAIA)     /* ? */
REGISTER_ENUM(MANWE)    /* The only eagle */
REGISTER_ENUM(DIVINE)   /* ? */
