REGISTER_ENUM(SDL_MOUSEMOTION)
REGISTER_ENUM(SDL_AUDIODEVICEADDED)
REGISTER_ENUM(SDL_AUDIODEVICEREMOVED)
REGISTER_ENUM(SDL_CONTROLLERDEVICEADDED)
REGISTER_ENUM(SDL_CONTROLLERDEVICEREMOVED)
REGISTER_ENUM(SDL_KEYDOWN) //This event REPEATS every frame pressed.
REGISTER_ENUM(SDL_CONTROLLERBUTTONDOWN) //This event DOES NOT repeat 