REGISTER_ENUM(SDL_MOUSEMOTION)
REGISTER_ENUM(SDL_AUDIODEVICEADDED)
REGISTER_ENUM(SDL_AUDIODEVICEREMOVED)
REGISTER_ENUM(SDL_CONTROLLERDEVICEADDED)
REGISTER_ENUM(SDL_JOYDEVICEADDED)
REGISTER_ENUM(SDL_JOYDEVICEREMOVED)
REGISTER_ENUM(SDL_CONTROLLERDEVICEREMOVED)
REGISTER_ENUM(SDL_KEYDOWN)                  /* REPEATS every frame pressed         */
REGISTER_ENUM(SDL_CONTROLLERBUTTONDOWN)     /* DOES NOT repeat every frame pressed */