REGISTER_ENUM(POISONED)     /* every turn 1%-5% hp loss Urand */
REGISTER_ENUM(STONE)        /* Permanent Cannot act */
REGISTER_ENUM(ROOTED)       /* Cannot move or be moved */
REGISTER_ENUM(STUNNED)      /* Cannot act */
REGISTER_ENUM(SEDUCED)      /* Move in directino of seducer */
REGISTER_ENUM(SLOWED)       /* move/2*/
REGISTER_ENUM(TERROR)       /* RUN AWAY */
REGISTER_ENUM(BERSERK)      /* ATTACKS FRIENDLIES */
REGISTER_ENUM(STASIS)       /* CANNOT BE INTERACTED WITH. CAN PASS THROUGH */
REGISTER_ENUM(SILENCE)      /* NO MAGIC */
REGISTER_ENUM(AGONY)        /* CLOSE TO DEATH */
REGISTER_ENUM(UNCONSCIOUS)  /* CANNOT MOVE, CANNOT ACT */