REGISTER_ENUM(ITEMS,            Item)       /* sGmpMap ssAny */
REGISTER_ENUM(TALK,             Talk)       /* sGmpMap ssAny */
REGISTER_ENUM(STAFF,            Staff)      /* sGmpMap ssAny */
REGISTER_ENUM(DANCE,            Dance)      /* sGmpMap ssAny */
REGISTER_ENUM(RESCUE,           Rescue)     /* sGmpMap ssAny */
REGISTER_ENUM(SEIZE,            Seize)      /* sGmpMap ssAny */
REGISTER_ENUM(ESCAPE,           Escape)     /* sGmpMap ssAny */
REGISTER_ENUM(ATTACK,           Atk)        /* sGmpMap ssAny */
REGISTER_ENUM(VILLAGE,          Vill)       /* sGmpMap ssAny */
REGISTER_ENUM(TRADE,            Trade)      /* sGmpMap ssAny */
REGISTER_ENUM(MAP,              Map)        /* Unused? */
REGISTER_ENUM(WAIT,             Wait)       /* sGmpMap ssAny */
REGISTER_ENUM(OPEN,             Open)       /* sGmpMap ssAny */
REGISTER_ENUM(QUIT,             QuiT)       /* sTtlScrn ssAny */
REGISTER_ENUM(END_TURN,         EndT)       /* sGmpMap ssAny */
REGISTER_ENUM(UNITS,            Unit)       /* sGmpMap ssAny */
REGISTER_ENUM(CONVOY,           Cnvy)       /* sGmpMap ssAny */
REGISTER_ENUM(GLOBAL_RANGE,     GlbRng)     /* sGmpMap ssAny */
REGISTER_ENUM(NEW_GAME,         NewGame)    /* sTtlScrn ssAny */
REGISTER_ENUM(LOAD,             Load)       /* sTtlScrn ssAny */
REGISTER_ENUM(ERASE,            Erase)      /* sTtlScrn ssAny */
REGISTER_ENUM(COPY,             Copy)       /* sTtlScrn ssAny */
REGISTER_ENUM(SETTINGS,         Stts)       /* sAny, ssAny */
REGISTER_ENUM(EXTRAS,           Ext)        /* sTtlScrn ssAny */
REGISTER_ENUM(DEBUG_MAP,        DbgMap)     /* sTtlScrn ssAny */
REGISTER_ENUM(DROP,             Drop)       /* sAny ssAny */
REGISTER_ENUM(EQUIP,            Equip)      /* sAny ssAny */
REGISTER_ENUM(EQUIP_LEFT,       EquipL)     /* sAny ssAny */
REGISTER_ENUM(EQUIP_RIGHT,      EquipR)     /* sAny ssAny */
REGISTER_ENUM(EQUIP_TWOHAND,    Equip2H)    /* sAny ssAny */
REGISTER_ENUM(USE,              Use)        /* sAny ssAny */
