#ifndef SETTINGS_H
#define SETTINGS_H

#include "types.h"
#include "debug.h"
#include "structs.h"
#include "enums.h"
#include "SDL2/SDL.h"
#include "SDL2/SDL_mixer.h"

/* --- Enums --- */
#define SOTA_BRIGHTNESS_MAX 1.0f
#define SOTA_BRIGHTNESS_MIN 0.0f

enum PLAYER_SETTINGS {
    SOTA_SETTINGS_NULL              = -1,
    SOTA_SETTINGS_ANIMATION         =  0,
    SOTA_SETTINGS_TEXT_SPEED        =  1,
    SOTA_SETTINGS_AUTOCURSOR        =  2,
    SOTA_SETTINGS_AUTOEND_TURNS     =  3,
    SOTA_SETTINGS_VOLUME_MUSIC      =  4,
    SOTA_SETTINGS_VOLUME_SOUNDFX    =  5,
    SOTA_SETTINGS_BRIGHTNESS        =  6,
    SOTA_SETTINGS_NUM,
};

enum ANIMATION_SETTINGS {
    ANIMATION_SETTINGS_NULL         = -1,
    ANIMATION_SETTINGS_ON           =  0,
    ANIMATION_SETTINGS_FRIENDLY     =  1,
    ANIMATION_SETTINGS_ENEMY        =  2,
    ANIMATION_SETTINGS_OFF          =  3,
    ANIMATION_SETTINGS_NUM,
};

enum TEXT_SPEED_SETTINGS {
    TEXT_SPEED_SETTINGS_NULL        = -1,
    TEXT_SPEED_SETTINGS_SLOW        =  0,
    TEXT_SPEED_SETTINGS_MID         =  1,
    TEXT_SPEED_SETTINGS_FAST        =  2,
    TEXT_SPEED_SETTINGS_MAX         =  3,
    TEXT_SPEED_SETTINGS_NUM,
};

enum AUTOCURSOR_SETTINGS {
    AUTOCURSOR_SETTINGS_NULL        = -1,
    AUTOCURSOR_SETTINGS_OFF         =  0,
    AUTOCURSOR_SETTINGS_ON          =  1,
};

enum AUTOEND_TURNS_SETTINGS {
    AUTOEND_TURNS_SETTINGS_NULL     = -1,
    AUTOEND_TURNS_SETTINGS_OFF      =  0,
    AUTOEND_TURNS_SETTINGS_ON       =  1,
};

#endif /* SETTINGS_H */
