#include "datamaker.cpp"

void baseWeapons() {
    SDL_Log("Writing all base weapons to xml.");
    Weapon temp_wpn;
    Weapon_stats temp_wpn_stats;
    // Pmight, Mmight, hit, dodge, crit, favor, wgt, uses, wpnlvl, range, hand, dmg_type, price
    temp_wpn_stats = {3, 0, 80, 0, 0, 0, 3, 30, 2, {1,1}, {1,2}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::SWORD, temp_wpn_stats, ITEM::NAME::WOODEN_SWORD);
    temp_wpn.setDescription("Practice sword, made of wood. It's crushing blows are still deadly.");
    all_weapons[ITEM::NAME::WOODEN_SWORD] = temp_wpn;
    temp_wpn_stats = {1, 0, 25, 0, 0, 0, 2, 10, 1, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::SWORD, temp_wpn_stats, ITEM::NAME::KITCHEN_KNIFE);
    temp_wpn.setDescription("The poor, desperate swordman's dagger.");
    all_weapons[ITEM::NAME::KITCHEN_KNIFE] = temp_wpn;
    temp_wpn_stats = {7, 0, 70, 0, 25, 0, 7, 30, 9, {1,1}, {1,2}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::SWORD, temp_wpn_stats, ITEM::NAME::WRATH_SWORD);
    temp_wpn.setDescription("Increases critical hit chance.");
    all_weapons[ITEM::NAME::WRATH_SWORD] = temp_wpn;
    temp_wpn_stats = {4, 0, 90, 0, 0, 0, 4, 20, 6, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::SWORD, temp_wpn_stats, ITEM::NAME::FLEURET);
    temp_wpn.setEffective(UNIT::TYPE::ARMOR);
    temp_wpn.setDescription("Simple and light thrust swords. Effective against armor. Usually used with off-hand parry daggers.");
    all_weapons[ITEM::NAME::FLEURET] = temp_wpn;
    temp_wpn_stats = {8, 0, 85, 5, 0, 0, 5, 25, 8, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::SWORD, temp_wpn_stats, ITEM::NAME::RAPIERE);
    temp_wpn.setEffective(UNIT::TYPE::ARMOR);
    temp_wpn.setDescription("Strong thrust swords. Effective against armor. Usually used with off-hand parry daggers.");
    all_weapons[ITEM::NAME::RAPIERE] = temp_wpn;
    temp_wpn_stats = {5, 0, 55, 0, 0, 0, 7, 30, 3, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::SWORD, temp_wpn_stats, ITEM::NAME::GLAIVE);
    temp_wpn.setDescription("Old-world style short sword.");
    all_weapons[ITEM::NAME::GLAIVE] = temp_wpn;
    temp_wpn_stats = {7, 0, 60, 10, 0, 0, 6, 33, 8, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::SWORD, temp_wpn_stats, ITEM::NAME::SABER);
    temp_wpn.setDescription("Curved sword made for slashing.");
    all_weapons[ITEM::NAME::SABER] = temp_wpn;
    temp_wpn_stats = {8, 0, 60, 15, 0, 0, 8, 27, 10, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::SWORD, temp_wpn_stats, ITEM::NAME::FAUCHON);
    temp_wpn.setDescription("Curved sword made for slashing.");
    all_weapons[ITEM::NAME::FAUCHON] = temp_wpn;
    temp_wpn_stats = {6, 0, 70, 0, 0, 0, 6, 45, 6, {1,1}, {1,2}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::SWORD, temp_wpn_stats, ITEM::NAME::IRON_SWORD);
    temp_wpn.setDescription("Simple straight sword made of iron. Cheap and reliable.");
    all_weapons[ITEM::NAME::IRON_SWORD] = temp_wpn;
    temp_wpn_stats = {9, 0, 60, 0, 0, 0, 9, 30, 10, {1,1}, {1,2}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::SWORD, temp_wpn_stats, ITEM::NAME::STEEL_SWORD);
    temp_wpn.setDescription("Simple straight sword made of steel. Strong and durable.");
    all_weapons[ITEM::NAME::STEEL_SWORD] = temp_wpn;
    temp_wpn_stats = {13, 0, 65, 0, 0, 0, 10, 25, 12, {1,1}, {1,2}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::SWORD, temp_wpn_stats, ITEM::NAME::DAMAS_SWORD);
    temp_wpn.setDescription("Simple straight sword made of damascus steel. Beautifully rippled, deadly and expensive.");
    all_weapons[ITEM::NAME::DAMAS_SWORD] = temp_wpn;
    temp_wpn_stats = {4, 0, 70, 0, 0, 10, 6, 30, 9, {1,1}, {1,2}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::SWORD, temp_wpn_stats, ITEM::NAME::MERCIFUL_BLADE);
    temp_wpn.setEffect(ITEM::EFFECT::SPARE);
    temp_wpn.setDescription("Infused with the life-giving tears of the goddess. Cannot reduce enemy HP below 1.");
    all_weapons[ITEM::NAME::MERCIFUL_BLADE] = temp_wpn;
    temp_wpn_stats = {10, 0, 40, 0, 0, 0, 10, 25, 6, {1,1}, {1,2}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::SWORD, temp_wpn_stats, ITEM::NAME::BROADSWORD);
    temp_wpn.setDescription("Blade of notable girth. Heavy and strong.");
    temp_wpn_stats = {12, 0, 40, 0, 0, 0, 13, 20, 7, {1,1}, {1,2}, 0, 1000, 0};
    all_weapons[ITEM::NAME::BROADSWORD] = temp_wpn;
    temp_wpn = Weapon(ITEM::TYPE::SWORD, temp_wpn_stats, ITEM::NAME::ESPADON);
    temp_wpn.setDescription("Blade of considerable girth and length. Heavier and stronger.");
    all_weapons[ITEM::NAME::ESPADON] = temp_wpn;
    temp_wpn_stats = {9, 0, 60, 10, 5, 0, 8, 25, 10, {1,1}, {1,2}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::SWORD, temp_wpn_stats, ITEM::NAME::OODACHI);
    temp_wpn.setDescription("Long, curved sword of the eastern lands.");
    all_weapons[ITEM::NAME::OODACHI] = temp_wpn;
    temp_wpn_stats = {7, 0, 75, 5, 0, 0, 5, 30, 8, {1,1}, {1,2}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::SWORD, temp_wpn_stats, ITEM::NAME::UCHIGATANA);
    temp_wpn.setDescription("Curved sword in the style of the eastern lands. Very sharp.");
    all_weapons[ITEM::NAME::UCHIGATANA] = temp_wpn;
    temp_wpn_stats = {1, 0, 50, 0, 0, 0, 1, 20, 10, {1,1}, {1,2}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::SWORD, temp_wpn_stats, ITEM::NAME::EXSANGUE);
    temp_wpn.setEffect(ITEM::EFFECT::LIFESTEAL);
    temp_wpn.setDescription("Drains enemies of their blood. Heals HP equal to damage dealt.");
    all_weapons[ITEM::NAME::EXSANGUE] = temp_wpn;
    temp_wpn_stats = {14, 0, 90, 10, 0, 0, 7, 25, 14, {1,1}, {1,2}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::SWORD, temp_wpn_stats, ITEM::NAME::HAUTECLAIRE);
    temp_wpn.setDescription("Crystal encrusted sword, as described in the Franc legends of old.");
    all_weapons[ITEM::NAME::HAUTECLAIRE] = temp_wpn;
    temp_wpn_stats = {16, 0, 100, 0, 0, 10, 9, 20, 12, {1,1}, {1,2}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::SWORD, temp_wpn_stats, ITEM::NAME::SECUNDUS);
    temp_wpn.setDescription("The first sword made by the God. The first weapon really only the second weapon of man, after his fists.");
    all_weapons[ITEM::NAME::SECUNDUS] = temp_wpn;
    temp_wpn_stats = {15, 0, 90, 10, 0, 0, 10, 30, 15, {1,1}, {1,2}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::SWORD, temp_wpn_stats, ITEM::NAME::EXCALIBUR);
    temp_wpn.setEffective(UNIT::TYPE::DEMON);
    temp_wpn.setDescription("The king's sword. Found in a rock.");
    all_weapons[ITEM::NAME::EXCALIBUR] = temp_wpn;
    temp_wpn_stats = {12, 0, 100, 0, 0, 0, 6, 20, 18, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::SWORD, temp_wpn_stats, ITEM::NAME::GALATINE);
    temp_wpn.setEffective(UNIT::TYPE::ARMOR);
    temp_wpn.setDescription("A pragmatic and honorable knight's thrusting sword. Usually used with off-hand parry daggers.");
    all_weapons[ITEM::NAME::GALATINE] = temp_wpn;
    temp_wpn_stats = {5, 0, 50, 0, 0, 0, 7, 25, 11, {1,2}, {1,2}, 1, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::SWORD, temp_wpn_stats, ITEM::NAME::RAIJINTOU);
    temp_wpn.setDescription("The thunder god's sword. Rains lightning upon enemies at a distance.");
    all_weapons[ITEM::NAME::RAIJINTOU] = temp_wpn;
    temp_wpn_stats = {7, 0, 45, 0, 0, 0, 1, 25, 11, {1,2}, {1,2}, 1, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::SWORD, temp_wpn_stats, ITEM::NAME::FUUJINTOU);
    temp_wpn.setDescription("The wind god's sword. Cuts enemies with wind at a distance.");
    all_weapons[ITEM::NAME::FUUJINTOU] = temp_wpn;
    temp_wpn_stats = {16, 0, 60, 5, 5, 0, 7, 35, 18, {1,1}, {1,2}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::SWORD, temp_wpn_stats, ITEM::NAME::HONJOU_MASAMUNE);
    temp_wpn.setDescription("Lost sword made by the most skilled swordsmith of the eastern lands.");
    all_weapons[ITEM::NAME::HONJOU_MASAMUNE] = temp_wpn;
    temp_wpn_stats = {0, 0, 0, 0, 0, 0, 0, 10, 30, {1,1}, {1,2}, 0, 9001};
    temp_wpn = Weapon(ITEM::TYPE::SWORD, temp_wpn_stats, ITEM::NAME::KIRITO); //Should be found inside a dragon skull? 
    temp_wpn.setDescription("Useless sword of a fake black swordsman.");
    all_weapons[ITEM::NAME::KIRITO] = temp_wpn;
    temp_wpn_stats = {20, 0, 30, 0, 0, 0, 20, 50, 20, {1,1}, {1,2}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::SWORD, temp_wpn_stats, ITEM::NAME::RAW_IRON_SLAB); //Should be found inside a dragon skull? 
    temp_wpn.setDescription("Barely a sword. Too big, too thick, too massive, too rough. Tempered by the malevolence of countless slain demons. Effective against demons and angels.");
    temp_wpn.setEffective(UNIT::TYPE::DEMON + UNIT::TYPE::ANGEL);
    all_weapons[ITEM::NAME::RAW_IRON_SLAB] = temp_wpn;    
    // Should have deeps chinks. This isn't the first time demons roamed the earth. Has deep holes in it. Must be repaired before being usable. Who is willing to repair it? 

    temp_wpn_stats = {2, 0, 60, 0, 0, 0, 4, 15, 1, {1,1}, {1,2}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::LANCE, temp_wpn_stats, ITEM::NAME::PITCHFORK);
    temp_wpn.setDescription("Farming implement. Makeshift lance for desperate times.");
    all_weapons[ITEM::NAME::PITCHFORK] = temp_wpn;
    temp_wpn_stats = {3, 0, 70, 0, 0, 0, 3, 30, 5, {1,1}, {2}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::LANCE, temp_wpn_stats, ITEM::NAME::FIGHTING_STICK);
    temp_wpn.setDescription("Simple two meter long wooden stick. Deadly in competent hands.");
    all_weapons[ITEM::NAME::FIGHTING_STICK] = temp_wpn;
    temp_wpn_stats = {5, 0, 95, 0, 0, 0, 5, 40, 4, {1,1}, {1,2}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::LANCE, temp_wpn_stats, ITEM::NAME::IRON_LANCE);
    temp_wpn.setDescription("Sharp iron tip on a wooden stick. Standard military fare.");
    all_weapons[ITEM::NAME::IRON_LANCE] = temp_wpn;
    temp_wpn_stats = {7, 0, 80, 30, 0, 0, 3, 30, 9, {1,1}, {1,2}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::LANCE, temp_wpn_stats, ITEM::NAME::WRATH_LANCE);
    temp_wpn.setDescription("Increases critical hit chance.");
    all_weapons[ITEM::NAME::WRATH_LANCE] = temp_wpn;
    temp_wpn_stats = {8, 0, 90, 0, 0, 0, 9, 35, 7, {1,1}, {1,2}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::LANCE, temp_wpn_stats, ITEM::NAME::STEEL_LANCE);
    temp_wpn.setDescription("Stronger and deadlier.");
    all_weapons[ITEM::NAME::STEEL_LANCE] = temp_wpn;
    temp_wpn_stats = {12, 0, 85, 0, 0, 0, 12, 25, 13, {1,1}, {1,2}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::LANCE, temp_wpn_stats, ITEM::NAME::DAMAS_LANCE);
    temp_wpn.setDescription("Fancy and fatal.");
    all_weapons[ITEM::NAME::DAMAS_LANCE] = temp_wpn;
    temp_wpn_stats = {6, 0, 60, 0, 0, 0, 15, 10, 8, {1,1}, {1,2}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::LANCE, temp_wpn_stats, ITEM::NAME::HEAVY_SPEAR);
    temp_wpn.setEffective(UNIT::TYPE::ARMOR);
    temp_wpn.setDescription("Heavy enough to pierce armor.");
    all_weapons[ITEM::NAME::HEAVY_SPEAR] = temp_wpn;
    temp_wpn_stats = {8, 0, 90, 0, 0, 0, 8, 10, 10, {1,1}, {1,2}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::LANCE, temp_wpn_stats, ITEM::NAME::TRIDENT);
    temp_wpn.setDescription("Fancy pitchfork");
    all_weapons[ITEM::NAME::TRIDENT] = temp_wpn;
    temp_wpn_stats = {6, 0, 70, 0, 0, 0, 7, 20, 7, {1,1}, {1,2}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::LANCE, temp_wpn_stats, ITEM::NAME::MERCIFUL_LANCE);
    temp_wpn.setDescription("Infused with the life-giving tears of the goddess. Cannot reduce enemy HP below 1.");
    all_weapons[ITEM::NAME::MERCIFUL_LANCE] = temp_wpn;
    temp_wpn_stats = {4, 0, 40, 0, 0, 0, 6, 25, 9, {1,2}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::LANCE, temp_wpn_stats, ITEM::NAME::JAVELIN);
    temp_wpn.setDescription("Simple throwing lance.");
    all_weapons[ITEM::NAME::JAVELIN] = temp_wpn;
    temp_wpn_stats = {6, 0, 45, 0, 0, 0, 8, 23, 10, {1,2}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::LANCE, temp_wpn_stats, ITEM::NAME::PILUM);
    temp_wpn.setDescription("Reliable throwing lance.");
    all_weapons[ITEM::NAME::PILUM] = temp_wpn;
    temp_wpn_stats = {9, 0, 50, 0, 0, 0, 11, 20, 11, {1,2}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::LANCE, temp_wpn_stats, ITEM::NAME::SPEAR);
    temp_wpn.setDescription("Strong throwing Lance. Strikes true.");
    all_weapons[ITEM::NAME::SPEAR] = temp_wpn;
    temp_wpn_stats = {14, 0, 60, 0, 0, 0, 9, 25, 15, {1,2}, {1,2}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::LANCE, temp_wpn_stats, ITEM::NAME::VEL);
    temp_wpn.setDescription("Legendary throwing lance. Said to be able to home in on the heart of your enemies.");
    all_weapons[ITEM::NAME::VEL] = temp_wpn;
    temp_wpn_stats = {8, 0, 90, 0, 0, 0, 6, 20, 9, {1,2}, {1,2}, 1, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::LANCE, temp_wpn_stats, ITEM::NAME::GUNGNIR);
    temp_wpn.setDescription("A lightning bolt resides in its tip. Can shoot lightning at enemies at a distance.");
    all_weapons[ITEM::NAME::GUNGNIR] = temp_wpn;
    temp_wpn_stats = {12, 0, 70, 0, 0, 0, 10, 32, 18, {1,2}, {1,2}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::LANCE, temp_wpn_stats, ITEM::NAME::ACHILLES);
    temp_wpn.setEffect(ITEM::EFFECT::KILL1P);
    temp_wpn.setDescription("Legendary throwing spear named after a fearless, immortal hero. Kills instantly if hits enemy's heel (1%).");
    all_weapons[ITEM::NAME::ACHILLES] = temp_wpn;
    temp_wpn_stats = {16, 0, 50, 0, 0, 0, 14, 24, 17, {1,1}, {1,2}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::LANCE, temp_wpn_stats, ITEM::NAME::TONBOKIRI);
    temp_wpn.setDescription("Cut a dragonfly that tried to land on its tip. Excessively sharp and dangerous.");
    all_weapons[ITEM::NAME::TONBOKIRI] = temp_wpn;

    temp_wpn_stats = {8, 0, 40, 0, 0, 0, 8, 40, 4, {1,1}, {1,2}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::AXE, temp_wpn_stats, ITEM::NAME::IRON_AXE);
    temp_wpn.setDescription("Iron cutting head on a stick. Simple, easy to repair. Bandits' favorite.");
    all_weapons[ITEM::NAME::IRON_AXE] = temp_wpn;
    temp_wpn_stats = {11, 0, 50, 0, 0, 0, 10, 35, 7, {1,1}, {1,2}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::AXE, temp_wpn_stats, ITEM::NAME::STEEL_AXE);
    temp_wpn.setDescription("Steel cutting head on a stick. Stronger. Smart bandits like it.");
    all_weapons[ITEM::NAME::STEEL_AXE] = temp_wpn;
    temp_wpn_stats = {14, 0, 55, 0, 0, 0, 13, 25, 11, {1,1}, {1,2}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::AXE, temp_wpn_stats, ITEM::NAME::DAMAS_AXE);
    temp_wpn.setDescription("Damas cutting head on a stick. Fancy and deadly. Scorned by dumb bandits.");
    all_weapons[ITEM::NAME::DAMAS_AXE] = temp_wpn;
    temp_wpn_stats = {14, 0, 65, 20, 0, 0, 11, 30, 10, {1,1}, {1,2}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::AXE, temp_wpn_stats, ITEM::NAME::WRATH_AXE);
    temp_wpn.setDescription("Increases critical hit chance.");
    all_weapons[ITEM::NAME::WRATH_AXE] = temp_wpn;
    temp_wpn_stats = {6, 0, 30, 0, 0, 0, 7, 25, 5, {1,2}, {1,2}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::AXE, temp_wpn_stats, ITEM::NAME::THROWING_AXE);
    temp_wpn.setDescription("Smaller, balanced axe, made for throwing. Cheapest option for ranged attacks.");
    all_weapons[ITEM::NAME::THROWING_AXE] = temp_wpn;
    temp_wpn_stats = {10, 0, 40, 0, 0, 0, 7, 25, 10, {1,2}, {1,2}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::AXE, temp_wpn_stats, ITEM::NAME::TOMAHAWK);
    temp_wpn.setDescription("Smaller, balanced axe, made for throwing. Cheapest option for ranged attacks.");
    all_weapons[ITEM::NAME::TOMAHAWK] = temp_wpn;
    temp_wpn_stats = {7, 0, 60, 0, 0, 0, 9, 20, 3, {1,1}, {1,2}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::AXE, temp_wpn_stats, ITEM::NAME::PICK_AXE);
    temp_wpn.setDescription("Mining implement. Weapon in time of need.");
    all_weapons[ITEM::NAME::PICK_AXE] = temp_wpn;
    temp_wpn_stats = {4, 0, 40, 0, 0, 0, 5, 25, 2, {1,1}, {1,2}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::AXE, temp_wpn_stats, ITEM::NAME::HOE);
    temp_wpn.setDescription("Farming implement. Can be used as an axe if need be.");
    all_weapons[ITEM::NAME::HOE] = temp_wpn;
    temp_wpn_stats = {9, 0, 50, 5, 0, 0, 6, 15, 1, {1,1}, {1,2}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::AXE, temp_wpn_stats, ITEM::NAME::CLUB);
    temp_wpn.setDescription("Big and wooden. For when the old-world weapons just aren't quite old enough.");
    all_weapons[ITEM::NAME::CLUB] = temp_wpn;
    temp_wpn_stats = {10, 0, 50, 0, 0, 0, 11, 20, 12, {1,1}, {1,2}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::AXE + ITEM::TYPE::LANCE, temp_wpn_stats, ITEM::NAME::HALBERD);
    temp_wpn.setEffective(UNIT::TYPE::MOUNTED);
    temp_wpn.setDescription("Polearm specially designed to deal with cavalry. Is both a lance and an axe.");
    all_weapons[ITEM::NAME::HALBERD] = temp_wpn;
    temp_wpn_stats = {8, 0, 40, 0, 0, 0, 9, 30, 8, {1,1}, {1,2}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::AXE, temp_wpn_stats, ITEM::NAME::HAMMER);
    temp_wpn.setEffective(UNIT::TYPE::ARMOR);
    temp_wpn.setDescription("Armor cannot stand the hammer's heavy crushing blows.");
    all_weapons[ITEM::NAME::HAMMER] = temp_wpn;
    temp_wpn_stats = {12, 0, 50, 0, 0, 0, 12, 25, 11, {1,1}, {1,2}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::AXE, temp_wpn_stats, ITEM::NAME::WAR_PICK);
    temp_wpn.setEffective(UNIT::TYPE::ARMOR);
    temp_wpn.setDescription("In trained hands, the pick can penatrate armor.");
    all_weapons[ITEM::NAME::WAR_PICK] = temp_wpn;
    temp_wpn_stats = {15, 0, 45, 0, 0, 0, 14, 30, 14, {1,1}, {1,2}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::AXE, temp_wpn_stats, ITEM::NAME::BATTLEAXE);
    temp_wpn.setDescription("Double-bladed, comically oversized axe.");
    all_weapons[ITEM::NAME::BATTLEAXE] = temp_wpn;
    temp_wpn_stats = {17, 0, 60, 0, 0, 0, 17, 20, 17, {1,1}, {1,2}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::AXE, temp_wpn_stats, ITEM::NAME::VIDYU);
    temp_wpn.setDescription("Battleaxe of the many-headed and armed gods of the east.");
    all_weapons[ITEM::NAME::VIDYU] = temp_wpn;
    temp_wpn_stats = {19, 0, 70, 0, 0, 0, 5, 60, 20, {1,1}, {1,2}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::AXE, temp_wpn_stats, ITEM::NAME::HEPHAESTUS);
    temp_wpn.setDescription("The god's hammer. Used to forge Secundus, the first sword. Basically a vaguely square stone fixed to a wooden handle.");
    all_weapons[ITEM::NAME::HEPHAESTUS] = temp_wpn;

    temp_wpn_stats = {12, 0, 70, 0, 0, 0, 14, 35, 9, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::BOW, temp_wpn_stats, ITEM::NAME::ADAPTED_CROSSBOW);
    temp_wpn.setDescription("Crossbow adapted to be fired, reloaded and drawn using one hand and one stump. 1H assassin only.");
    all_weapons[ITEM::NAME::ADAPTED_CROSSBOW] = temp_wpn;
    temp_wpn_stats = {8, 0, 60, 0, 0, 0, 18, 28, 14, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::BOW, temp_wpn_stats, ITEM::NAME::REPEATABLE_CROSSBOW);
    temp_wpn.setDescription("Crossbow that fires many bolts every attack.");
    all_weapons[ITEM::NAME::REPEATABLE_CROSSBOW] = temp_wpn;
    temp_wpn_stats = {10, 0, 85, 0, 0, 0, 12, 15, 7, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::BOW, temp_wpn_stats, ITEM::NAME::CROSSBOW);
    temp_wpn.setDescription("Powerful and easier to use than a bow, although quite heavy.");
    all_weapons[ITEM::NAME::CROSSBOW] = temp_wpn;
    temp_wpn_stats = {4, 0, 90, 0, 0, 0, 4, 35, 5, {1,2}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::BOW, temp_wpn_stats, ITEM::NAME::SHORT_BOW);
    temp_wpn.setDescription("Simple and light bow.");
    all_weapons[ITEM::NAME::SHORT_BOW] = temp_wpn;
    temp_wpn_stats = {8, 0, 70, 0, 0, 0, 10, 25, 11, {1,3}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::BOW, temp_wpn_stats, ITEM::NAME::LONG_BOW);
    temp_wpn.setDescription("Long and heavy bow. Has increased range.");
    all_weapons[ITEM::NAME::LONG_BOW] = temp_wpn;
    temp_wpn_stats = {7, 0, 80, 0, 0, 0, 5, 30, 10, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::BOW, temp_wpn_stats, ITEM::NAME::COMPOSITE_BOW);
    temp_wpn.setDescription("Bow made of laminated wood and animal horn. Very useful for horseback shooting.");
    all_weapons[ITEM::NAME::COMPOSITE_BOW] = temp_wpn;
    temp_wpn_stats = {18, 0, 50, 0, 0, 0, 19, 20, 11, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::BOW, temp_wpn_stats, ITEM::NAME::RECURVE_CROSSBOW);
    temp_wpn.setDescription("Crossbow with recurve limbs. Heavy and powerful.");
    all_weapons[ITEM::NAME::RECURVE_CROSSBOW] = temp_wpn;
    temp_wpn_stats = {13, 0, 75, 0, 0, 0, 10, 24, 14, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::BOW, temp_wpn_stats, ITEM::NAME::RECURVE_BOW);
    temp_wpn.setDescription("Bow whose limbs curve away when unstrung. Shoots faster and deadlier arrows.");
    all_weapons[ITEM::NAME::RECURVE_BOW] = temp_wpn;
    temp_wpn_stats = {19, 0, 69, 0, 0, 0, 9, 25, 17, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::BOW, temp_wpn_stats, ITEM::NAME::APOLLO);
    temp_wpn.setDescription("Bow crafted of sun rays, used by the most handsome ancient god.");
    all_weapons[ITEM::NAME::APOLLO] = temp_wpn;
    temp_wpn_stats = {18, 0, 96, 0, 0, 0, 4, 26, 19, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::BOW, temp_wpn_stats, ITEM::NAME::ARTEMIS);
    temp_wpn.setDescription("Bow of the ancient goddess of hunting.");
    all_weapons[ITEM::NAME::ARTEMIS] = temp_wpn;
    temp_wpn_stats = {17, 0, 100, 0, 0, 0, 7, 35, 16, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::BOW, temp_wpn_stats, ITEM::NAME::PINAKA);
    temp_wpn.setDescription("Bow of the god of death.");
    all_weapons[ITEM::NAME::PINAKA] = temp_wpn;

    temp_wpn_stats = {5, 0, 0, 10, 0, 5, 4, 45, 8, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::SHIELD, temp_wpn_stats, ITEM::NAME::ADAPTED_SHIELD);
    temp_wpn.setDescription("Shield adapted to be used without one\'s weak hand. Straps on the forearm. 1H assassin only.");
    all_weapons[ITEM::NAME::ADAPTED_SHIELD] = temp_wpn;
    temp_wpn_stats = {1, 0, 0, 5, 0, 1, 2, 15, 2, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::SHIELD, temp_wpn_stats, ITEM::NAME::POT_LID);
    temp_wpn.setDescription("Useful in the kitchen. For the poor militia man: life saving device.");
    all_weapons[ITEM::NAME::POT_LID] = temp_wpn;
    temp_wpn_stats = {2, 0, 0, 8, 0, 0, 3, 20, 7, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::SHIELD, temp_wpn_stats, ITEM::NAME::WOODEN_SHIELD);
    temp_wpn.setDescription("Simple wood plank with a strap. Will probably save your life.");
    all_weapons[ITEM::NAME::WOODEN_SHIELD] = temp_wpn;
    temp_wpn_stats = {4, 0, 0, 10, 0, 4, 5, 0, 13, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::SHIELD, temp_wpn_stats, ITEM::NAME::CLOAK);
    temp_wpn.setDescription("The Mousquetaire\"s offhand shield in time of need.");
    all_weapons[ITEM::NAME::CLOAK] = temp_wpn;
    temp_wpn_stats = {3, 0, 0, 9, 0, 2, 4, 25, 9, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::SHIELD, temp_wpn_stats, ITEM::NAME::LEATHER_SHIELD);
    temp_wpn.setDescription("Wooden plank lined with leather. Smooth and slippery. Cheap way to redirect weapons away from the body.");
    all_weapons[ITEM::NAME::LEATHER_SHIELD] = temp_wpn;
    temp_wpn_stats = {8, 0, 0, 15, 0, 4, 4, 35, 12, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::SHIELD, temp_wpn_stats, ITEM::NAME::KITE_SHIELD);
    temp_wpn.setDescription("Large wooden shield of recognizable shape, to increase protection.");
    all_weapons[ITEM::NAME::KITE_SHIELD] = temp_wpn;
    temp_wpn_stats = {6, 0, 0, 6, 0, 6, 6, 36, 6, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::SHIELD, temp_wpn_stats, ITEM::NAME::IRON_BUCKLER);
    temp_wpn.setDescription("Small round iron shield. Light, resistant.");
    all_weapons[ITEM::NAME::IRON_BUCKLER] = temp_wpn;
    temp_wpn_stats = {7, 0, 0, 7, 0, 7, 7, 37, 7, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::SHIELD, temp_wpn_stats, ITEM::NAME::STEEL_BUCKLER);
    temp_wpn.setDescription("Small round steel shield. Heavier and more resistant.");
    all_weapons[ITEM::NAME::STEEL_BUCKLER] = temp_wpn;
    temp_wpn_stats = {5, 0, 0, 5, 0, 5, 9, 30, 10, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::SHIELD, temp_wpn_stats, ITEM::NAME::SPIKED_BUCKLER);
    temp_wpn.setDescription("Iron buckler with a prickly spike at its center. Damages attackers upon their attacks.");
    all_weapons[ITEM::NAME::SPIKED_BUCKLER] = temp_wpn;
    temp_wpn_stats = {11, 0, 0, 15, 0, 5, 13, 25, 7, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::SHIELD, temp_wpn_stats, ITEM::NAME::SCUTUM);
    temp_wpn.setDescription("Very large and heavy shield.");
    all_weapons[ITEM::NAME::SCUTUM] = temp_wpn;
    temp_wpn_stats = {12, 0, 0, 20, 0, 10, 10, 0, 14, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::SHIELD, temp_wpn_stats, ITEM::NAME::MASTER_SHIELD);
    temp_wpn.setDescription("Shield of the princess of time.");
    all_weapons[ITEM::NAME::MASTER_SHIELD] = temp_wpn;
    temp_wpn_stats = {9, 0, 0, 5, 0, 200, 9, 22, 13, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::SHIELD, temp_wpn_stats, ITEM::NAME::GODDESS_HAND);
    temp_wpn.setDescription("Offers the protection of the goddess. Negates enemy critical hits.");
    all_weapons[ITEM::NAME::GODDESS_HAND] = temp_wpn;
    temp_wpn_stats = {15, 0, 0, 10, 0, 2, 13, 19, 12, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::SHIELD, temp_wpn_stats, ITEM::NAME::ANCILE);
    temp_wpn.setDescription("Shield of the ancient god of war.");
    all_weapons[ITEM::NAME::ANCILE] = temp_wpn;
    temp_wpn_stats = {15, 0, 0, 10, 0, 2, 13, 19, 12, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::SHIELD, temp_wpn_stats, ITEM::NAME::ROCK_PLATE);
    temp_wpn.setDescription("Almost a raw boulder. The powerful and dumb demon's favorite.");
    all_weapons[ITEM::NAME::ROCK_PLATE] = temp_wpn;
    temp_wpn_stats = {15, 0, 0, 10, 0, 2, 13, 19, 12, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::SHIELD, temp_wpn_stats, ITEM::NAME::OBSIDIAN_PLATE);
    temp_wpn.setDescription("Rock melted by demon-breath, then recystallized into a more demon-claw friendly shape. Even harder than rock, but more brittle.");
    all_weapons[ITEM::NAME::OBSIDIAN_PLATE] = temp_wpn;
    temp_wpn_stats = {15, 0, 0, 10, 0, 2, 13, 19, 12, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::SHIELD, temp_wpn_stats, ITEM::NAME::MARBLE_PLATE_SHIELD);
    temp_wpn.setDescription("Kite shield lined in an ornate layer of sculpted marble. Magical.");
    all_weapons[ITEM::NAME::MARBLE_PLATE_SHIELD] = temp_wpn;
    temp_wpn_stats = {15, 0, 0, 10, 0, 2, 13, 19, 12, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::SHIELD, temp_wpn_stats, ITEM::NAME::DIVINE_PROTECTOR);
    temp_wpn.setDescription("Large tower shield imbued with angelic properties. Surprisingly light and effective against magic attacks.");
    all_weapons[ITEM::NAME::DIVINE_PROTECTOR] = temp_wpn;

    // Daggers get ridiculously low hit cause they are short and stubby!!!! Kitchen knife is the only exception.
    temp_wpn_stats = {2, 0, 10, 0, 10, 0, 5, 21, 16, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::OFFHAND, temp_wpn_stats, ITEM::NAME::WRISTBLADE);
    temp_wpn.setDescription("Blade generally strapped to the weak forearm. Used by assassins to increase crit potential.");
    all_weapons[ITEM::NAME::WRISTBLADE] = temp_wpn;
    temp_wpn_stats = {2, 0, 10, 0, 10, 0, 5, 21, 16, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::OFFHAND, temp_wpn_stats, ITEM::NAME::SHIELD_HOOK);
    temp_wpn.setDescription("Offhand weapon designed to grab on shields to drag them aside. Ignores shield bonuses.");
    temp_wpn.setEffect(ITEM::EFFECT::IGNORE_SHIELD);
    all_weapons[ITEM::NAME::SHIELD_HOOK] = temp_wpn;
    temp_wpn_stats = {4, 0, 8, 0, 14, 0, 7, 16, 19, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::OFFHAND, temp_wpn_stats, ITEM::NAME::RETRACTABLE_WRISTBLADE);
    temp_wpn.setDescription("Blade generally strapped to the weak forearm. Controlled by hand movements. Used by assasins to stealthily increase crit potential.");
    all_weapons[ITEM::NAME::RETRACTABLE_WRISTBLADE] = temp_wpn;
    temp_wpn_stats = {1, 0, 0, 10, 0, 5, 4, 35, 7, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::OFFHAND, temp_wpn_stats, ITEM::NAME::MAIN_GAUCHE);
    temp_wpn.setDescription("Dagger designed to parry using the left/weak/off-hand. Increases avoir and favor.");
    all_weapons[ITEM::NAME::MAIN_GAUCHE] = temp_wpn;
    temp_wpn_stats = {2, 0, 0, 22, 0, 4, 6, 28, 12, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::OFFHAND, temp_wpn_stats, ITEM::NAME::SWORDBREAKER);
    temp_wpn.setDescription("Dagger with slots designed to catch swords. Increases avoid and favor. Rarely does it actually break swords...");
    all_weapons[ITEM::NAME::SWORDBREAKER] = temp_wpn;
    temp_wpn_stats = {3, 0, 14, 0, 8, 0, 4, 20, 10, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::OFFHAND, temp_wpn_stats, ITEM::NAME::TRIDENT_DAGGER);
    temp_wpn.setDescription("Dagger whose blade splits into three prongs. Designed to catch opposing swords. Increases avoid and favor.");
    all_weapons[ITEM::NAME::TRIDENT_DAGGER] = temp_wpn;
    temp_wpn_stats = {3, 0, 5, 0, 0, 0, 2, 26, 8, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::OFFHAND, temp_wpn_stats, ITEM::NAME::TANTOU);
    temp_wpn.setDescription("Eastern style short dagger. Very sharp and dangerous. Increases might.");
    all_weapons[ITEM::NAME::TANTOU] = temp_wpn;
    temp_wpn_stats = {5, 0, 8, 0, 0, 0, 4, 24, 11, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::OFFHAND, temp_wpn_stats, ITEM::NAME::KODACHI);
    temp_wpn.setDescription("Dagger used by the legendary assasins of the East, the Ninja. Increases might.");
    all_weapons[ITEM::NAME::KODACHI] = temp_wpn;
    temp_wpn_stats = {4, 0, 10, 0, 0, 0, 3, 20, 10, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::OFFHAND, temp_wpn_stats, ITEM::NAME::DAGUE);
    temp_wpn.setDescription("Messenic dagger. Simple and efficient. Beautiful engravings adorn the blade surface. ");
    all_weapons[ITEM::NAME::DAGUE] = temp_wpn;
    temp_wpn_stats = {7, 0, 0, 0, 0, 0, 8, 10, 15, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::OFFHAND, temp_wpn_stats, ITEM::NAME::WAKIZASHI);
    temp_wpn.setDescription("Dagger of the warriors of the East. Companion of the uchigatana. Very deadly.");
    all_weapons[ITEM::NAME::WAKIZASHI] = temp_wpn;
    temp_wpn_stats = {2, 0, 0, 0, 0, 0, 4, 15, 7, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::OFFHAND, temp_wpn_stats, ITEM::NAME::BRAQUEMARD);
    temp_wpn.setDescription("Legendary Dagger.");
    all_weapons[ITEM::NAME::BRAQUEMARD] = temp_wpn;
    temp_wpn_stats = {0, 0, 0, 0, 0, 0, 7, 30, 10, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::OFFHAND, temp_wpn_stats, ITEM::NAME::MISERICORDE);
    temp_wpn.setDescription("Used to delivery the Coup de grace to wounded knights. Might of this dagger increases by one for each missing 3 health.");
    all_weapons[ITEM::NAME::MISERICORDE] = temp_wpn;
    temp_wpn_stats = {8, 0, 10, 10, 0, 2, 9, 24, 17, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::OFFHAND, temp_wpn_stats, ITEM::NAME::CARNWENNAN);
    temp_wpn.setDescription("The king\'s dagger. Has the power to shroud its user in shadow.");
    all_weapons[ITEM::NAME::CARNWENNAN] = temp_wpn;
    temp_wpn_stats = {7, 0, 0, 0, 0, 0, 7, 8, 5, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::OFFHAND, temp_wpn_stats, ITEM::NAME::FLINTLOCK);
    temp_wpn.setDescription("A gun!");
    all_weapons[ITEM::NAME::FLINTLOCK] = temp_wpn;

    temp_wpn_stats = {7, 0, 0, 0, 0, 0, 7, 8, 5, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::TRINKET, temp_wpn_stats, ITEM::NAME::SHRUNKEN_HEAD);
    temp_wpn.setDescription("Horrible. Infused with demonic energies.");
    all_weapons[ITEM::NAME::SHRUNKEN_HEAD] = temp_wpn;
    temp_wpn_stats = {7, 0, 0, 0, 0, 0, 7, 8, 5, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::TRINKET, temp_wpn_stats, ITEM::NAME::CRYSTAL);
    temp_wpn.setDescription("");
    all_weapons[ITEM::NAME::CRYSTAL] = temp_wpn;
    temp_wpn_stats = {7, 0, 0, 0, 0, 0, 7, 8, 5, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::TRINKET, temp_wpn_stats, ITEM::NAME::HUMAN_FEMUR);
    temp_wpn.setDescription("Taken from an ancient tomb. Used by demons to increase their magic power.");
    all_weapons[ITEM::NAME::HUMAN_FEMUR] = temp_wpn;
    temp_wpn_stats = {7, 0, 0, 0, 0, 0, 7, 8, 5, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::TRINKET, temp_wpn_stats, ITEM::NAME::VOID_FRAGMENT);
    temp_wpn.setDescription("");
    all_weapons[ITEM::NAME::VOID_FRAGMENT] = temp_wpn;
    temp_wpn_stats = {7, 0, 0, 0, 0, 0, 7, 8, 5, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::TRINKET, temp_wpn_stats, ITEM::NAME::DEMON_FANG);
    temp_wpn.setDescription("Ripped from the mouth of a dead demon. Unusable by demons.");
    all_weapons[ITEM::NAME::DEMON_FANG] = temp_wpn;
    temp_wpn_stats = {7, 0, 0, 0, 0, 0, 7, 8, 5, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::TRINKET, temp_wpn_stats, ITEM::NAME::ANGEL_FEATHER);
    temp_wpn.setDescription("Beautiful and fluffy. Given by incarnates and possessed to the worthy. Increases magical ability. Unusable by demons and demon incarnates.");
    all_weapons[ITEM::NAME::ANGEL_FEATHER] = temp_wpn;
    temp_wpn_stats = {7, 0, 0, 0, 0, 0, 7, 8, 5, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::TRINKET, temp_wpn_stats, ITEM::NAME::ANGEL_HAIR);
    temp_wpn.setDescription("Golden strands of angel hair held up by a silver thread. Increases magical ability. Unusable by demons and demon incarnates.");
    all_weapons[ITEM::NAME::ANGEL_HAIR] = temp_wpn;
    temp_wpn_stats = {7, 0, 0, 0, 0, 0, 7, 8, 5, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::TRINKET, temp_wpn_stats, ITEM::NAME::VIAL_OF_LIGHT);
    temp_wpn.setDescription("Light magically contained in glass. Shines brightest in darkness.");
    all_weapons[ITEM::NAME::VIAL_OF_LIGHT] = temp_wpn;
    temp_wpn_stats = {7, 0, 0, 0, 0, 0, 7, 8, 5, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::TRINKET, temp_wpn_stats, ITEM::NAME::GLASS_ORB);
    temp_wpn.setDescription("Orb used to focus magical power.");
    all_weapons[ITEM::NAME::GLASS_ORB] = temp_wpn;
    temp_wpn_stats = {7, 0, 0, 0, 0, 0, 7, 8, 5, {1,1}, {1}, 0, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::TRINKET, temp_wpn_stats, ITEM::NAME::WAR_HORN);
    temp_wpn.setDescription("Used to call for battle. Raise's close allies' combat abilities.");
    all_weapons[ITEM::NAME::WAR_HORN] = temp_wpn;

    temp_wpn_stats = {0, 12, 76, 0, 0, 0, 11, 25, 7, {1,2}, {1,2}, 1, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::ELEMENTAL, temp_wpn_stats, ITEM::NAME::BALL_LIGHTNING);
    temp_wpn.setDescription("Lightning, compressed and explosive.");
    all_weapons[ITEM::NAME::BALL_LIGHTNING] = temp_wpn;
    temp_wpn_stats = {0, 6, 70, 0, 0, 0, 5, 34, 7, {1,2}, {1,2}, 1, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::ELEMENTAL, temp_wpn_stats, ITEM::NAME::ICICLE);
    temp_wpn.setDescription("Summons sharp and cold death spikes.");
    all_weapons[ITEM::NAME::ICICLE] = temp_wpn;
    temp_wpn_stats = {0, 14, 50, 0, 0, 0, 13, 20, 7, {1,2}, {1,2}, 1, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::ELEMENTAL, temp_wpn_stats, ITEM::NAME::VOLCANO);
    temp_wpn.setDescription("Summons magma spewing mountains from under enemies' feets.");
    all_weapons[ITEM::NAME::VOLCANO] = temp_wpn;
    temp_wpn_stats = {0, 4, 80, 0, 0, 0, 3, 40, 7, {1,2}, {1,2}, 1, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::ELEMENTAL, temp_wpn_stats, ITEM::NAME::WIND_SPEAR);
    temp_wpn.setDescription("Invisible, swift and minuscule. Can pierce armor.");
    all_weapons[ITEM::NAME::WIND_SPEAR] = temp_wpn;
    temp_wpn_stats = {0, 6, 60, 0, 0, 0, 8, 30, 7, {1,2}, {1,2}, 1, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::ELEMENTAL, temp_wpn_stats, ITEM::NAME::EMBER);
    temp_wpn.setDescription("Summon smoldering embers.");    
    all_weapons[ITEM::NAME::EMBER] = temp_wpn;
    temp_wpn_stats = {0, 13, 40, 0, 0, 0, 11, 25, 7, {1,2}, {1,2}, 1, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::ELEMENTAL, temp_wpn_stats, ITEM::NAME::TSUNAMI);
    temp_wpn.setDescription("");
    all_weapons[ITEM::NAME::TSUNAMI] = temp_wpn;
    temp_wpn_stats = {0, 18, 50, 0, 0, 0, 11, 15, 7, {1,2}, {1,2}, 1, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::ELEMENTAL, temp_wpn_stats, ITEM::NAME::GOD_FORGE_FIRE);
    temp_wpn.setDescription("The fire used to forge Secundus, contained magically. Can melt any and all metals.");
    all_weapons[ITEM::NAME::GOD_FORGE_FIRE] = temp_wpn;
    temp_wpn_stats = {0, 11, 50, 0, 0, 0, 9, 20, 7, {1,2}, {1,2}, 1, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::ELEMENTAL, temp_wpn_stats, ITEM::NAME::FINGOLFIN);
    temp_wpn.setDescription("Distilled courage. Strikes at 7 times at darkness's heart. Effective against demons.");
    temp_wpn.setEffective(UNIT::TYPE::DEMON);
    all_weapons[ITEM::NAME::FINGOLFIN] = temp_wpn;
    temp_wpn_stats = {0, 6, 65, 0, 0, 0, 5, 28, 7, {1,2}, {1,2}, 1, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::ELEMENTAL, temp_wpn_stats, ITEM::NAME::MITHRANDIR);
    temp_wpn.setDescription("Inspires courage in the hearts of men. Effective against demons.");
    temp_wpn.setEffective(UNIT::TYPE::DEMON);
    all_weapons[ITEM::NAME::MITHRANDIR] = temp_wpn;

    temp_wpn_stats = {0, 5, 70, 0, 0, 0, 5, 60, 7, {1,2}, {1,2}, 1, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::DEMONIC, temp_wpn_stats, ITEM::NAME::VOIDD);
    temp_wpn.setDescription("");
    all_weapons[ITEM::NAME::VOIDD] = temp_wpn;
    temp_wpn_stats = {0, 5, 70, 0, 0, 0, 5, 60, 7, {1,2}, {1,2}, 1, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::DEMONIC, temp_wpn_stats, ITEM::NAME::NETHER);
    temp_wpn.setDescription("");
    all_weapons[ITEM::NAME::NETHER] = temp_wpn;
    temp_wpn_stats = {0, 5, 70, 0, 0, 0, 5, 60, 7, {1,2}, {1,2}, 1, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::DEMONIC, temp_wpn_stats, ITEM::NAME::DOWNFALL);
    temp_wpn.setDescription("");
    all_weapons[ITEM::NAME::DOWNFALL] = temp_wpn;
    temp_wpn_stats = {0, 5, 70, 0, 0, 0, 5, 60, 7, {1,2}, {1,2}, 1, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::DEMONIC, temp_wpn_stats, ITEM::NAME::CONSUME);
    temp_wpn.setDescription("");
    all_weapons[ITEM::NAME::CONSUME] = temp_wpn;
    temp_wpn_stats = {0, 5, 70, 0, 0, 0, 5, 60, 7, {1,2}, {1,2}, 1, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::DEMONIC, temp_wpn_stats, ITEM::NAME::PUTRIFY);
    temp_wpn.setDescription("Brings out the inner rot.");
    all_weapons[ITEM::NAME::PUTRIFY] = temp_wpn;
    temp_wpn_stats = {0, 5, 70, 0, 0, 0, 5, 60, 7, {1,2}, {1,2}, 1, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::DEMONIC, temp_wpn_stats, ITEM::NAME::GLAURUNG);
    temp_wpn.setDescription("");
    all_weapons[ITEM::NAME::GLAURUNG] = temp_wpn;
    temp_wpn_stats = {0, 5, 70, 0, 0, 0, 5, 60, 7, {1,2}, {1,2}, 1, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::DEMONIC, temp_wpn_stats, ITEM::NAME::MORGOTH);
    temp_wpn.setDescription("Dark power, in the shape of a massive dark hammer. Makes craters wherever it strikes.");
    all_weapons[ITEM::NAME::MORGOTH] = temp_wpn;
    temp_wpn_stats = {0, 5, 70, 0, 0, 0, 5, 60, 7, {1,2}, {1,2}, 1, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::DEMONIC, temp_wpn_stats, ITEM::NAME::GOTHMOG);
    temp_wpn.setDescription("Infernal whip of flame and shadows.");
    all_weapons[ITEM::NAME::GOTHMOG] = temp_wpn;
    temp_wpn_stats = {0, 5, 70, 0, 0, 0, 5, 60, 7, {1,2}, {1,2}, 1, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::DEMONIC, temp_wpn_stats, ITEM::NAME::FATALIS);
    temp_wpn.setDescription("");
    all_weapons[ITEM::NAME::FATALIS] = temp_wpn;

    temp_wpn_stats = {0, 5, 70, 0, 0, 0, 5, 60, 7, {1,2}, {1,2}, 1, 1000, 0};
    temp_wpn = Weapon(ITEM::TYPE::STAFF, temp_wpn_stats, ITEM::NAME::FATALIS);
    temp_wpn.setDescription("");
    all_weapons[ITEM::NAME::FATALIS] = temp_wpn;
}
