/*! \page handle weapon.cpp
* \file weapon.cpp
* \brief weapon class implementation.
*/
#include "weapon.hpp"
#include "shared.hpp"

Weapon::Weapon() {

}

Weapon::Weapon(Weapon_stats in_stats) {
    stats = in_stats;
}

Weapon::Weapon(std::string in_name, Weapon_stats in_stats) : Weapon(in_stats) {
    name = in_name;
}

Weapon::Weapon(std::string in_name, short unsigned int in_type, Weapon_stats in_stats) : Weapon(in_name, in_stats) {
    type = in_type;
}

Weapon::Weapon(std::string in_name, short unsigned int in_type, Weapon_stats in_stats, unsigned char in_id) : Weapon(in_name, in_type, in_stats) {
    id = in_id;
}

Weapon_stats Weapon::getStats() {
    return(stats);
}

void Weapon::setMalus(Unit_stats in_malus) {
    malus = in_malus;
}

Unit_stats Weapon::getMalus() {
    return(malus);
}

void Weapon::setStats(Weapon_stats in_stats) {
    stats = in_stats;
}

void Weapon::setBonus(Unit_stats in_bonus) {
    bonus = in_bonus;
}
Unit_stats Weapon::getBonus() {
    return(bonus);
}

void Weapon::setEffect(std::string in_effect) {
    effect = in_effect;
}
std::string Weapon::getEffect() {
    return(effect);
}
void Weapon::setEffective(std::string in_effective) {
	effective = in_effective;
}
std::string Weapon::getEffective() {
    return(effective);
}
void Weapon::setDescription(std::string in_description) {
	description = in_description;
}
std::string Weapon::getDescription() {
    return(description);
}
std::string Weapon::getName() {
    return(name);
}
short unsigned int Weapon::getType() {
    return(type);
}
void Weapon::setType(short unsigned int in_type) {
    type = in_type;
}

void Weapon::write(const char * filename, const char * mode){
    FILE * fp;
    fp = fopen(filename, mode);
    fprintf(fp, "%s \n", name.c_str());
    std::vector<std::string> wpn_types = wpntype2str(type);
    for (short unsigned int i = 0; i < wpn_types.size(); i++) {
        fprintf(fp, "%s \n", wpn_types[i].c_str());
    }
    fprintf(fp, "%d", type);
    fprintf(fp, "\n");
    fprintf(fp, "%s \n", description.c_str());
    fprintf(fp, "%s \n", effect.c_str());
    if (stats.dmg_type) {
        fprintf(fp, "Damage type: %s \n", "Magic");
    } else {
        fprintf(fp, "Damage type: %s \n", "Physical");
    }
    // Handedness variable sucks and is hard to print.
    fprintf(fp, "Stats, PMight, MMight, Hit, Dodge, Crit, Favor, Weight, Proficiency, Range min, Range max, Price\n");
    fprintf(fp, "Stats,\t\t%d,\t%d,\t%d,\t%d,\t%d,\t%d,\t%d,\t%d,\t%d,\t%d,\t%d\n", stats.Pmight, stats.Mmight, stats.combat.hit, stats.combat.dodge, stats.combat.crit, stats.combat.favor, stats.prof, stats.uses, stats.wgt, stats.price);
    fprintf(fp, "Units Stats, HP, Str, Mag, Skl, Spd, Luck, Def, Res, Con, Move\n");
    fprintf(fp, "Unit Malus,\t\t%d,\t%d,\t%d,\t%d,\t%d,\t%d,\t%d,\t%d,\t%d,\t%d,\t%d\n", malus.hp, malus.str, malus.mag, malus.dex, malus.agi, malus.luck, malus.def, malus.res, malus.con, malus.move, malus.prof);
    fprintf(fp, "Unit Bonus,\t\t%d,\t%d,\t%d,\t%d,\t%d,\t%d,\t%d,\t%d,\t%d,\t%d,\t%d\n", bonus.hp, bonus.str, bonus.mag, bonus.dex, bonus.agi, bonus.luck, bonus.def, bonus.res, bonus.con, bonus.move, bonus.prof);
    fprintf(fp, "\n");
    fclose(fp);
}

std::vector<Weapon> all_weapons(WEAPON::END);

void baseWeapons2(){
    Weapon temp_wpn;
    Weapon_stats temp_wpn_stats;
    // Pmight, Mmight, hit, dodge, crit, favor, wgt, uses, wpnlvl, range, hand, dmg_type, cost
    temp_wpn_stats = {3, 0, 80, 0, 0, 0, 3, 30, 2, {1,1}, {1,2}, 0, 1000};
    temp_wpn = Weapon("Wooden sword", WPN_TYPE::SWORD, temp_wpn_stats, WEAPON::WOODEN_SWORD);
    temp_wpn.setDescription("Practice sword, made of wood. It's crushing blows are still deadly.");
    all_weapons[WEAPON::WOODEN_SWORD] = temp_wpn;
    temp_wpn_stats = {1, 0, 25, 0, 0, 0, 2, 10, 1, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Kitchen knife", WPN_TYPE::SWORD, temp_wpn_stats, WEAPON::KITCHEN_KNIFE);
    temp_wpn.setDescription("The poor, desperate swordman's dagger.");
    all_weapons[WEAPON::KITCHEN_KNIFE] = temp_wpn;
    temp_wpn_stats = {7, 0, 70, 0, 25, 0, 7, 30, 9, {1,1}, {1,2}, 0, 1000};
    temp_wpn = Weapon("Wrath sword", WPN_TYPE::SWORD, temp_wpn_stats, WEAPON::WRATH_SWORD);
    temp_wpn.setDescription("Increases critical hit chance.");
    all_weapons[WEAPON::WRATH_SWORD] = temp_wpn;
    temp_wpn_stats = {4, 0, 90, 0, 0, 0, 4, 20, 6, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Fleuret", WPN_TYPE::SWORD, temp_wpn_stats, WEAPON::FLEURET);
    temp_wpn.setEffective("Armor");
    temp_wpn.setDescription("Simple and light thrust swords. Effective against armor. Usually used with off-hand parry daggers.");
    all_weapons[WEAPON::FLEURET] = temp_wpn;
    temp_wpn_stats = {8, 0, 85, 5, 0, 0, 5, 25, 8, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Rapière", WPN_TYPE::SWORD, temp_wpn_stats, WEAPON::RAPIERE);
    temp_wpn.setEffective("Armor");
    temp_wpn.setDescription("Strong thrust swords. Effective against armor. Usually used with off-hand parry daggers.");
    all_weapons[WEAPON::RAPIERE] = temp_wpn;
    temp_wpn_stats = {5, 0, 55, 0, 0, 0, 7, 30, 3, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Glaive", WPN_TYPE::SWORD, temp_wpn_stats, WEAPON::GLAIVE);
    temp_wpn.setDescription("Old-world style short sword.");
    all_weapons[WEAPON::GLAIVE] = temp_wpn;
    temp_wpn_stats = {7, 0, 60, 10, 0, 0, 6, 33, 8, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Saber", WPN_TYPE::SWORD, temp_wpn_stats, WEAPON::SABER);
    temp_wpn.setDescription("Curved sword made for slashing.");
    all_weapons[WEAPON::SABER] = temp_wpn;
    temp_wpn_stats = {8, 0, 60, 15, 0, 0, 8, 27, 10, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Fauchon", WPN_TYPE::SWORD, temp_wpn_stats, WEAPON::FAUCHON);
    temp_wpn.setDescription("Curved sword made for slashing.");
    all_weapons[WEAPON::FAUCHON] = temp_wpn;
    temp_wpn_stats = {6, 0, 70, 0, 0, 0, 6, 45, 6, {1,1}, {1,2}, 0, 1000};
    temp_wpn = Weapon("Iron sword", WPN_TYPE::SWORD, temp_wpn_stats, WEAPON::IRON_SWORD);
    temp_wpn.setDescription("Simple straight sword made of iron. Cheap and reliable.");
    all_weapons[WEAPON::IRON_SWORD] = temp_wpn;
    temp_wpn_stats = {9, 0, 60, 0, 0, 0, 9, 30, 10, {1,1}, {1,2}, 0, 1000};
    temp_wpn = Weapon("Steel sword", WPN_TYPE::SWORD, temp_wpn_stats, WEAPON::STEEL_SWORD);
    temp_wpn.setDescription("Simple straight sword made of steel. Strong and durable.");
    all_weapons[WEAPON::STEEL_SWORD] = temp_wpn;
    temp_wpn_stats = {13, 0, 65, 0, 0, 0, 10, 25, 12, {1,1}, {1,2}, 0, 1000};
    temp_wpn = Weapon("Damas sword", WPN_TYPE::SWORD, temp_wpn_stats, WEAPON::DAMAS_SWORD);
    temp_wpn.setDescription("Simple straight sword made of damascus steel. Beautifully rippled, deadly and expensive.");
    all_weapons[WEAPON::DAMAS_SWORD] = temp_wpn;
    temp_wpn_stats = {4, 0, 70, 0, 0, 10, 6, 30, 9, {1,1}, {1,2}, 0, 1000};
    temp_wpn = Weapon("Merciful blade", WPN_TYPE::SWORD, temp_wpn_stats, WEAPON::MERCIFUL_BLADE);
    temp_wpn.setEffect("spare");
    temp_wpn.setDescription("Infused with the life-giving tears of the goddess. Cannot reduce enemy HP below 1.");
    all_weapons[WEAPON::MERCIFUL_BLADE] = temp_wpn;
    temp_wpn_stats = {10, 0, 40, 0, 0, 0, 10, 25, 6, {1,1}, {1,2}, 0, 1000};
    temp_wpn = Weapon("Broadsword", WPN_TYPE::SWORD, temp_wpn_stats, WEAPON::BROADSWORD);
    temp_wpn.setDescription("Blade of notable girth. Heavy and strong.");
    temp_wpn_stats = {12, 0, 40, 0, 0, 0, 13, 20, 7, {1,1}, {1,2}, 0, 1000};
    all_weapons[WEAPON::BROADSWORD] = temp_wpn;
    temp_wpn = Weapon("Espadon", WPN_TYPE::SWORD, temp_wpn_stats, WEAPON::ESPADON);
    temp_wpn.setDescription("Blade of considerable girth and length. Heavier and stronger.");
    all_weapons[WEAPON::ESPADON] = temp_wpn;
    temp_wpn_stats = {9, 0, 60, 10, 5, 0, 8, 25, 10, {1,1}, {1,2}, 0, 1000};
    temp_wpn = Weapon("Oodachi", WPN_TYPE::SWORD, temp_wpn_stats, WEAPON::OODACHI);
    temp_wpn.setDescription("Long, curved sword of the eastern lands.");
    all_weapons[WEAPON::OODACHI] = temp_wpn;
    temp_wpn_stats = {7, 0, 75, 5, 0, 0, 5, 30, 8, {1,1}, {1,2}, 0, 1000};
    temp_wpn = Weapon("Uchigatana", WPN_TYPE::SWORD, temp_wpn_stats, WEAPON::UCHIGATANA);
    temp_wpn.setDescription("Curved sword in the style of the eastern lands. Very sharp.");
    all_weapons[WEAPON::UCHIGATANA] = temp_wpn;
    temp_wpn_stats = {1, 0, 50, 0, 0, 0, 1, 20, 10, {1,1}, {1,2}, 0, 1000};
    temp_wpn = Weapon("Exsangue", WPN_TYPE::SWORD, temp_wpn_stats, WEAPON::EXSANGUE);
    temp_wpn.setEffect("lifesteal");
    temp_wpn.setDescription("Drains enemies of their blood. Heals HP equal to damage dealt.");
    all_weapons[WEAPON::EXSANGUE] = temp_wpn;
    temp_wpn_stats = {14, 0, 90, 10, 0, 0, 7, 25, 14, {1,1}, {1,2}, 0, 1000};
    temp_wpn = Weapon("Hauteclaire", WPN_TYPE::SWORD, temp_wpn_stats, WEAPON::HAUTECLAIRE);
    temp_wpn.setDescription("Crystal encrusted sword, as described in the Franc legends of old.");
    all_weapons[WEAPON::HAUTECLAIRE] = temp_wpn;
    temp_wpn_stats = {16, 0, 100, 0, 0, 10, 9, 20, 12, {1,1}, {1,2}, 0, 1000};
    temp_wpn = Weapon("Secundus", WPN_TYPE::SWORD, temp_wpn_stats, WEAPON::SECUNDUS);
    temp_wpn.setDescription("The first sword made by the God. The first weapon really only the second weapon of man, after his fists.");
    all_weapons[WEAPON::SECUNDUS] = temp_wpn;
    temp_wpn_stats = {15, 0, 90, 10, 0, 0, 10, 30, 15, {1,1}, {1,2}, 0, 1000};
    temp_wpn = Weapon("Excalibur", WPN_TYPE::SWORD, temp_wpn_stats, WEAPON::EXCALIBUR);
    temp_wpn.setEffective({"Demon"});
    temp_wpn.setDescription("The king's sword. Found in a rock.");
    all_weapons[WEAPON::EXCALIBUR] = temp_wpn;
    temp_wpn_stats = {12, 0, 100, 0, 0, 0, 6, 20, 18, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Galatine", WPN_TYPE::SWORD, temp_wpn_stats, WEAPON::GALATINE);
    temp_wpn.setEffective("Armor");
    temp_wpn.setDescription("A pragmatic and honorable knight's thrusting sword. Usually used with off-hand parry daggers.");
    all_weapons[WEAPON::GALATINE] = temp_wpn;
    temp_wpn_stats = {5, 0, 50, 0, 0, 0, 7, 25, 11, {1,2}, {1,2}, 1, 1000};
    temp_wpn = Weapon("Raijintou", WPN_TYPE::SWORD, temp_wpn_stats, WEAPON::RAIJINTOU);
    temp_wpn.setDescription("The thunder god's sword. Rains lightning upon enemies at a distance.");
    all_weapons[WEAPON::RAIJINTOU] = temp_wpn;
    temp_wpn_stats = {7, 0, 45, 0, 0, 0, 1, 25, 11, {1,2}, {1,2}, 1, 1000};
    temp_wpn = Weapon("Fuujintou", WPN_TYPE::SWORD, temp_wpn_stats, WEAPON::FUUJINTOU);
    temp_wpn.setDescription("The wind god's sword. Cuts enemies with wind at a distance.");
    all_weapons[WEAPON::FUUJINTOU] = temp_wpn;
    temp_wpn_stats = {16, 0, 60, 5, 5, 0, 7, 35, 18, {1,1}, {1,2}, 0, 1000};
    temp_wpn = Weapon("Honjou Masamune", WPN_TYPE::SWORD, temp_wpn_stats, WEAPON::HONJOU_MASAMUNE);
    temp_wpn.setDescription("Lost sword made by the most skilled swordsmith of the eastern lands.");
    all_weapons[WEAPON::HONJOU_MASAMUNE] = temp_wpn;
    temp_wpn_stats = {20, 0, 30, 0, 0, 0, 20, 50, 20, {1,1}, {1,2}, 0, 1000};
    temp_wpn = Weapon("Raw Iron slab", WPN_TYPE::SWORD, temp_wpn_stats, WEAPON::RAW_IRON_SLAB); //Should be found inside a dragon skull? 
    temp_wpn.setDescription("Barely a sword. Too big, too thick, too massive, too rough. Tempered by the malevolence of countless slain demons. Effective against demons and angels.");
    temp_wpn.setEffective("DemonAngel");
    all_weapons[WEAPON::RAW_IRON_SLAB] = temp_wpn;
// Should have deeps chinks. This isn't the first time demons roamed the earth. Has deep holes in it. Must be repaired before being usable. Who is willing to repair it? 

    temp_wpn_stats = {2, 0, 60, 0, 0, 0, 4, 15, 1, {1,1}, {1,2}, 0, 1000};
    temp_wpn = Weapon("Pitchfork", WPN_TYPE::LANCE, temp_wpn_stats, WEAPON::PITCHFORK);
    temp_wpn.setDescription("Farming implement. Makeshift lance for desperate times.");
    all_weapons[WEAPON::PITCHFORK] = temp_wpn;
    temp_wpn_stats = {3, 0, 70, 0, 0, 0, 3, 30, 5, {1,1}, {2}, 0, 1000};
    temp_wpn = Weapon("Fighthing stick", WPN_TYPE::LANCE, temp_wpn_stats, WEAPON::FIGHTING_STICK);
    temp_wpn.setDescription("Simple two meter long wooden stick. Deadly in competent hands.");
    all_weapons[WEAPON::FIGHTING_STICK] = temp_wpn;
    temp_wpn_stats = {5, 0, 95, 0, 0, 0, 5, 40, 4, {1,1}, {1,2}, 0, 1000};
    temp_wpn = Weapon("Iron lance", WPN_TYPE::LANCE, temp_wpn_stats, WEAPON::IRON_LANCE);
    temp_wpn.setDescription("Sharp iron tip on a wooden stick. Standard military fare.");
    all_weapons[WEAPON::IRON_LANCE] = temp_wpn;
    temp_wpn_stats = {7, 0, 80, 30, 0, 0, 3, 30, 9, {1,1}, {1,2}, 0, 1000};
    temp_wpn = Weapon("Wrath lance", WPN_TYPE::LANCE, temp_wpn_stats, WEAPON::WRATH_LANCE);
    temp_wpn.setDescription("Increases critical hit chance.");
    all_weapons[WEAPON::WRATH_LANCE] = temp_wpn;
    temp_wpn_stats = {8, 0, 90, 0, 0, 0, 9, 35, 7, {1,1}, {1,2}, 0, 1000};
    temp_wpn = Weapon("Steel lance", WPN_TYPE::LANCE, temp_wpn_stats, WEAPON::STEEL_LANCE);
    temp_wpn.setDescription("Stronger and deadlier.");
    all_weapons[WEAPON::STEEL_LANCE] = temp_wpn;
    temp_wpn_stats = {12, 0, 85, 0, 0, 0, 12, 25, 13, {1,1}, {1,2}, 0, 1000};
    temp_wpn = Weapon("Damas lance", WPN_TYPE::LANCE, temp_wpn_stats, WEAPON::DAMAS_LANCE);
    temp_wpn.setDescription("Fancy and fatal.");
    all_weapons[WEAPON::DAMAS_LANCE] = temp_wpn;
    temp_wpn_stats = {6, 0, 60, 0, 0, 0, 15, 10, 8, {1,1}, {1,2}, 0, 1000};
    temp_wpn = Weapon("Heavy spear", WPN_TYPE::LANCE, temp_wpn_stats, WEAPON::HEAVY_SPEAR);
    temp_wpn.setEffective("Armor");
    temp_wpn.setDescription("Heavy enough to pierce armor.");
    all_weapons[WEAPON::HEAVY_SPEAR] = temp_wpn;
    temp_wpn_stats = {8, 0, 90, 0, 0, 0, 8, 10, 10, {1,1}, {1,2}, 0, 1000};
    temp_wpn = Weapon("Trident", WPN_TYPE::LANCE, temp_wpn_stats, WEAPON::TRIDENT);
    temp_wpn.setDescription("Fancy pitchfork");
    all_weapons[WEAPON::TRIDENT] = temp_wpn;
    temp_wpn_stats = {6, 0, 70, 0, 0, 0, 7, 20, 7, {1,1}, {1,2}, 0, 1000};
    temp_wpn = Weapon("Merciful lance", WPN_TYPE::LANCE, temp_wpn_stats, WEAPON::MERCIFUL_LANCE);
    temp_wpn.setDescription("Infused with the life-giving tears of the goddess. Cannot reduce enemy HP below 1.");
    all_weapons[WEAPON::MERCIFUL_LANCE] = temp_wpn;
    temp_wpn_stats = {4, 0, 40, 0, 0, 0, 6, 25, 9, {1,2}, {1}, 0, 1000};
    temp_wpn = Weapon("Javelin", WPN_TYPE::LANCE, temp_wpn_stats, WEAPON::JAVELIN);
    temp_wpn.setDescription("Simple throwing lance.");
    all_weapons[WEAPON::JAVELIN] = temp_wpn;
    temp_wpn_stats = {6, 0, 45, 0, 0, 0, 8, 23, 10, {1,2}, {1}, 0, 1000};
    temp_wpn = Weapon("Pilum", WPN_TYPE::LANCE, temp_wpn_stats, WEAPON::PILUM);
    temp_wpn.setDescription("Reliable throwing lance.");
    all_weapons[WEAPON::PILUM] = temp_wpn;
    temp_wpn_stats = {9, 0, 50, 0, 0, 0, 11, 20, 11, {1,2}, {1}, 0, 1000};
    temp_wpn = Weapon("Spear", WPN_TYPE::LANCE, temp_wpn_stats, WEAPON::SPEAR);
    temp_wpn.setDescription("Strong throwing Lance. Strikes true.");
    all_weapons[WEAPON::SPEAR] = temp_wpn;
    temp_wpn_stats = {14, 0, 60, 0, 0, 0, 9, 25, 15, {1,2}, {1,2}, 0, 1000};
    temp_wpn = Weapon("Vel", WPN_TYPE::LANCE, temp_wpn_stats, WEAPON::VEL);
    temp_wpn.setDescription("Legendary throwing lance. Said to be able to home in on the heart of your enemies.");
    all_weapons[WEAPON::VEL] = temp_wpn;
    temp_wpn_stats = {8, 0, 90, 0, 0, 0, 6, 20, 9, {1,2}, {1,2}, 1, 1000};
    temp_wpn = Weapon("Gungnir", WPN_TYPE::LANCE, temp_wpn_stats, WEAPON::GUNGNIR);
    temp_wpn.setDescription("A lightning bolt resides in its tip. Can shoot lightning at enemies at a distance.");
    all_weapons[WEAPON::GUNGNIR] = temp_wpn;
    temp_wpn_stats = {12, 0, 70, 0, 0, 0, 10, 32, 18, {1,2}, {1,2}, 0, 1000};
    temp_wpn = Weapon("Achilles", WPN_TYPE::LANCE, temp_wpn_stats, WEAPON::ACHILLES);
    temp_wpn.setEffect("1%kill");
    temp_wpn.setDescription("Legendary throwing spear named after a fearless, immortal hero. Kills instantly if hits enemy's heel (1%).");
    all_weapons[WEAPON::ACHILLES] = temp_wpn;
    temp_wpn_stats = {16, 0, 50, 0, 0, 0, 14, 24, 17, {1,1}, {1,2}, 0, 1000};
    temp_wpn = Weapon("Tonbokiri", WPN_TYPE::LANCE, temp_wpn_stats, WEAPON::TONBOKIRI);
    temp_wpn.setDescription("Cut a dragonfly that tried to land on its tip. Excessively sharp and dangerous.");
    all_weapons[WEAPON::TONBOKIRI] = temp_wpn;

    temp_wpn_stats = {8, 0, 40, 0, 0, 0, 8, 40, 4, {1,1}, {1,2}, 0, 1000};
    temp_wpn = Weapon("Iron axe", WPN_TYPE::AXE, temp_wpn_stats, WEAPON::IRON_AXE);
    temp_wpn.setDescription("Iron cutting head on a stick. Simple, easy to repair. Bandits' favorite.");
    all_weapons[WEAPON::IRON_AXE] = temp_wpn;
    temp_wpn_stats = {11, 0, 50, 0, 0, 0, 10, 35, 7, {1,1}, {1,2}, 0, 1000};
    temp_wpn = Weapon("Steel axe", WPN_TYPE::AXE, temp_wpn_stats, WEAPON::STEEL_AXE);
    temp_wpn.setDescription("Steel cutting head on a stick. Stronger. Smart bandits like it.");
    all_weapons[WEAPON::STEEL_AXE] = temp_wpn;
    temp_wpn_stats = {14, 0, 55, 0, 0, 0, 13, 25, 11, {1,1}, {1,2}, 0, 1000};
    temp_wpn = Weapon("Damas axe", WPN_TYPE::AXE, temp_wpn_stats, WEAPON::DAMAS_AXE);
    temp_wpn.setDescription("Damas cutting head on a stick. Fancy and deadly. Scorned by dumb bandits.");
    all_weapons[WEAPON::DAMAS_AXE] = temp_wpn;
    temp_wpn_stats = {14, 0, 65, 20, 0, 0, 11, 30, 10, {1,1}, {1,2}, 0, 1000};
    temp_wpn = Weapon("Wrath axe", WPN_TYPE::AXE, temp_wpn_stats, WEAPON::WRATH_AXE);
    temp_wpn.setDescription("Increases critical hit chance.");
    all_weapons[WEAPON::WRATH_AXE] = temp_wpn;
    temp_wpn_stats = {6, 0, 30, 0, 0, 0, 7, 25, 5, {1,2}, {1,2}, 0, 1000};
    temp_wpn = Weapon("Throwing axe", WPN_TYPE::AXE, temp_wpn_stats, WEAPON::THROWING_AXE);
    temp_wpn.setDescription("Smaller, balanced axe, made for throwing. Cheapest option for ranged attacks.");
    all_weapons[WEAPON::THROWING_AXE] = temp_wpn;
    temp_wpn_stats = {10, 0, 40, 0, 0, 0, 7, 25, 10, {1,2}, {1,2}, 0, 1000};
    temp_wpn = Weapon("tomahawk", WPN_TYPE::AXE, temp_wpn_stats, WEAPON::TOMAHAWK);
    temp_wpn.setDescription("Smaller, balanced axe, made for throwing. Cheapest option for ranged attacks.");
    all_weapons[WEAPON::TOMAHAWK] = temp_wpn;
    temp_wpn_stats = {7, 0, 60, 0, 0, 0, 9, 20, 3, {1,1}, {1,2}, 0, 1000};
    temp_wpn = Weapon("Pick axe", WPN_TYPE::AXE, temp_wpn_stats, WEAPON::PICK_AXE);
    temp_wpn.setDescription("Mining implement. Weapon in time of need.");
    all_weapons[WEAPON::PICK_AXE] = temp_wpn;
    temp_wpn_stats = {4, 0, 40, 0, 0, 0, 5, 25, 2, {1,1}, {1,2}, 0, 1000};
    temp_wpn = Weapon("Hoe", WPN_TYPE::AXE, temp_wpn_stats, WEAPON::HOE);
    temp_wpn.setDescription("Farming implement. Can be used as an axe if need be.");
    all_weapons[WEAPON::HOE] = temp_wpn;
    temp_wpn_stats = {9, 0, 50, 5, 0, 0, 6, 15, 1, {1,1}, {1,2}, 0, 1000};
    temp_wpn = Weapon("Club", WPN_TYPE::AXE, temp_wpn_stats, WEAPON::CLUB);
    temp_wpn.setDescription("Big and wooden. For when the old-world weapons just aren't quite old enough.");
    all_weapons[WEAPON::CLUB] = temp_wpn;
    temp_wpn_stats = {10, 0, 50, 0, 0, 0, 11, 20, 12, {1,1}, {1,2}, 0, 1000};
    temp_wpn = Weapon("Halberd", WPN_TYPE::AXE + WPN_TYPE::LANCE, temp_wpn_stats, WEAPON::HALBERD);
    temp_wpn.setEffective("Mounted");
    temp_wpn.setDescription("Polearm specially designed to deal with cavalry. Is both a lance and an axe.");
    all_weapons[WEAPON::HALBERD] = temp_wpn;
    temp_wpn_stats = {8, 0, 40, 0, 0, 0, 9, 30, 8, {1,1}, {1,2}, 0, 1000};
    temp_wpn = Weapon("Hammer", WPN_TYPE::AXE, temp_wpn_stats, WEAPON::HAMMER);
    temp_wpn.setEffective("Armor");
    temp_wpn.setDescription("Armor cannot stand the hammer's heavy crushing blows.");
    all_weapons[WEAPON::HAMMER] = temp_wpn;
    temp_wpn_stats = {12, 0, 50, 0, 0, 0, 12, 25, 11, {1,1}, {1,2}, 0, 1000};
    temp_wpn = Weapon("War pick", WPN_TYPE::AXE, temp_wpn_stats, WEAPON::WAR_PICK);
    temp_wpn.setEffective("Armor");
    temp_wpn.setDescription("In trained hands, the pick can penatrate armor.");
    all_weapons[WEAPON::WAR_PICK] = temp_wpn;
    temp_wpn_stats = {15, 0, 45, 0, 0, 0, 14, 30, 14, {1,1}, {1,2}, 0, 1000};
    temp_wpn = Weapon("Battleaxe", WPN_TYPE::AXE, temp_wpn_stats, WEAPON::BATTLEAXE);
    temp_wpn.setDescription("Double-bladed, comically oversized axe.");
    all_weapons[WEAPON::BATTLEAXE] = temp_wpn;
    temp_wpn_stats = {17, 0, 60, 0, 0, 0, 17, 20, 17, {1,1}, {1,2}, 0, 1000};
    temp_wpn = Weapon("Vidyu", WPN_TYPE::AXE, temp_wpn_stats, WEAPON::VIDYU);
    temp_wpn.setDescription("Battleaxe of the many-headed and armed gods of the east.");
    all_weapons[WEAPON::VIDYU] = temp_wpn;
    temp_wpn_stats = {19, 0, 70, 0, 0, 0, 5, 60, 20, {1,1}, {1,2}, 0, 1000};
    temp_wpn = Weapon("Hephaestus", WPN_TYPE::AXE, temp_wpn_stats, WEAPON::HEPHAESTUS);
    temp_wpn.setDescription("The god's hammer. Used to forge Secundus, the first sword. Basically a vaguely square stone fixed to a wooden handle.");
    all_weapons[WEAPON::HEPHAESTUS] = temp_wpn;

    temp_wpn_stats = {12, 0, 70, 0, 0, 0, 14, 35, 9, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Adapted Crossbow", WPN_TYPE::BOW, temp_wpn_stats, WEAPON::ADAPTED_CROSSBOW);
    temp_wpn.setDescription("Crossbow adapted to be fired, reloaded and drawn using one hand and one stump. 1H assassin only.");
    all_weapons[WEAPON::ADAPTED_CROSSBOW] = temp_wpn;
    temp_wpn_stats = {8, 0, 60, 0, 0, 0, 18, 28, 14, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Repeatable Crossbow", WPN_TYPE::BOW, temp_wpn_stats);
    temp_wpn.setDescription("Crossbow that fires many bolts every attack.");
    all_weapons[WEAPON::REPEATABLE_CROSSBOW] = temp_wpn;
    temp_wpn_stats = {10, 0, 85, 0, 0, 0, 12, 15, 7, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Crossbow", WPN_TYPE::BOW, temp_wpn_stats);
    temp_wpn.setDescription("Powerful and easier to use than a bow, although quite heavy.");
    all_weapons[WEAPON::CROSSBOW] = temp_wpn;
    temp_wpn_stats = {4, 0, 90, 0, 0, 0, 4, 35, 5, {1,2}, {1}, 0, 1000};
    temp_wpn = Weapon("Short bow", WPN_TYPE::BOW, temp_wpn_stats);
    temp_wpn.setDescription("Simple and light bow.");
    all_weapons[WEAPON::SHORT_BOW] = temp_wpn;
    temp_wpn_stats = {8, 0, 70, 0, 0, 0, 10, 25, 11, {1,3}, {1}, 0, 1000};
    temp_wpn = Weapon("Long bow", WPN_TYPE::BOW, temp_wpn_stats);
    temp_wpn.setDescription("Long and heavy bow. Has increased range.");
    all_weapons[WEAPON::LONG_BOW] = temp_wpn;
    temp_wpn_stats = {7, 0, 80, 0, 0, 0, 5, 30, 10, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Composite bow", WPN_TYPE::BOW, temp_wpn_stats);
    temp_wpn.setDescription("Bow made of laminated wood and animal horn. Very useful for horseback shooting.");
    all_weapons[WEAPON::COMPOSITE_BOW] = temp_wpn;
    temp_wpn_stats = {18, 0, 50, 0, 0, 0, 19, 20, 11, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Recurve Crossbow", WPN_TYPE::BOW, temp_wpn_stats);
    temp_wpn.setDescription("Crossbow with recurve limbs. Heavy and powerful.");
    all_weapons[WEAPON::RECURVE_CROSSBOW] = temp_wpn;
    temp_wpn_stats = {13, 0, 75, 0, 0, 0, 10, 24, 14, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Recurve bow", WPN_TYPE::BOW, temp_wpn_stats);
    temp_wpn.setDescription("Bow whose limbs curve away when unstrung. Shoots faster and deadlier arrows.");
    all_weapons[WEAPON::RECURVE_BOW] = temp_wpn;
    temp_wpn_stats = {19, 0, 69, 0, 0, 0, 9, 25, 17, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Apollo", WPN_TYPE::BOW, temp_wpn_stats);
    temp_wpn.setDescription("Bow crafted of sun rays, used by the most handsome ancient god.");
    all_weapons[WEAPON::APOLLO] = temp_wpn;
    temp_wpn_stats = {18, 0, 96, 0, 0, 0, 4, 26, 19, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Artemis", WPN_TYPE::BOW, temp_wpn_stats);
    temp_wpn.setDescription("Bow of the ancient goddess of hunting.");
    all_weapons[WEAPON::ARTEMIS] = temp_wpn;
    temp_wpn_stats = {17, 0, 100, 0, 0, 0, 7, 35, 16, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Pinaka", WPN_TYPE::BOW, temp_wpn_stats);
    temp_wpn.setDescription("Bow of the god of death.");
    all_weapons[WEAPON::PINAKA] = temp_wpn;

    temp_wpn_stats = {5, 0, 0, 10, 0, 5, 4, 45, 8, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Adapted Shield", WPN_TYPE::SHIELD, temp_wpn_stats);
    temp_wpn.setDescription("Shield adapted to be used without one\'s weak hand. Straps on the forearm. 1H assassin only.");
    all_weapons[WEAPON::ADAPTED_SHIELD] = temp_wpn;
    temp_wpn_stats = {1, 0, 0, 5, 0, 1, 2, 15, 2, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Pot lid", WPN_TYPE::SHIELD, temp_wpn_stats);
    temp_wpn.setDescription("Useful in the kitchen. For the poor militia man: life saving device.");
    all_weapons[WEAPON::POT_LID] = temp_wpn;
    temp_wpn_stats = {2, 0, 0, 8, 0, 0, 3, 20, 7, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Wooden Shield", WPN_TYPE::SHIELD, temp_wpn_stats);
    temp_wpn.setDescription("Simple wood plank with a strap. Will probably save your life.");
    all_weapons[WEAPON::WOODEN_SHIELD] = temp_wpn;
    temp_wpn_stats = {4, 0, 0, 10, 0, 4, 5, 0, 13, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Cloak", WPN_TYPE::SHIELD, temp_wpn_stats);
    temp_wpn.setDescription("The Mousquetaire\"s offhand shield in time of need.");
    all_weapons[WEAPON::CLOAK] = temp_wpn;
    temp_wpn_stats = {3, 0, 0, 9, 0, 2, 4, 25, 9, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Leather Shield", WPN_TYPE::SHIELD, temp_wpn_stats);
    temp_wpn.setDescription("Wooden plank lined with leather. Smooth and slippery. Cheap way to redirect weapons away from the body.");
    all_weapons[WEAPON::LEATHER_SHIELD] = temp_wpn;
    temp_wpn_stats = {8, 0, 0, 15, 0, 4, 4, 35, 12, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Kite Shield", WPN_TYPE::SHIELD, temp_wpn_stats);
    temp_wpn.setDescription("Large wooden shield of recognizable shape, to increase protection.");
    all_weapons[WEAPON::KITE_SHIELD] = temp_wpn;
    temp_wpn_stats = {6, 0, 0, 6, 0, 6, 6, 36, 6, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Iron Buckler", WPN_TYPE::SHIELD, temp_wpn_stats);
    temp_wpn.setDescription("Small round iron shield. Light, resistant.");
    all_weapons[WEAPON::IRON_BUCKLER] = temp_wpn;
    temp_wpn_stats = {7, 0, 0, 7, 0, 7, 7, 37, 7, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Steel Buckler", WPN_TYPE::SHIELD, temp_wpn_stats);
    temp_wpn.setDescription("Small round steel shield. Heavier and more resistant.");
    all_weapons[WEAPON::STEEL_BUCKLER] = temp_wpn;
    temp_wpn_stats = {5, 0, 0, 5, 0, 5, 9, 30, 10, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Spiked Buckler", WPN_TYPE::SHIELD, temp_wpn_stats);
    temp_wpn.setDescription("Iron buckler with a prickly spike at its center. Damages attackers upon their attacks.");
    all_weapons[WEAPON::SPIKED_BUCKLER] = temp_wpn;
    temp_wpn_stats = {11, 0, 0, 15, 0, 5, 13, 25, 7, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Scutum", WPN_TYPE::SHIELD, temp_wpn_stats);
    temp_wpn.setDescription("Very large and heavy shield.");
    all_weapons[WEAPON::SCUTUM] = temp_wpn;
    temp_wpn_stats = {12, 0, 0, 20, 0, 10, 10, 0, 14, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Master Shield", WPN_TYPE::SHIELD, temp_wpn_stats);
    temp_wpn.setDescription("Shield of the princess of time.");
    all_weapons[WEAPON::MASTER_SHIELD] = temp_wpn;
    temp_wpn_stats = {9, 0, 0, 5, 0, 200, 9, 22, 13, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Goddess's Hand", WPN_TYPE::SHIELD, temp_wpn_stats);
    temp_wpn.setDescription("Offers the protection of the goddess. Negates enemy critical hits.");
    all_weapons[WEAPON::GODDESS_HAND] = temp_wpn;
    temp_wpn_stats = {15, 0, 0, 10, 0, 2, 13, 19, 12, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Ancile", WPN_TYPE::SHIELD, temp_wpn_stats);
    temp_wpn.setDescription("Shield of the ancient god of war.");
    all_weapons[WEAPON::ANCILE] = temp_wpn;
    temp_wpn_stats = {15, 0, 0, 10, 0, 2, 13, 19, 12, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Rock plate", WPN_TYPE::SHIELD, temp_wpn_stats);
    temp_wpn.setDescription("Almost a raw boulder. The powerful and dumb demon's favorite.");
    all_weapons[WEAPON::ROCK_PLATE] = temp_wpn;
    temp_wpn_stats = {15, 0, 0, 10, 0, 2, 13, 19, 12, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Obsidian plate", WPN_TYPE::SHIELD, temp_wpn_stats);
    temp_wpn.setDescription("Rock melted by demon-breath, then recystallized into a more demon-claw friendly shape. Even harder than rock, but more brittle.");
    all_weapons[WEAPON::OBSIDIAN_PLATE] = temp_wpn;
    temp_wpn_stats = {15, 0, 0, 10, 0, 2, 13, 19, 12, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Marble plate shield", WPN_TYPE::SHIELD, temp_wpn_stats);
    temp_wpn.setDescription("Kite shield lined in an ornate layer of sculpted marble. Magical.");
    all_weapons[WEAPON::MARBLE_PLATE_SHIELD] = temp_wpn;
    temp_wpn_stats = {15, 0, 0, 10, 0, 2, 13, 19, 12, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Divine Protector", WPN_TYPE::SHIELD, temp_wpn_stats);
    temp_wpn.setDescription("Large tower shield imbued with angelic properties. Surprinsgly light and effective against magic attacks.");
    all_weapons[WEAPON::DIVINE_PROTECTOR] = temp_wpn;

    // Daggers get ridiculously low hit cause they are short and stubby!!!! Kitchen knife is the only exception.
    temp_wpn_stats = {2, 0, 10, 0, 10, 0, 5, 21, 16, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Wristblade", WPN_TYPE::OFFHAND, temp_wpn_stats);
    temp_wpn.setDescription("Blade generally strapped to the weak forearm. Used by assassins to increase crit potential.");
    all_weapons[WEAPON::WRISTBLADE] = temp_wpn;
    temp_wpn_stats = {2, 0, 10, 0, 10, 0, 5, 21, 16, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Shield Hook", WPN_TYPE::OFFHAND, temp_wpn_stats);
    temp_wpn.setDescription("Offhand weapon designed to grab on shields to drag them aside. Ignores shield bonuses.");
    temp_wpn.setEffect("ignoreshield");
    all_weapons[WEAPON::SHIELD_HOOK] = temp_wpn;
    temp_wpn_stats = {4, 0, 8, 0, 14, 0, 7, 16, 19, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Retractable Wristblade", WPN_TYPE::OFFHAND, temp_wpn_stats);
    temp_wpn.setDescription("Blade generally strapped to the weak forearm. Controlled by hand movements. Used by assasins to stealthily increase crit potential.");
    all_weapons[WEAPON::RETRACTABLE_WRISTBLADE] = temp_wpn;
    temp_wpn_stats = {1, 0, 0, 10, 0, 5, 4, 35, 7, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Main Gauche", WPN_TYPE::OFFHAND, temp_wpn_stats);
    temp_wpn.setDescription("Dagger designed to parry using the left/weak/off-hand. Increases avoir and favor.");
    all_weapons[WEAPON::MAIN_GAUCHE] = temp_wpn;
    temp_wpn_stats = {2, 0, 0, 22, 0, 4, 6, 28, 12, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Swordbreaker", WPN_TYPE::OFFHAND, temp_wpn_stats);
    temp_wpn.setDescription("Dagger with slots designed to catch swords. Increases avoid and favor. Rarely does it actually break swords...");
    all_weapons[WEAPON::SWORDBREAKER] = temp_wpn;
    temp_wpn_stats = {3, 0, 14, 0, 8, 0, 4, 20, 10, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Trident Dagger", WPN_TYPE::OFFHAND, temp_wpn_stats);
    temp_wpn.setDescription("Dagger whose blade splits into three prongs. Designed to catch opposing swords. Increases avoid and favor.");
    all_weapons[WEAPON::TRIDENT_DAGGER] = temp_wpn;
    temp_wpn_stats = {3, 0, 5, 0, 0, 0, 2, 26, 8, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Tantou", WPN_TYPE::OFFHAND, temp_wpn_stats);
    temp_wpn.setDescription("Eastern style short dagger. Very sharp and dangerous. Increases might.");
    all_weapons[WEAPON::TANTOU] = temp_wpn;
    temp_wpn_stats = {5, 0, 8, 0, 0, 0, 4, 24, 11, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Kodachi", WPN_TYPE::OFFHAND, temp_wpn_stats);
    temp_wpn.setDescription("Dagger used by the legendary assasins of the East, the Ninja. Increases might.");
    all_weapons[WEAPON::KODACHI] = temp_wpn;
    temp_wpn_stats = {4, 0, 10, 0, 0, 0, 3, 20, 10, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Dague", WPN_TYPE::OFFHAND, temp_wpn_stats);
    temp_wpn.setDescription("Messenic dagger. Simple and efficient. Beautiful engravings adorn the blade surface. ");
    all_weapons[WEAPON::DAGUE] = temp_wpn;
    temp_wpn_stats = {7, 0, 0, 0, 0, 0, 8, 10, 15, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Wakizashi", WPN_TYPE::OFFHAND, temp_wpn_stats);
    temp_wpn.setDescription("Dagger of the warriors of the East. Companion of the uchigatana. Very deadly.");
    all_weapons[WEAPON::WAKIZASHI] = temp_wpn;
    temp_wpn_stats = {2, 0, 0, 0, 0, 0, 4, 15, 7, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Baquemard", WPN_TYPE::OFFHAND, temp_wpn_stats);
    temp_wpn.setDescription("Legendary Dagger.");
    all_weapons[WEAPON::BRAQUEMARD] = temp_wpn;
    temp_wpn_stats = {0, 0, 0, 0, 0, 0, 7, 30, 10, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Misericorde", WPN_TYPE::OFFHAND, temp_wpn_stats);
    temp_wpn.setDescription("Used to delivery the Coup de grace to wounded knights. Might of this dagger increases by one for each missing 3 health.");
    all_weapons[WEAPON::MISERICORDE] = temp_wpn;
    temp_wpn_stats = {8, 0, 10, 10, 0, 2, 9, 24, 17, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Carnwennan", WPN_TYPE::OFFHAND, temp_wpn_stats);
    temp_wpn.setDescription("The king\'s dagger. Has the power to shroud its user in shadow.");
    all_weapons[WEAPON::CARNWENNAN] = temp_wpn;
    temp_wpn_stats = {7, 0, 0, 0, 0, 0, 7, 8, 5, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Flintlock", WPN_TYPE::OFFHAND, temp_wpn_stats);
    temp_wpn.setDescription("A gun!");
    all_weapons[WEAPON::FLINTLOCK] = temp_wpn;

    temp_wpn_stats = {7, 0, 0, 0, 0, 0, 7, 8, 5, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Shrunken Head", WPN_TYPE::TRINKET, temp_wpn_stats);
    temp_wpn.setDescription("Horrible. Infused with demonic energies.");
    all_weapons[WEAPON::SHRUNKEN_HEAD] = temp_wpn;
    temp_wpn_stats = {7, 0, 0, 0, 0, 0, 7, 8, 5, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Crystal", WPN_TYPE::TRINKET, temp_wpn_stats);
    temp_wpn.setDescription("");
    all_weapons[WEAPON::CRYSTAL] = temp_wpn;
    temp_wpn_stats = {7, 0, 0, 0, 0, 0, 7, 8, 5, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Human femur", WPN_TYPE::TRINKET, temp_wpn_stats);
    temp_wpn.setDescription("Taken from an ancient tomb. Used by demons to increase their magic power.");
    all_weapons[WEAPON::HUMAN_FEMUR] = temp_wpn;
    temp_wpn_stats = {7, 0, 0, 0, 0, 0, 7, 8, 5, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Void fragment", WPN_TYPE::TRINKET, temp_wpn_stats);
    temp_wpn.setDescription("");
    all_weapons[WEAPON::VOIDD] = temp_wpn;
    temp_wpn_stats = {7, 0, 0, 0, 0, 0, 7, 8, 5, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Demon fang", WPN_TYPE::TRINKET, temp_wpn_stats);
    temp_wpn.setDescription("Ripped from the mouth of a dead demon.");
    all_weapons[WEAPON::DEMON_FANG] = temp_wpn;
    temp_wpn_stats = {7, 0, 0, 0, 0, 0, 7, 8, 5, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Angel feather", WPN_TYPE::TRINKET, temp_wpn_stats);
    temp_wpn.setDescription("Beautiful and fluffy. Given by incarnates and possessed to the worthy. Increases magical ability. Unusable by demons and demon incarnates.");
    all_weapons[WEAPON::ANGEL_FEATHER] = temp_wpn;
    temp_wpn_stats = {7, 0, 0, 0, 0, 0, 7, 8, 5, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Angel hair", WPN_TYPE::TRINKET, temp_wpn_stats);
    temp_wpn.setDescription("Beautiful and fluffy. Given by incarnates and possessed to the worthy. Increases magical ability. Unusable by demons and demon incarnates.");
    all_weapons[WEAPON::ANGEL_HAIR] = temp_wpn;    
    temp_wpn_stats = {7, 0, 0, 0, 0, 0, 7, 8, 5, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Angel feather", WPN_TYPE::TRINKET, temp_wpn_stats);
    temp_wpn.setDescription("Beautiful and fluffy. Given by incarnates and possessed to the worthy. Increases magical ability. Unusable by demons and demon incarnates.");
    all_weapons[WEAPON::ANGEL_FEATHER] = temp_wpn;
    temp_wpn_stats = {7, 0, 0, 0, 0, 0, 7, 8, 5, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Angel hair", WPN_TYPE::TRINKET, temp_wpn_stats);
    temp_wpn.setDescription("Golden strands of angel hair held up by a silver thread. Increases magical ability. Unusable by demons and demon incarnates.");
    all_weapons[WEAPON::ANGEL_HAIR] = temp_wpn;
    temp_wpn_stats = {7, 0, 0, 0, 0, 0, 7, 8, 5, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Vial of light", WPN_TYPE::TRINKET, temp_wpn_stats);
    temp_wpn.setDescription("Light magically contained in glass. Shines brightest in darkness.");
    all_weapons[WEAPON::VIAL_OF_LIGHT] = temp_wpn;
    temp_wpn_stats = {7, 0, 0, 0, 0, 0, 7, 8, 5, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("Glass orb", WPN_TYPE::TRINKET, temp_wpn_stats);
    temp_wpn.setDescription("Orb used to focus magical power.");
    all_weapons[WEAPON::GLASS_ORB] = temp_wpn;
    temp_wpn_stats = {7, 0, 0, 0, 0, 0, 7, 8, 5, {1,1}, {1}, 0, 1000};
    temp_wpn = Weapon("War horn", WPN_TYPE::TRINKET, temp_wpn_stats);
    temp_wpn.setDescription("Used to call for battle. Raise's close allies' combat abilities.");
    all_weapons[WEAPON::WAR_HORN] = temp_wpn;

    temp_wpn_stats = {0, 12, 76, 0, 0, 0, 11, 25, 7, {1,2}, {1,2}, 1, 1000};
    temp_wpn = Weapon("Ball lightning", WPN_TYPE::ELEMENTAL, temp_wpn_stats);
    temp_wpn.setDescription("Lightning, compressed and explosive.");
    all_weapons[WEAPON::BALL_LIGHTNING] = temp_wpn;
    temp_wpn_stats = {0, 6, 70, 0, 0, 0, 5, 34, 7, {1,2}, {1,2}, 1, 1000};
    temp_wpn = Weapon("Icicle", WPN_TYPE::ELEMENTAL, temp_wpn_stats);
    temp_wpn.setDescription("Summons sharp and cold death spikes.");
    all_weapons[WEAPON::ICICLE] = temp_wpn;
    temp_wpn_stats = {0, 14, 50, 0, 0, 0, 13, 20, 7, {1,2}, {1,2}, 1, 1000};
    temp_wpn = Weapon("Volcano", WPN_TYPE::ELEMENTAL, temp_wpn_stats);
    temp_wpn.setDescription("Summons magma spewing mountains from under enemies' feets.");
    all_weapons[WEAPON::VOLCANO] = temp_wpn;
    temp_wpn_stats = {0, 4, 80, 0, 0, 0, 3, 40, 7, {1,2}, {1,2}, 1, 1000};
    temp_wpn = Weapon("wind_spear", WPN_TYPE::ELEMENTAL, temp_wpn_stats);
    temp_wpn.setDescription("Invisible, swift and minuscule. Can pierce armor.");
    all_weapons[WEAPON::WIND_SPEAR] = temp_wpn;
    temp_wpn_stats = {0, 6, 60, 0, 0, 0, 8, 30, 7, {1,2}, {1,2}, 1, 1000};
    temp_wpn = Weapon("Ember", WPN_TYPE::ELEMENTAL, temp_wpn_stats);
    temp_wpn.setDescription("Summon smoldering embers.");    
    all_weapons[WEAPON::EMBER] = temp_wpn;
    temp_wpn_stats = {0, 13, 40, 0, 0, 0, 11, 25, 7, {1,2}, {1,2}, 1, 1000};
    temp_wpn = Weapon("Tsunami", WPN_TYPE::ELEMENTAL, temp_wpn_stats);
    temp_wpn.setDescription("");
    all_weapons[WEAPON::TSUNAMI] = temp_wpn;
    temp_wpn_stats = {0, 18, 50, 0, 0, 0, 11, 15, 7, {1,2}, {1,2}, 1, 1000};
    temp_wpn = Weapon("The God Forge's Fire", WPN_TYPE::ELEMENTAL, temp_wpn_stats);
    temp_wpn.setDescription("The fire used to forge Secundus, contained magically. Can melt any and all metals.");
    all_weapons[WEAPON::GOD_FORGE_FIRE] = temp_wpn;
    temp_wpn_stats = {0, 11, 50, 0, 0, 0, 9, 20, 7, {1,2}, {1,2}, 1, 1000};
    temp_wpn = Weapon("Fingolfin", WPN_TYPE::ELEMENTAL, temp_wpn_stats);
    temp_wpn.setDescription("Distilled courage, strikes at darkness's heart, especially in times of despair. Effective against demons.");
    temp_wpn.setEffective("Demon");
    all_weapons[WEAPON::FINGOLFIN] = temp_wpn;
    temp_wpn_stats = {0, 6, 65, 0, 0, 0, 5, 28, 7, {1,2}, {1,2}, 1, 1000};
    temp_wpn = Weapon("Mithrandir", WPN_TYPE::ELEMENTAL, temp_wpn_stats);
    temp_wpn.setDescription("Inspires courage in the hearts of men. Effective against demons.");
    temp_wpn.setEffective("Demon");
    temp_wpn.setEffect("Demon");
    all_weapons[WEAPON::MITHRANDIR] = temp_wpn;

    temp_wpn_stats = {0, 5, 70, 0, 0, 0, 5, 60, 7, {1,2}, {1,2}, 1, 1000};
    temp_wpn = Weapon("Void", WPN_TYPE::DEMONIC, temp_wpn_stats);
    temp_wpn.setDescription("");
    all_weapons[WEAPON::VOIDD] = temp_wpn;
    temp_wpn_stats = {0, 5, 70, 0, 0, 0, 5, 60, 7, {1,2}, {1,2}, 1, 1000};
    temp_wpn = Weapon("Nether", WPN_TYPE::DEMONIC, temp_wpn_stats);
    temp_wpn.setDescription("");
    all_weapons[WEAPON::NETHER] = temp_wpn;
    temp_wpn_stats = {0, 5, 70, 0, 0, 0, 5, 60, 7, {1,2}, {1,2}, 1, 1000};
    temp_wpn = Weapon("Downfall", WPN_TYPE::DEMONIC, temp_wpn_stats);
    temp_wpn.setDescription("");
    all_weapons[WEAPON::DOWNFALL] = temp_wpn;
    temp_wpn_stats = {0, 5, 70, 0, 0, 0, 5, 60, 7, {1,2}, {1,2}, 1, 1000};
    temp_wpn = Weapon("Consume", WPN_TYPE::DEMONIC, temp_wpn_stats);
    temp_wpn.setDescription("");
    all_weapons[WEAPON::CONSUME] = temp_wpn;
    temp_wpn_stats = {0, 5, 70, 0, 0, 0, 5, 60, 7, {1,2}, {1,2}, 1, 1000};
    temp_wpn = Weapon("Putrify", WPN_TYPE::DEMONIC, temp_wpn_stats);
    temp_wpn.setDescription("Brings out the inner rot.");
    all_weapons[WEAPON::PUTRIFY] = temp_wpn;
    temp_wpn_stats = {0, 5, 70, 0, 0, 0, 5, 60, 7, {1,2}, {1,2}, 1, 1000};
    temp_wpn = Weapon("Glaurung", WPN_TYPE::DEMONIC, temp_wpn_stats);
    temp_wpn.setDescription("");
    all_weapons[WEAPON::GLAURUNG] = temp_wpn;
    temp_wpn_stats = {0, 5, 70, 0, 0, 0, 5, 60, 7, {1,2}, {1,2}, 1, 1000};
    temp_wpn = Weapon("Morgoth", WPN_TYPE::DEMONIC, temp_wpn_stats);
    temp_wpn.setDescription("Dark power, in the shape of a massive dark hammer. Makes craters wherever it strikes.");
    all_weapons[WEAPON::MORGOTH] = temp_wpn;
    temp_wpn_stats = {0, 5, 70, 0, 0, 0, 5, 60, 7, {1,2}, {1,2}, 1, 1000};
    temp_wpn = Weapon("Gothmog", WPN_TYPE::DEMONIC, temp_wpn_stats);
    temp_wpn.setDescription("Infernal whip of flame and shadows.");
    all_weapons[WEAPON::GOTHMOG] = temp_wpn;
    temp_wpn_stats = {0, 5, 70, 0, 0, 0, 5, 60, 7, {1,2}, {1,2}, 1, 1000};
    temp_wpn = Weapon("Fatalis", WPN_TYPE::DEMONIC, temp_wpn_stats);
    temp_wpn.setDescription("");
    all_weapons[WEAPON::FATALIS] = temp_wpn;
}

// void baseWeapons(){
//     printf("Making base weapons\n");
//     Weapon_stats temp_wpn;
//     Unit_stats temp_unit;
//     // Pmight, Mmight, hit, dodge, crit, favor, wgt, uses, wpnlvl, range, hand, dmg_type, cost
//     temp_wpn = {3, 0, 80, 0, 0, 0, 3, 30, 2, {1,1}, {1,2}, 0, 1000};
//     Weapon wooden_sword("Wooden sword", WPN_TYPE::SWORD, temp_wpn);
//     wooden_sword.setDescription("Practice sword, made of wood. It's crushing blows are still deadly.");
//     all_weapons["wooden_sword"] = wooden_sword;
//     temp_wpn = {1, 0, 25, 0, 0, 0, 2, 10, 1, {1,1}, {1}, 0, 1000};
//     Weapon kitchen_knife("Kitchen knife", WPN_TYPE::SWORD, temp_wpn);
//     kitchen_knife.setDescription("The poor, desperate swordman's dagger.");
//     all_weapons["kitchen_knife"] = kitchen_knife;

//     temp_wpn = {7, 0, 70, 0, 25, 0, 7, 30, 9, {1,1}, {1,2}, 0, 1000};
//     Weapon wrath_sword("Wrath sword", WPN_TYPE::SWORD, temp_wpn);
//     wrath_sword.setDescription("Increases critical hit chance.");
//     all_weapons["wrath_sword"] = wrath_sword;
//     temp_wpn = {4, 0, 90, 0, 0, 0, 4, 20, 6, {1,1}, {1}, 0, 1000};
//     Weapon fleuret("Fleuret", WPN_TYPE::SWORD, temp_wpn);
//     fleuret.setEffective("Armor");
//     fleuret.setDescription("Simple and light thrust swords. Effective against armor. Usually used with off-hand parry daggers.");
//     all_weapons["fleuret"] = fleuret;
//     temp_wpn = {8, 0, 85, 5, 0, 0, 5, 25, 8, {1,1}, {1}, 0, 1000};
//     Weapon rapiere("Rapière", WPN_TYPE::SWORD, temp_wpn);
//     rapiere.setEffective("Armor");
//     rapiere.setDescription("Strong thrust swords. Effective against armor. Usually used with off-hand parry daggers.");
//     all_weapons["rapiere"] = rapiere;
//     temp_wpn = {5, 0, 55, 0, 0, 0, 7, 30, 3, {1,1}, {1}, 0, 1000};
//     Weapon glaive("Glaive", WPN_TYPE::SWORD, temp_wpn);
//     glaive.setDescription("Old-world style short sword.");
//     all_weapons["glaive"] = glaive;
//     temp_wpn = {7, 0, 60, 10, 0, 0, 6, 33, 8, {1,1}, {1}, 0, 1000};
//     Weapon saber("Saber", WPN_TYPE::SWORD, temp_wpn);
//     saber.setDescription("Curved sword made for slashing.");
//     all_weapons["saber"] = saber;
//     temp_wpn = {8, 0, 60, 15, 0, 0, 8, 27, 10, {1,1}, {1}, 0, 1000};
//     Weapon fauchon("Fauchon", WPN_TYPE::SWORD, temp_wpn);
//     fauchon.setDescription("Curved sword made for slashing.");
//     all_weapons["fauchon"] = fauchon;
//     temp_wpn = {6, 0, 70, 0, 0, 0, 6, 45, 6, {1,1}, {1,2}, 0, 1000};
//     Weapon iron_sword("Iron sword", WPN_TYPE::SWORD, temp_wpn);
//     iron_sword.setDescription("Simple straight sword made of iron. Cheap and reliable.");
//     all_weapons["iron_sword"] = iron_sword;
//     temp_wpn = {9, 0, 60, 0, 0, 0, 9, 30, 10, {1,1}, {1,2}, 0, 1000};
//     Weapon steel_sword("Steel sword", WPN_TYPE::SWORD, temp_wpn);
//     steel_sword.setDescription("Simple straight sword made of steel. Strong and durable.");
//     all_weapons["steel_sword"] = steel_sword;
//     temp_wpn = {13, 0, 65, 0, 0, 0, 10, 25, 12, {1,1}, {1,2}, 0, 1000};
//     Weapon damas_sword("Damas sword", WPN_TYPE::SWORD, temp_wpn);
//     damas_sword.setDescription("Simple straight sword made of damascus steel. Beautifully rippled, deadly and expensive.");
//     all_weapons["damas_sword"] = damas_sword;
//     temp_wpn = {4, 0, 70, 0, 0, 10, 6, 30, 9, {1,1}, {1,2}, 0, 1000};
//     Weapon merciful_blade("Merciful blade", WPN_TYPE::SWORD, temp_wpn);
//     merciful_blade.setEffect("spare");
//     merciful_blade.setDescription("Infused with the life-giving tears of the goddess. Cannot reduce enemy HP below 1.");
//     all_weapons["merciful_blade"] = merciful_blade;
//     temp_wpn = {10, 0, 40, 0, 0, 0, 10, 25, 6, {1,1}, {1,2}, 0, 1000};
//     Weapon broadsword("Broadsword", WPN_TYPE::SWORD, temp_wpn);
//     broadsword.setDescription("Blade of notable girth. Heavy and strong.");
//     temp_wpn = {12, 0, 40, 0, 0, 0, 13, 20, 7, {1,1}, {1,2}, 0, 1000};
//     all_weapons["broadsword"] = broadsword;
//     Weapon espadon("Espadon", WPN_TYPE::SWORD, temp_wpn);
//     espadon.setDescription("Blade of considerable girth and length. Heavier and stronger.");
//     all_weapons["espadon"] = espadon;
//     temp_wpn = {9, 0, 60, 10, 5, 0, 8, 25, 10, {1,1}, {1,2}, 0, 1000};
//     Weapon oodachi("Oodachi", WPN_TYPE::SWORD, temp_wpn);
//     oodachi.setDescription("Long, curved sword of the eastern lands.");
//     all_weapons["oodachi"] = oodachi;
//     temp_wpn = {7, 0, 75, 5, 0, 0, 5, 30, 8, {1,1}, {1,2}, 0, 1000};
//     Weapon uchigatana("Uchigatana", WPN_TYPE::SWORD, temp_wpn);
//     uchigatana.setDescription("Curved sword in the style of the eastern lands. Very sharp.");
//     all_weapons["uchigatana"] = uchigatana;
//     temp_wpn = {1, 0, 50, 0, 0, 0, 1, 20, 10, {1,1}, {1,2}, 0, 1000};
//     Weapon exsangue("Exsangue", WPN_TYPE::SWORD, temp_wpn);
//     exsangue.setEffect("lifesteal");
//     exsangue.setDescription("Drains enemies of their blood. Heals HP equal to damage dealt.");
//     all_weapons["exsangue"] = exsangue;
//     temp_wpn = {14, 0, 90, 10, 0, 0, 7, 25, 14, {1,1}, {1,2}, 0, 1000};
//     Weapon Hauteclaire("Hauteclaire", WPN_TYPE::SWORD, temp_wpn);
//     Hauteclaire.setDescription("Crystal encrusted sword, as described in the Franc legends of old.");
//     all_weapons["Hauteclaire"] = Hauteclaire;
//     temp_wpn = {16, 0, 100, 0, 0, 10, 9, 20, 12, {1,1}, {1,2}, 0, 1000};
//     Weapon Secundus("Secundus", WPN_TYPE::SWORD, temp_wpn);
//     Secundus.setDescription("The first sword made by the God. The first sword is only the second weapon of man, after his fists.");
//     all_weapons["Secundus"] = Secundus;
//     temp_wpn = {15, 0, 90, 10, 0, 0, 10, 30, 15, {1,1}, {1,2}, 0, 1000};
//     Weapon Excalibur("Excalibur", WPN_TYPE::SWORD, temp_wpn);
//     Excalibur.setEffective({"Demon"});
//     Excalibur.setDescription("The king's sword. Found in a rock.");
//     all_weapons["Excalibur"] = Excalibur;
//     temp_wpn = {12, 0, 100, 0, 0, 0, 6, 20, 18, {1,1}, {1}, 0, 1000};
//     Weapon Galatine("Galatine", WPN_TYPE::SWORD, temp_wpn);
//     Galatine.setEffective("Armor");
//     Galatine.setDescription("A pragmatic and honorable knight's thrusting sword. Usually used with off-hand parry daggers.");
//     all_weapons["Galatine"] = Galatine;
//     temp_wpn = {5, 0, 50, 0, 0, 0, 7, 25, 11, {1,2}, {1,2}, 1, 1000};
//     Weapon Raijintou("Raijintou", WPN_TYPE::SWORD, temp_wpn);
//     Raijintou.setDescription("The thunder god's sword. Rains lightning upon enemies at a distance.");
//     all_weapons["Raijintou"] = Raijintou;
//     temp_wpn = {7, 0, 45, 0, 0, 0, 1, 25, 11, {1,2}, {1,2}, 1, 1000};
//     Weapon Fuujintou("Fuujintou", WPN_TYPE::SWORD, temp_wpn);
//     Fuujintou.setDescription("The wind god's sword. Cuts enemies with wind at a distance.");
//     all_weapons["Fuujintou"] = Fuujintou;
//     temp_wpn = {16, 0, 60, 5, 5, 0, 7, 35, 18, {1,1}, {1,2}, 0, 1000};
//     Weapon Honjou_Masamune("Honjou Masamune", WPN_TYPE::SWORD, temp_wpn);
//     Honjou_Masamune.setDescription("Lost sword made by the most skilled swordsmith of the eastern lands.");
//     all_weapons["Honjou_Masamune"] = Honjou_Masamune;
//     temp_wpn = {20, 0, 30, 0, 0, 0, 20, 50, 20, {1,1}, {1,2}, 0, 1000};
//     Weapon Raw_iron_slab("Raw Iron slab", WPN_TYPE::SWORD, temp_wpn); //Should be found inside a dragon skull? 
//     Raw_iron_slab.setDescription("Barely a sword. Too big, too thick, too massive, too rough. Tempered by the malevolence of countless slain demons. Effective against demons and angels.");
//     Raw_iron_slab.setEffective("DemonAngel");
//     all_weapons["Raw_iron_slab"] = Raw_iron_slab;
// // Should have deeps chinks. This isn't the first time demons roamed the earth. Has deep holes in it. Must be repaired before being usable. Who is willing to repair it? 

//     temp_wpn = {2, 0, 60, 0, 0, 0, 4, 15, 1, {1,1}, {1,2}, 0, 1000};
//     Weapon pitchfork("Pitchfork", WPN_TYPE::LANCE, temp_wpn);
//     pitchfork.setDescription("Farming implement. Makeshift lance for desperate times.");
//     all_weapons["pitchfork"] = pitchfork;
//     temp_wpn = {3, 0, 70, 0, 0, 0, 3, 30, 5, {1,1}, {2}, 0, 1000};
//     Weapon fighthing_stick("Fighthing stick", WPN_TYPE::LANCE, temp_wpn);
//     fighthing_stick.setDescription("Simple two meter long wooden stick. Deadly in competent hands.");
//     all_weapons["fighthing_stick"] = fighthing_stick;
//     temp_wpn = {5, 0, 95, 0, 0, 0, 5, 40, 4, {1,1}, {1,2}, 0, 1000};
//     Weapon iron_lance("Iron lance", WPN_TYPE::LANCE, temp_wpn);
//     iron_lance.setDescription("Sharp iron tip on a wooden stick. Standard military fare.");
//     all_weapons["iron_lance"] = iron_lance;
//     temp_wpn = {7, 0, 80, 30, 0, 0, 3, 30, 9, {1,1}, {1,2}, 0, 1000};
//     Weapon wrath_lance("Wrath lance", WPN_TYPE::LANCE, temp_wpn);
//     wrath_lance.setDescription("Increases critical hit chance.");
//     all_weapons["wrath_lance"] = wrath_lance;
//     temp_wpn = {8, 0, 90, 0, 0, 0, 9, 35, 7, {1,1}, {1,2}, 0, 1000};
//     Weapon steel_lance("Steel lance", WPN_TYPE::LANCE, temp_wpn);
//     steel_lance.setDescription("Stronger and deadlier.");
//     all_weapons["steel_lance"] = steel_lance;
//     temp_wpn = {12, 0, 85, 0, 0, 0, 12, 25, 13, {1,1}, {1,2}, 0, 1000};
//     Weapon damas_lance("Damas lance", WPN_TYPE::LANCE, temp_wpn);
//     damas_lance.setDescription("Fancy and fatal.");
//     all_weapons["damas_lance"] = damas_lance;
//     temp_wpn = {6, 0, 60, 0, 0, 0, 15, 10, 8, {1,1}, {1,2}, 0, 1000};
//     Weapon heavy_spear("Heavy spear", WPN_TYPE::LANCE, temp_wpn);
//     heavy_spear.setEffective("Armor");
//     heavy_spear.setDescription("Heavy enough to pierce armor.");
//     all_weapons["heavy_spear"] = heavy_spear;
//     temp_wpn = {8, 0, 90, 0, 0, 0, 8, 10, 10, {1,1}, {1,2}, 0, 1000};
//     Weapon trident("Trident", WPN_TYPE::LANCE, temp_wpn);
//     trident.setDescription("Fancy pitchfork");
//     all_weapons["trident"] = trident;
//     temp_wpn = {6, 0, 70, 0, 0, 0, 7, 20, 7, {1,1}, {1,2}, 0, 1000};
//     Weapon merciful_lance("Merciful lance", WPN_TYPE::LANCE, temp_wpn);
//     merciful_lance.setDescription("Infused with the life-giving tears of the goddess. Cannot reduce enemy HP below 1.");
//     all_weapons["merciful_lance"] = merciful_lance;
//     temp_wpn = {4, 0, 40, 0, 0, 0, 6, 25, 9, {1,2}, {1}, 0, 1000};
//     Weapon javelin("Javelin", WPN_TYPE::LANCE, temp_wpn);
//     javelin.setDescription("Simple throwing lance.");
//     all_weapons["javelin"] = javelin;
//     temp_wpn = {6, 0, 45, 0, 0, 0, 8, 23, 10, {1,2}, {1}, 0, 1000};
//     Weapon pilum("Pilum", WPN_TYPE::LANCE, temp_wpn);
//     pilum.setDescription("Reliable throwing lance.");
//     all_weapons["pilum"] = pilum;
//     temp_wpn = {9, 0, 50, 0, 0, 0, 11, 20, 11, {1,2}, {1}, 0, 1000};
//     Weapon spear("Spear", WPN_TYPE::LANCE, temp_wpn);
//     spear.setDescription("Strong throwing Lance. Strikes true.");
//     all_weapons["spear"] = spear;
//     temp_wpn = {14, 0, 60, 0, 0, 0, 9, 25, 15, {1,2}, {1,2}, 0, 1000};
//     Weapon Vel("Vel", WPN_TYPE::LANCE, temp_wpn);
//     Vel.setDescription("Legendary throwing lance. Said to be able to home in on the heart of your enemies.");
//     all_weapons["Vel"] = Vel;
//     temp_wpn = {8, 0, 90, 0, 0, 0, 6, 20, 9, {1,2}, {1,2}, 1, 1000};
//     Weapon Gungnir("Gungnir", WPN_TYPE::LANCE, temp_wpn);
//     Gungnir.setDescription("A lightning bolt resides in its tip. Can shoot lightning at enemies at a distance.");
//     all_weapons["Gungnir"] = Gungnir;
//     temp_wpn = {12, 0, 70, 0, 0, 0, 10, 32, 18, {1,2}, {1,2}, 0, 1000};
//     Weapon Achilles("Achilles", WPN_TYPE::LANCE, temp_wpn);
//     Achilles.setEffect("1%kill");
//     Achilles.setDescription("Legendary throwing spear named after a fearless, immortal hero. Kills instantly if hits enemy's heel (1%).");
//     all_weapons["Achilles"] = Achilles;
//     temp_wpn = {16, 0, 50, 0, 0, 0, 14, 24, 17, {1,1}, {1,2}, 0, 1000};
//     Weapon Tonbokiri("Tonbokiri", WPN_TYPE::LANCE, temp_wpn);
//     Tonbokiri.setDescription("Cut a dragonfly that tried to land on its tip. Excessively sharp and dangerous.");
//     all_weapons["Tonbokiri"] = Tonbokiri;

//     temp_wpn = {8, 0, 40, 0, 0, 0, 8, 40, 4, {1,1}, {1,2}, 0, 1000};
//     Weapon iron_WPN_TYPE::AXE("Iron WPN_TYPE::AXE", WPN_TYPE::AXE, temp_wpn);
//     iron_WPN_TYPE::AXE.setDescription("Iron cutting head on a stick. Simple, easy to repair. Bandits' favorite.");
//     all_weapons["iron_WPN_TYPE::AXE"] = iron_WPN_TYPE::AXE;
//     temp_wpn = {11, 0, 50, 0, 0, 0, 10, 35, 7, {1,1}, {1,2}, 0, 1000};
//     Weapon steel_WPN_TYPE::AXE("Steel WPN_TYPE::AXE", WPN_TYPE::AXE, temp_wpn);
//     steel_WPN_TYPE::AXE.setDescription("Steel cutting head on a stick. Stronger. Smart bandits like it.");
//     all_weapons["steel_WPN_TYPE::AXE"] = steel_WPN_TYPE::AXE;
//     temp_wpn = {14, 0, 55, 0, 0, 0, 13, 25, 11, {1,1}, {1,2}, 0, 1000};
//     Weapon damas_WPN_TYPE::AXE("Damas WPN_TYPE::AXE", WPN_TYPE::AXE, temp_wpn);
//     damas_WPN_TYPE::AXE.setDescription("Damas cutting head on a stick. Fancy and deadly. Scorned by dumb bandits.");
//     all_weapons["damas_WPN_TYPE::AXE"] = damas_WPN_TYPE::AXE;
//     temp_wpn = {14, 0, 65, 20, 0, 0, 11, 30, 10, {1,1}, {1,2}, 0, 1000};
//     Weapon wrath_WPN_TYPE::AXE("Wrath WPN_TYPE::AXE", WPN_TYPE::AXE, temp_wpn);
//     wrath_WPN_TYPE::AXE.setDescription("Increases critical hit chance.");
//     all_weapons["wrath_WPN_TYPE::AXE"] = wrath_WPN_TYPE::AXE;
//     temp_wpn = {6, 0, 30, 0, 0, 0, 7, 25, 5, {1,2}, {1,2}, 0, 1000};
//     Weapon throwing_WPN_TYPE::AXE("Throwing WPN_TYPE::AXE", WPN_TYPE::AXE, temp_wpn);
//     throwing_WPN_TYPE::AXE.setDescription("Smaller, balanced WPN_TYPE::AXE, made for throwing. Cheapest option for ranged attacks.");
//     all_weapons["throwing_WPN_TYPE::AXE"] = throwing_WPN_TYPE::AXE;
//     temp_wpn = {10, 0, 40, 0, 0, 0, 7, 25, 10, {1,2}, {1,2}, 0, 1000};
//     Weapon tomahawk("tomahawk", WPN_TYPE::AXE, temp_wpn);
//     tomahawk.setDescription("Smaller, balanced WPN_TYPE::AXE, made for throwing. Cheapest option for ranged attacks.");
//     all_weapons["tomahawk"] = tomahawk;
//     temp_wpn = {7, 0, 60, 0, 0, 0, 9, 20, 3, {1,1}, {1,2}, 0, 1000};
//     Weapon pick_WPN_TYPE::AXE("Pick axe", WPN_TYPE::AXE, temp_wpn);
//     pick_WPN_TYPE::AXE.setDescription("Mining implement. Weapon in time of need.");
//     all_weapons["pick_WPN_TYPE::AXE"] = pick_WPN_TYPE::AXE;
//     temp_wpn = {4, 0, 40, 0, 0, 0, 5, 25, 2, {1,1}, {1,2}, 0, 1000};
//     Weapon hoe("Hoe", WPN_TYPE::AXE, temp_wpn);
//     hoe.setDescription("Farming implement. Can be used as an WPN_TYPE::AXE if need be.");
//     all_weapons["hoe"] = hoe;
//     temp_wpn = {9, 0, 50, 5, 0, 0, 6, 15, 1, {1,1}, {1,2}, 0, 1000};
//     Weapon club("Club", WPN_TYPE::AXE, temp_wpn);
//     club.setDescription("Big and wooden. For when the old-world weapons just aren't quite old enough.");
//     all_weapons["club"] = club;
//     temp_wpn = {10, 0, 50, 0, 0, 0, 11, 20, 12, {1,1}, {1,2}, 0, 1000};
//     Weapon halberd("Halberd", WPN_TYPE::AXE + WPN_TYPE::LANCE, temp_wpn);
//     halberd.setEffective("Mounted");
//     halberd.setDescription("Polearm specially designed to deal with cavalry. Is both a lance and an WPN_TYPE::AXE.");
//     all_weapons["halberd"] = halberd;
//     temp_wpn = {8, 0, 40, 0, 0, 0, 9, 30, 8, {1,1}, {1,2}, 0, 1000};
//     Weapon hammer("Hammer", WPN_TYPE::AXE, temp_wpn);
//     hammer.setEffective("Armor");
//     hammer.setDescription("Armor cannot stand the hammer's heavy crushing blows.");
//     all_weapons["hammer"] = hammer;
//     temp_wpn = {12, 0, 50, 0, 0, 0, 12, 25, 11, {1,1}, {1,2}, 0, 1000};
//     Weapon war_pick("War pick", WPN_TYPE::AXE, temp_wpn);
//     war_pick.setEffective("Armor");
//     war_pick.setDescription("In trained hands, the pick can penatrate armor.");
//     all_weapons["war_pick"] = war_pick;
//     temp_wpn = {15, 0, 45, 0, 0, 0, 14, 30, 14, {1,1}, {1,2}, 0, 1000};
//     Weapon battleWPN_TYPE::AXE("BattleWPN_TYPE::AXE", WPN_TYPE::AXE, temp_wpn);
//     battleWPN_TYPE::AXE.setDescription("Double-bladed, comically oversized WPN_TYPE::AXE.");
//     all_weapons["battleWPN_TYPE::AXE"] = battleWPN_TYPE::AXE;
//     temp_wpn = {17, 0, 60, 0, 0, 0, 17, 20, 17, {1,1}, {1,2}, 0, 1000};
//     Weapon Vidyu("Vidyu", WPN_TYPE::AXE, temp_wpn);
//     Vidyu.setDescription("BattleWPN_TYPE::AXE of the gods of the east.");
//     all_weapons["Vidyu"] = Vidyu;
//     temp_wpn = {19, 0, 70, 0, 0, 0, 5, 60, 20, {1,1}, {1,2}, 0, 1000};
//     Weapon Hephaestus("Hephaestus", WPN_TYPE::AXE, temp_wpn);
//     Hephaestus.setDescription("The god's hammer. Used to forge Secundus, the first sword.");
//     all_weapons["Hephaestus"] = Hephaestus;

//     temp_wpn = {12, 0, 70, 0, 0, 0, 14, 35, 9, {1,1}, {1}, 0, 1000};
//     Weapon adapted_crossbow("Adapted Crossbow", WPN_TYPE::BOW, temp_wpn);
//     adapted_crossbow.setDescription("Crossbow adapted to be fired, reloaded and drawn using one hand and one stump. 1H assassin only.");
//     all_weapons["adapted_crossbow"] = adapted_crossbow;
//     temp_wpn = {8, 0, 60, 0, 0, 0, 18, 28, 14, {1,1}, {1}, 0, 1000};
//     Weapon repeatable_crossbow("Repeatable Crossbow", WPN_TYPE::BOW, temp_wpn);
//     repeatable_crossbow.setDescription("Crossbow that fires many bolts every attack.");
//     all_weapons["repeatable_crossbow"] = repeatable_crossbow;
//     temp_wpn = {10, 0, 85, 0, 0, 0, 12, 15, 7, {1,1}, {1}, 0, 1000};
//     Weapon crossbow("Crossbow", WPN_TYPE::BOW, temp_wpn);
//     crossbow.setDescription("Powerful and easier to use than a bow, although quite heavy.");
//     all_weapons["crossbow"] = crossbow;
//     temp_wpn = {4, 0, 90, 0, 0, 0, 4, 35, 5, {1,2}, {1}, 0, 1000};
//     Weapon short_bow("Short bow", WPN_TYPE::BOW, temp_wpn);
//     short_bow.setDescription("Simple and light bow.");
//     all_weapons["short_bow"] = short_bow;
//     temp_wpn = {8, 0, 70, 0, 0, 0, 10, 25, 11, {1,3}, {1}, 0, 1000};
//     Weapon long_bow("Long bow", WPN_TYPE::BOW, temp_wpn);
//     long_bow.setDescription("Long and heavy bow. Has increased range.");
//     all_weapons["long_bow"] = long_bow;
//     temp_wpn = {7, 0, 80, 0, 0, 0, 5, 30, 10, {1,1}, {1}, 0, 1000};
//     Weapon composite_bow("Composite bow", WPN_TYPE::BOW, temp_wpn);
//     composite_bow.setDescription("Bow made of laminated wood and animal horn. Very useful for horseback shooting.");
//     all_weapons["composite_bow"] = composite_bow;
//     temp_wpn = {18, 0, 50, 0, 0, 0, 19, 20, 11, {1,1}, {1}, 0, 1000};
//     Weapon recurve_crossbow("Recurve Crossbow", WPN_TYPE::BOW, temp_wpn);
//     recurve_crossbow.setDescription("Crossbow with recurve limbs. Heavy and powerful.");
//     all_weapons["recurve_crossbow"] = recurve_crossbow;
//     temp_wpn = {13, 0, 75, 0, 0, 0, 10, 24, 14, {1,1}, {1}, 0, 1000};
//     Weapon recurve_bow("Recurve bow", WPN_TYPE::BOW, temp_wpn);
//     recurve_bow.setDescription("Bow whose limbs curve away when unstrung. Shoots faster and deadlier arrows.");
//     all_weapons["recurve_bow"] = recurve_bow;    
//     temp_wpn = {19, 0, 69, 0, 0, 0, 9, 25, 17, {1,1}, {1}, 0, 1000};
//     Weapon Apollo("Apollo", WPN_TYPE::BOW, temp_wpn);
//     Apollo.setDescription("Bow crafted of sun rays, used by the most handsome ancient god.");
//     all_weapons["Apollo"] = Apollo;
//     temp_wpn = {18, 0, 96, 0, 0, 0, 4, 26, 19, {1,1}, {1}, 0, 1000};
//     Weapon Artemis("Artemis", WPN_TYPE::BOW, temp_wpn);
//     Artemis.setDescription("Bow of the ancient goddess of hunting.");
//     all_weapons["Artemis"] = Artemis;    
//     temp_wpn = {17, 0, 100, 0, 0, 0, 7, 35, 16, {1,1}, {1}, 0, 1000};
//     Weapon Pinaka("Pinaka", WPN_TYPE::BOW, temp_wpn);
//     Pinaka.setDescription("Bow of the god of death.");
//     all_weapons["Pinaka"] = Pinaka;

//     temp_wpn = {5, 0, 0, 10, 0, 5, 4, 45, 8, {1,1}, {1}, 0, 1000};
//     Weapon adapted_shield("Adapted Shield", WPN_TYPE::SHIELD, temp_wpn);
//     adapted_shield.setDescription("Shield adapted to be used without one\'s weak hand. Straps on the forearm. 1H assassin only.");
//     all_weapons["adapted_shield"] = adapted_shield;
//     temp_wpn = {1, 0, 0, 5, 0, 1, 2, 15, 2, {1,1}, {1}, 0, 1000};
//     Weapon pot_lid("Pot lid", WPN_TYPE::SHIELD, temp_wpn);
//     pot_lid.setDescription("Useful in the kitchen. For the poor militia man: life saving device.");
//     all_weapons["pot_lid"] = pot_lid;
//     temp_wpn = {2, 0, 0, 8, 0, 0, 3, 20, 7, {1,1}, {1}, 0, 1000};
//     Weapon wooden_shield("Wooden Shield", WPN_TYPE::SHIELD, temp_wpn);
//     pot_lid.setDescription("Simple wood plank with a strap. Will probably save your life.");
//     all_weapons["wooden_shield"] = wooden_shield;
//     temp_wpn = {4, 0, 0, 10, 0, 4, 5, 0, 13, {1,1}, {1}, 0, 1000};
//     Weapon cloak("Cloak", WPN_TYPE::SHIELD, temp_wpn);
//     cloak.setDescription("The Mousquetaire\"s offhand shield in time of need.");
//     all_weapons["cloak"] = cloak;
//     temp_wpn = {3, 0, 0, 9, 0, 2, 4, 25, 9, {1,1}, {1}, 0, 1000};
//     Weapon leather_shield("Leather Shield", WPN_TYPE::SHIELD, temp_wpn);
//     leather_shield.setDescription("Wooden plank lined with leather. Smooth and slippery. Cheap way to redirect weapons away from the body.");
//     all_weapons["leather_shield"] = leather_shield;
//     temp_wpn = {8, 0, 0, 15, 0, 4, 4, 35, 12, {1,1}, {1}, 0, 1000};
//     Weapon kite_shield("Kite Shield", WPN_TYPE::SHIELD, temp_wpn);
//     kite_shield.setDescription("Large wooden shield of recognizable shape, to increase protection.");
//     all_weapons["kite_shield"] = kite_shield;    
//     temp_wpn = {6, 0, 0, 6, 0, 6, 6, 36, 6, {1,1}, {1}, 0, 1000};
//     Weapon iron_buckler("Iron Buckler", WPN_TYPE::SHIELD, temp_wpn);
//     iron_buckler.setDescription("Small round iron shield. Light, resistant.");
//     all_weapons["iron_buckler"] = iron_buckler;
//     temp_wpn = {7, 0, 0, 7, 0, 7, 7, 37, 7, {1,1}, {1}, 0, 1000};
//     Weapon steel_buckler("Steel Buckler", WPN_TYPE::SHIELD, temp_wpn);
//     steel_buckler.setDescription("Small round steel shield. Heavier and more resistant.");
//     all_weapons["steel_buckler"] = steel_buckler;
//     temp_wpn = {5, 0, 0, 5, 0, 5, 9, 30, 10, {1,1}, {1}, 0, 1000};
//     Weapon spiked_buckler("Spiked Buckler", WPN_TYPE::SHIELD, temp_wpn);
//     spiked_buckler.setDescription("Iron buckler with a prickly spike at its center. Damages attackers upon their attacks.");
//     all_weapons["spiked_buckler"] = spiked_buckler;    
//     temp_wpn = {11, 0, 0, 15, 0, 5, 13, 25, 7, {1,1}, {1}, 0, 1000};
//     Weapon tower_shield("Tower Shield", WPN_TYPE::SHIELD, temp_wpn);
//     tower_shield.setDescription("Very large and heavy shield.");
//     all_weapons["tower_shield"] = tower_shield;    
//     temp_wpn = {12, 0, 0, 20, 0, 10, 10, 0, 14, {1,1}, {1}, 0, 1000};
//     Weapon Master_shield("Master Shield", WPN_TYPE::SHIELD, temp_wpn);
//     Master_shield.setDescription("Shield of the princess of time.");
//     all_weapons["Master_shield"] = Master_shield;
//     temp_wpn = {9, 0, 0, 5, 0, 200, 9, 22, 13, {1,1}, {1}, 0, 1000};
//     Weapon Goddess_hand("Goddess's Hand", WPN_TYPE::SHIELD, temp_wpn);
//     Goddess_hand.setDescription("Offers the protection of the goddess. Negates enemy critical hits.");
//     all_weapons["Goddess_hand"] = Goddess_hand;
//     temp_wpn = {15, 0, 0, 10, 0, 2, 13, 19, 12, {1,1}, {1}, 0, 1000};
//     Weapon Ancile("Ancile", WPN_TYPE::SHIELD, temp_wpn);
//     Ancile.setDescription("Shield of the ancient god of war.");
//     all_weapons["Ancile"] = Ancile;
//     temp_wpn = {15, 0, 0, 10, 0, 2, 13, 19, 12, {1,1}, {1}, 0, 1000};
//     Weapon rock_plate("Rock plate", WPN_TYPE::SHIELD, temp_wpn);
//     Ancile.setDescription("Almost a raw boulder. The powerful and dumb demon's favorite.");
//     all_weapons["rock_plate"] = rock_plate;    
//     temp_wpn = {15, 0, 0, 10, 0, 2, 13, 19, 12, {1,1}, {1}, 0, 1000};
//     Weapon obsidian_plate("Obsidian plate", WPN_TYPE::SHIELD, temp_wpn);
//     Ancile.setDescription("Rock melted by demon-breath, then recystallized into a more demon-claw friendly shape. Even harder than rock, but more brittle.");
//     all_weapons["obsidian_plate"] = obsidian_plate;
//     temp_wpn = {15, 0, 0, 10, 0, 2, 13, 19, 12, {1,1}, {1}, 0, 1000};
//     Weapon marble_plate_shield("Marble plate shield", WPN_TYPE::SHIELD, temp_wpn);
//     Ancile.setDescription("Kite shield lined in an ornate layer of sculpted marble. Magical.");
//     all_weapons["marble_plate_shield"] = marble_plate_shield;
//     temp_wpn = {15, 0, 0, 10, 0, 2, 13, 19, 12, {1,1}, {1}, 0, 1000};
//     Weapon divine_protector("Divine Protector", WPN_TYPE::SHIELD, temp_wpn);
//     Ancile.setDescription("Large tower shield imbued with angelic properties. Surprinsgly light and effective against magic attacks.");
//     all_weapons["divine_protector"] = divine_protector;

//     // Daggers get ridiculously low hit cause they are short and stubby!!!! Kitchen knife is the only exception.
//     temp_wpn = {2, 0, 10, 0, 10, 0, 5, 21, 16, {1,1}, {1}, 0, 1000};
//     Weapon wristblade("Wristblade", WPN_TYPE::OFFHAND, temp_wpn);
//     wristblade.setDescription("Blade generally strapped to the weak forearm. Used by assassins to increase crit potential.");
//     all_weapons["wristblade"] = wristblade;    
//     temp_wpn = {2, 0, 10, 0, 10, 0, 5, 21, 16, {1,1}, {1}, 0, 1000};
//     Weapon shieldhook("Shield Hook", WPN_TYPE::OFFHAND, temp_wpn);
//     wristblade.setDescription("Offhand weapon designed to grab on shields to drag them aside. Ignores shield bonuses.");
//     wristblade.setEffect("ignoreshield");
//     all_weapons["shieldhook"] = shieldhook;
//     temp_wpn = {4, 0, 8, 0, 14, 0, 7, 16, 19, {1,1}, {1}, 0, 1000};
//     Weapon retractable_wristblade("Retractable Wristblade", WPN_TYPE::OFFHAND, temp_wpn);
//     retractable_wristblade.setDescription("Blade generally strapped to the weak forearm. Controlled by hand movements. Used by assasins to stealthily increase crit potential.");
//     all_weapons["retractable_wristblade"] = retractable_wristblade;
//     temp_wpn = {1, 0, 0, 10, 0, 5, 4, 35, 7, {1,1}, {1}, 0, 1000};
//     Weapon main_gauche("Main Gauche", WPN_TYPE::OFFHAND, temp_wpn);
//     main_gauche.setDescription("Dagger designed to parry using the left/weak/off-hand. Increases avoir and favor.");
//     all_weapons["main_gauche"] = main_gauche;
//     temp_wpn = {2, 0, 0, 22, 0, 4, 6, 28, 12, {1,1}, {1}, 0, 1000};
//     Weapon swordbreaker("Swordbreaker", WPN_TYPE::OFFHAND, temp_wpn);
//     swordbreaker.setDescription("Dagger with slots designed to catch swords. Increases avoid and favor. Rarely does it actually break swords...");
//     all_weapons["swordbreaker"] = swordbreaker;
//     temp_wpn = {3, 0, 14, 0, 8, 0, 4, 20, 10, {1,1}, {1}, 0, 1000};
//     Weapon trident_dagger("Trident Dagger", WPN_TYPE::OFFHAND, temp_wpn);
//     trident_dagger.setDescription("Dagger whose blade splits into three prongs. Designed to catch opposing swords. Increases avoid and favor.");
//     all_weapons["trident_dagger"] = trident_dagger;
//     temp_wpn = {3, 0, 5, 0, 0, 0, 2, 26, 8, {1,1}, {1}, 0, 1000};
//     Weapon tantou("Tantou", WPN_TYPE::OFFHAND, temp_wpn);
//     tantou.setDescription("Eastern style short dagger. Very sharp and dangerous. Increases might.");
//     all_weapons["tantou"] = tantou;
//     temp_wpn = {5, 0, 8, 0, 0, 0, 4, 24, 11, {1,1}, {1}, 0, 1000};
//     Weapon  kodachi("Kodachi", WPN_TYPE::OFFHAND, temp_wpn);
//     kodachi.setDescription("Dagger used by the legendary assasins of the East, the Ninja. Increases might.");
//     all_weapons["kodachi"] = kodachi;
//         temp_wpn = {4, 0, 10, 0, 0, 0, 3, 20, 10, {1,1}, {1}, 0, 1000};
//     Weapon  dague("Dague", WPN_TYPE::OFFHAND, temp_wpn);
//     dague.setDescription("Messenic dagger. Simple and efficient. Beautiful engravings adorn the blade surface. ");
//     all_weapons["dague"] = dague;
//     temp_wpn = {7, 0, 0, 0, 0, 0, 8, 10, 15, {1,1}, {1}, 0, 1000};
//     Weapon wakizashi("Wakizashi", WPN_TYPE::OFFHAND, temp_wpn);
//     wakizashi.setDescription("Dagger of the warriors of the East. Companion of the uchigatana. Very deadly.");
//     all_weapons["wakizashi"] = wakizashi;    
//     temp_wpn = {2, 0, 0, 0, 0, 0, 4, 15, 7, {1,1}, {1}, 0, 1000};
//     Weapon Baquemard("Baquemard", WPN_TYPE::OFFHAND, temp_wpn);
//     Baquemard.setDescription("Legendary Dagger.");
//     all_weapons["Baquemard"] = Baquemard;    
//     temp_wpn = {0, 0, 0, 0, 0, 0, 7, 30, 10, {1,1}, {1}, 0, 1000};
//     Weapon misericorde("Misericorde", WPN_TYPE::OFFHAND, temp_wpn);
//     misericorde.setDescription("Used to delivery the Coup de grace to wounded knights. Might of this dagger increases by one for each missing 3 health.");
//     all_weapons["misericorde"] = misericorde;    
//     temp_wpn = {8, 0, 10, 10, 0, 2, 9, 24, 17, {1,1}, {1}, 0, 1000};
//     Weapon Carnwennan("Carnwennan", WPN_TYPE::OFFHAND, temp_wpn);
//     Carnwennan.setDescription("The king\'s dagger. Has the power to shroud its user in shadow.");
//     all_weapons["Carnwennan"] = Carnwennan;    
//     temp_wpn = {7, 0, 0, 0, 0, 0, 7, 8, 5, {1,1}, {1}, 0, 1000};
//     Weapon flintlock("Flintlock", WPN_TYPE::OFFHAND, temp_wpn);
//     flintlock.setDescription("A gun!");
//     all_weapons["flintlock"] = flintlock;

//     temp_wpn = {7, 0, 0, 0, 0, 0, 7, 8, 5, {1,1}, {1}, 0, 1000};
//     Weapon shrunken_head("Shrunken Head", WPN_TYPE::TRINKET, temp_wpn);
//     shrunken_head.setDescription("Horrible. Infused with demonic energies.");
//     all_weapons["shrunken_head"] = shrunken_head;        
//     temp_wpn = {7, 0, 0, 0, 0, 0, 7, 8, 5, {1,1}, {1}, 0, 1000};
//     Weapon crystal("Crystal", WPN_TYPE::TRINKET, temp_wpn);
//     crystal.setDescription("");
//     all_weapons["crystal"] = crystal;      
//     temp_wpn = {7, 0, 0, 0, 0, 0, 7, 8, 5, {1,1}, {1}, 0, 1000};
//     Weapon human_femur("Human femur", WPN_TYPE::TRINKET, temp_wpn);
//     human_femur.setDescription("Taken from an ancient tomb. Used by demons to increase their magic power.");
//     all_weapons["human_femur"] = human_femur;        
//     temp_wpn = {7, 0, 0, 0, 0, 0, 7, 8, 5, {1,1}, {1}, 0, 1000};
//     Weapon void_fragment("Void fragment", WPN_TYPE::TRINKET, temp_wpn);
//     void_fragment.setDescription("");
//     all_weapons["void_fragment"] = void_fragment;
//     temp_wpn = {7, 0, 0, 0, 0, 0, 7, 8, 5, {1,1}, {1}, 0, 1000};
//     Weapon demon_fang("Demon fang", WPN_TYPE::TRINKET, temp_wpn);
//     demon_fang.setDescription("Ripped from the mouth of a dead demon.");
//     all_weapons["demon_fang"] = demon_fang;
//     temp_wpn = {7, 0, 0, 0, 0, 0, 7, 8, 5, {1,1}, {1}, 0, 1000};
//     Weapon angel_feather("Angel feather", WPN_TYPE::TRINKET, temp_wpn);
//     angel_feather.setDescription("Beautiful and fluffy. Given by incarnates and possessed to the worthy. Increases magical ability. Unusable by demons and demon incarnates.");
//     all_weapons["angel_feather"] = angel_feather;
//     temp_wpn = {7, 0, 0, 0, 0, 0, 7, 8, 5, {1,1}, {1}, 0, 1000};
//     Weapon angel_hair("Angel hair", WPN_TYPE::TRINKET, temp_wpn);
//     angel_hair.setDescription("Golden strands of angel hair held up by a silver thread. Increases magical ability. Unusable by demons and demon incarnates.");
//     all_weapons["angel_hair"] = angel_hair;
//     temp_wpn = {7, 0, 0, 0, 0, 0, 7, 8, 5, {1,1}, {1}, 0, 1000};
//     Weapon vial_of_light("Vial of light", WPN_TYPE::TRINKET, temp_wpn);
//     vial_of_light.setDescription("Light magically contained in glass. Shines brightest in darkness.");
//     all_weapons["vial_of_light"] = vial_of_light;       
//     temp_wpn = {7, 0, 0, 0, 0, 0, 7, 8, 5, {1,1}, {1}, 0, 1000};
//     Weapon glass_orb("Glass orb", WPN_TYPE::TRINKET, temp_wpn);
//     glass_orb.setDescription("Orb used to focus magical power.");
//     all_weapons["glass_orb"] = glass_orb;
//     temp_wpn = {7, 0, 0, 0, 0, 0, 7, 8, 5, {1,1}, {1}, 0, 1000};
//     Weapon war_horn("War horn", WPN_TYPE::TRINKET, temp_wpn);
//     war_horn.setDescription("Used to call for battle. Raise's close allies' combat abilities.");
//     all_weapons["war_horn"] = war_horn;    

//     temp_wpn = {0, 12, 76, 0, 0, 0, 11, 25, 7, {1,2}, {1,2}, 1, 1000};
//     Weapon ball_lightning("Ball lightning", WPN_TYPE::ELEMENTAL, temp_wpn);
//     ball_lightning.setDescription("Lightning, compressed and explosive.");
//     all_weapons["ball_lightning"] = ball_lightning;
//     temp_wpn = {0, 6, 70, 0, 0, 0, 5, 34, 7, {1,2}, {1,2}, 1, 1000};
//     Weapon icicle("Icicle", WPN_TYPE::ELEMENTAL, temp_wpn);
//     icicle.setDescription("Summons sharp and cold death spikes.");
//     all_weapons["icicle"] = icicle;
//     temp_wpn = {0, 14, 50, 0, 0, 0, 13, 20, 7, {1,2}, {1,2}, 1, 1000};
//     Weapon volcano("Volcano", WPN_TYPE::ELEMENTAL, temp_wpn);
//     volcano.setDescription("Summons magma spewing mountains from under enemies' feets.");
//     all_weapons["volcano"] = volcano;
//     temp_wpn = {0, 4, 80, 0, 0, 0, 3, 40, 7, {1,2}, {1,2}, 1, 1000};
//     Weapon wind_spear("wind_spear", WPN_TYPE::ELEMENTAL, temp_wpn);
//     wind_spear.setDescription("Invisible, swift and minuscule. Can pierce armor.");
//     all_weapons["wind_spear"] = wind_spear;
//     temp_wpn = {0, 6, 60, 0, 0, 0, 8, 30, 7, {1,2}, {1,2}, 1, 1000};
//     Weapon ember("Ember", WPN_TYPE::ELEMENTAL, temp_wpn);
//     ember.setDescription("Summon smoldering embers.");    
//     all_weapons["ember"] = ember;
//     temp_wpn = {0, 13, 40, 0, 0, 0, 11, 25, 7, {1,2}, {1,2}, 1, 1000};
//     Weapon tsunami("Tsunami", WPN_TYPE::ELEMENTAL, temp_wpn);
//     tsunami.setDescription("");
//     all_weapons["tsunami"] = tsunami;
//     temp_wpn = {0, 18, 50, 0, 0, 0, 11, 15, 7, {1,2}, {1,2}, 1, 1000};
//     Weapon God_forge_fire("The God Forge's Fire", WPN_TYPE::ELEMENTAL, temp_wpn);
//     God_forge_fire.setDescription("The fire used to forge Secundus, contained magically. Can melt any and all metals.");
//     all_weapons["God_forge_fire"] = God_forge_fire;
//     temp_wpn = {0, 11, 50, 0, 0, 0, 9, 20, 7, {1,2}, {1,2}, 1, 1000};
//     Weapon Fingolfin("Fingolfin", WPN_TYPE::ELEMENTAL, temp_wpn);
//     Fingolfin.setDescription("Distilled courage, strikes at darkness's heart, especially in times of despair. Effective against demons.");
//     Fingolfin.setEffective("Demon");
//     all_weapons["Fingolfin"] = Fingolfin;
//     temp_wpn = {0, 6, 65, 0, 0, 0, 5, 28, 7, {1,2}, {1,2}, 1, 1000};
//     Weapon Mithrandir("Mithrandir", WPN_TYPE::ELEMENTAL, temp_wpn);
//     Mithrandir.setDescription("Inspires courage in the hearts of men. Effective against demons.");
//     Mithrandir.setEffective("Demon");
//     Mithrandir.setEffect("Demon");
//     all_weapons["Mithrandir"] = Mithrandir;

//     temp_wpn = {0, 5, 70, 0, 0, 0, 5, 60, 7, {1,2}, {1,2}, 1, 1000};
//     Weapon _void("Void", WPN_TYPE::DEMONIC, temp_wpn);
//     _void.setDescription("");
//     all_weapons["void"] = _void;
//     temp_wpn = {0, 5, 70, 0, 0, 0, 5, 60, 7, {1,2}, {1,2}, 1, 1000};
//     Weapon nether("Nether", WPN_TYPE::DEMONIC, temp_wpn);
//     nether.setDescription("");
//     all_weapons["nether"] = nether;
//     temp_wpn = {0, 5, 70, 0, 0, 0, 5, 60, 7, {1,2}, {1,2}, 1, 1000};
//     Weapon downfall("Downfall", WPN_TYPE::DEMONIC, temp_wpn);
//     downfall.setDescription("");
//     all_weapons["downfall"] = downfall;
//     temp_wpn = {0, 5, 70, 0, 0, 0, 5, 60, 7, {1,2}, {1,2}, 1, 1000};
//     Weapon consume("Consume", WPN_TYPE::DEMONIC, temp_wpn);
//     consume.setDescription("");
//     all_weapons["consume"] = consume;
//     temp_wpn = {0, 5, 70, 0, 0, 0, 5, 60, 7, {1,2}, {1,2}, 1, 1000};
//     Weapon putrify("Putrify", WPN_TYPE::DEMONIC, temp_wpn);
//     putrify.setDescription("Brings out the inner rot.");
//     all_weapons["Putrify"] = putrify;
//     temp_wpn = {0, 5, 70, 0, 0, 0, 5, 60, 7, {1,2}, {1,2}, 1, 1000};
//     Weapon Glaurung("Glaurung", WPN_TYPE::DEMONIC, temp_wpn);
//     Glaurung.setDescription("");
//     all_weapons["Glaurung"] = Glaurung;
//     temp_wpn = {0, 5, 70, 0, 0, 0, 5, 60, 7, {1,2}, {1,2}, 1, 1000};
//     Weapon Morgoth("Morgoth", WPN_TYPE::DEMONIC, temp_wpn);
//     Morgoth.setDescription("Dark power, in the shape of a massive dark hammer. Makes craters wherever it strikes.");
//     all_weapons["Morgoth"] = Morgoth;
//     temp_wpn = {0, 5, 70, 0, 0, 0, 5, 60, 7, {1,2}, {1,2}, 1, 1000};
//     Weapon Gothmog("Gothmog", WPN_TYPE::DEMONIC, temp_wpn);
//     Gothmog.setDescription("Infernal whip of flame and shadows.");
//     all_weapons["Gothmog"] = Gothmog;
//     temp_wpn = {0, 5, 70, 0, 0, 0, 5, 60, 7, {1,2}, {1,2}, 1, 1000};
//     Weapon Fatalis("Fatalis", WPN_TYPE::DEMONIC, temp_wpn);
//     Fatalis.setDescription("");
//     all_weapons["Fatalis"] = Fatalis;
// }
